import{buildTestBlueprint}from'../test-builder.js';
import{createTestSession,navigate,setQuestionStatus,submissionSummary,submitTest,abandonTest}from'../test-session.js';
import{beginGrading,gradeBinary,gradingProgress,finalizeGrading,formatFrenchPoints}from'../test-grading.js';
import{buildTestResults}from'../test-results.js';
import{ExamBoardLifecycle}from'./exam-board-lifecycle.js';
import{TestPageLock}from'./test-page-lock.js';
import{TestStorage}from'../test-storage.js';
import{normalizeScene}from'../../board-model.js';
import{renderSegments,renderSteps}from'../../math/render-math.js';

const development=()=>['localhost','127.0.0.1',''].includes(globalThis.location?.hostname??'');
export class TestApp{
 constructor({root,board,onExit=()=>{},onFinalized=()=>{},pageLock=new TestPageLock()}){Object.assign(this,{root,board,onExit,onFinalized,pageLock});this.storage=new TestStorage();this.boardLifecycle=new ExamBoardLifecycle(board);this.session=null;this.timer=null;this.bind()}
 bind(){this.root.addEventListener('click',e=>{const target=e.target.closest('[data-test-action]');if(target)this.action(target.dataset.testAction,target)});this.root.addEventListener('change',()=>this.preview());this.preview()}
 open(){this.boardLifecycle.open();this.root.classList.remove('hidden');this.show('setup')}
 startWith({mode,chapterId,count}){if(mode!=='chapter-test'||!chapterId||![20,40].includes(Number(count)))throw new TypeError('Configuration de test de chapitre invalide.');this.boardLifecycle.open();this.root.classList.remove('hidden');const base=this.config();this.previewBlueprint=buildTestBlueprint({...base,scale:Number(count),scope:{partIds:[],chapterIds:[chapterId],notionIds:[]}});this.startFromBlueprint()}
 startFromBlueprint(){if(!this.previewBlueprint)return;this.session=createTestSession(this.previewBlueprint);this.boardLifecycle.start();this.pageLock.enable();this.show('runner');this.renderQuestion();this.save();this.tick()}
 close(){clearInterval(this.timer);this.timer=null;this.pageLock.disable();this.closeDialog();this.boardLifecycle.exit();this.root.classList.add('hidden')}
 config(){const f=new FormData(this.root.querySelector('form')),scale=Number(f.get('scale'));return{scale,seed:f.get('seed')||undefined,maximumLevel:Number(f.get('level')),trapsMode:f.get('traps'),durationMode:f.get('durationMode'),durationMinutes:Number(f.get('duration'))||(scale===40?60:30),orderMode:f.get('order'),compositionMode:f.get('composition'),scope:{partIds:[],chapterIds:[],notionIds:[]}}}
 preview(){try{const b=buildTestBlueprint(this.config());this.root.querySelector('[data-preview]').textContent=`${b.totals.questionCount} questions · ${b.scale} points · ${b.totals.estimatedMinutes} min estimées · graine ${b.seed}`;this.previewBlueprint=b}catch(error){this.previewBlueprint=null;this.report(error)}}
 async save(){if(this.session)await this.storage.save(this.session).catch(error=>this.report(error,'Le test n’a pas pu être enregistré. Le brouillon reste ouvert ; libérez de l’espace puis réessayez avant de fermer l’application.'))}
 show(name){for(const view of this.root.querySelectorAll('[data-view]'))view.classList.toggle('hidden',view.dataset.view!==name)}
 start(){this.preview();this.startFromBlueprint()}
 current(){const questions=this.session?.blueprint?.questions;return Array.isArray(questions)?questions[this.session.currentIndex]:undefined}
 ensureState(question){if(!question)throw new Error('La question courante est introuvable. La session reste ouverte.');if(!this.session.questionStates||typeof this.session.questionStates!=='object')this.session.questionStates={};return this.session.questionStates[question.instanceId]??=( {status:'unvisited',draft:null} )}
 stash(){if(this.session?.status!=='in-progress')return;const q=this.current(),state=this.ensureState(q);let captured;try{captured=this.board.capture()}catch(error){this.report(error,'Le dessin courant est endommagé. Les éléments lisibles ont été conservés et le test peut continuer.');captured=null}const{scene,issues}=normalizeScene(captured,{fallbackSpace:this.board.space});state.draft=scene;if(Array.isArray(scene.strokes)&&scene.strokes.length&&state.status==='unvisited')state.status='started';if(issues.length)this.message(`Brouillon réparé : ${issues.join(' ; ')}. Le test peut continuer.`);return scene}
 go(index){this.stash();navigate(this.session,index);this.renderQuestion();this.save()}
 renderQuestion(){const q=this.current(),state=this.ensureState(q),questions=this.session?.blueprint?.questions??[];renderSegments(this.root.querySelector('[data-statement]'),q.snapshot.statement);this.root.querySelector('[data-counter]').textContent=`Question ${q.order}/${questions.length} · ${q.points} points`;const p=this.root.querySelector('[data-progress]');p.value=q.order;p.max=questions.length;const{issues}=normalizeScene(state.draft,{fallbackSpace:this.board.space});this.boardLifecycle.showDraft(state.draft);if(issues.length&&state.draft!==null)this.message(`Brouillon réparé : ${issues.join(' ; ')}.`);const nav=this.root.querySelector('[data-navigator]');nav.replaceChildren(...questions.map((x,i)=>{const itemState=this.ensureState(x),b=document.createElement('button');b.type='button';b.dataset.index=i;b.dataset.testAction='jump';b.textContent=`${i+1} ${itemState.status==='review'?'⚑':'○'}`;b.setAttribute('aria-label',`Question ${i+1}, ${itemState.status}`);return b}))}
 openDialog(kind){const dialog=this.root.querySelector('[data-test-dialog]'),title=dialog.querySelector('[data-dialog-title]'),text=dialog.querySelector('[data-dialog-text]'),confirmButton=dialog.querySelector('[data-dialog-confirm]');if(kind==='submit'){const s=submissionSummary(this.session);title.textContent='Rendre le test ?';text.textContent=`${s.unvisited} question(s) non visitée(s) · ${s.review} question(s) à revoir.`;confirmButton.textContent='Rendre définitivement';confirmButton.dataset.testAction='confirm-submit'}else{title.textContent='Abandonner le test ?';text.textContent='Le test sera conservé sans note. Cette action ne pourra pas être annulée.';confirmButton.textContent='Abandonner';confirmButton.dataset.testAction='confirm-abandon'}dialog.showModal?.();dialog.setAttribute('open','');dialog.querySelector('[data-test-action="cancel-dialog"]').focus()}
 closeDialog(){const dialog=this.root.querySelector('[data-test-dialog]');if(!dialog)return;dialog.close?.();dialog.removeAttribute('open')}
 submit({automatic=false}={}){this.stash();if(!automatic){this.openDialog('submit');return}this.submitDefinitely()}
 submitDefinitely(){this.closeDialog();submitTest(this.session);this.boardLifecycle.lock();beginGrading(this.session,{role:'self'});this.show('grading');this.renderGrading();this.save()}
 abandonDefinitely(){this.closeDialog();this.stash();abandonTest(this.session);this.boardLifecycle.finish();this.pageLock.disable();this.save();this.message('Test abandonné — conservé sans note.');this.show('setup')}
 renderGrading(){const box=this.root.querySelector('[data-grading-list]');box.replaceChildren(...this.session.blueprint.questions.map(q=>{const section=document.createElement('section'),title=document.createElement('h3'),statement=document.createElement('div'),correction=document.createElement('div'),choices=document.createElement('div');title.textContent=`Question ${q.order} — 1 point`;renderSegments(statement,q.snapshot.statement);renderSteps(correction,q.snapshot.correction);choices.className='binary-grade';for(const[label,value]of[['Réussie — 1 point',true],['Ratée — 0 point',false]]){const button=document.createElement('button');button.type='button';button.dataset.testAction='binary-grade';button.dataset.instanceId=q.instanceId;button.dataset.succeeded=String(value);button.textContent=label;const score=this.session.grading.scores[q.instanceId];button.classList.toggle('selected',score?.succeeded===value);button.setAttribute('aria-pressed',String(score?.succeeded===value));choices.append(button)}section.append(title,statement,correction,choices);return section}));this.updateGradingProgress()}
 updateGradingProgress(){const p=gradingProgress(this.session),node=this.root.querySelector('[data-grading-progress]'),button=this.root.querySelector('[data-test-action="finalize"]');node.textContent=`${p.corrected} questions corrigées sur ${p.total}`;button.disabled=!p.complete}
 selectBinary(target){gradeBinary(this.session,target.dataset.instanceId,target.dataset.succeeded==='true');this.renderGrading();this.save()}
 grade(){finalizeGrading(this.session);this.show('results');const r=buildTestResults(this.session),parts=[`${r.successes} réussies`,`${r.failures} ratées`,`${formatFrenchPoints(r.points)}/${r.maxPoints}`];if(r.maxPoints===40)parts.push(`équivalent ${formatFrenchPoints(r.equivalent20)}/20`);parts.push(`${formatFrenchPoints(r.percentage)} %`,r.roleLabel);this.root.querySelector('[data-result]').textContent=parts.join(' · ');this.root.querySelector('[data-notions]').replaceChildren(...r.byNotion.map(n=>{const p=document.createElement('p');p.textContent=`${n.id} : ${formatFrenchPoints(n.points)} / ${n.maxPoints} — ${n.indication}`;return p}));this.boardLifecycle.finish();this.onFinalized(this.session);this.save()}
 tick(){clearInterval(this.timer);this.timer=setInterval(()=>{if(this.session?.status!=='in-progress')return;const node=this.root.querySelector('[data-timer]');if(this.session.deadlineAt===null){node.textContent='Sans chrono';return}const ms=Math.max(0,this.session.deadlineAt-Date.now());node.textContent=`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;if(!ms)this.submit({automatic:true})},1000)}
 message(text){const node=this.root.querySelector('[data-message]');node.textContent=text;node.hidden=!text}
 report(error,publicMessage='Une erreur empêche cette action. Votre session reste ouverte ; réessayez ou fermez après sauvegarde.'){this.message(publicMessage);if(development())console.error(error?.stack||error)}
 action(action,target){try{if(action==='start')this.start();else if(action==='prev')this.go(Math.max(0,this.session.currentIndex-1));else if(action==='next')this.go(Math.min((this.session.blueprint.questions?.length??1)-1,this.session.currentIndex+1));else if(action==='jump')this.go(Number(target.dataset.index));else if(action==='review'){setQuestionStatus(this.session,this.current().instanceId,'review');this.renderQuestion();this.save()}else if(action==='submit')this.submit();else if(action==='confirm-submit')this.submitDefinitely();else if(action==='abandon')this.openDialog('abandon');else if(action==='confirm-abandon')this.abandonDefinitely();else if(action==='cancel-dialog')this.closeDialog();else if(action==='binary-grade')this.selectBinary(target);else if(action==='finalize')this.grade();else if(action==='close'){this.close();this.onExit()}}catch(error){this.report(error)}}
}
