const uuid=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const normalizeEvaluation=value=>({easy:'success',hard:'partial',fragile:'partial',success:'success',partial:'partial',failed:'failed'}[value]||value);
export function createReviewEvent({question,selfEvaluation,hintUsed=false,correctionSeen,sessionId='review',now=new Date(),deviceId='local-device'}){
 if(!selfEvaluation)return null;
 let evaluation=normalizeEvaluation(selfEvaluation);if(hintUsed&&evaluation==='success')evaluation='partial';
 const occurredAt=new Date(now).toISOString(),level=Number(question.masteryLevel||question.difficulty||2);
 return{id:uuid(),version:1,eventType:'review-evaluation',occurredAt,recordedAt:occurredAt,partId:question.partId,chapterId:question.chapterId,notionId:question.notionId,source:{type:level===4?'trap':question.generator==='fixed'?'course-question':'generated-exercise',sourceId:question.templateId||question.id,sourceVersion:question.templateVersion||1,variantSignature:question.signature||question.fingerprint||question.id},evidence:{level,questionType:question.questionType||question.kind||'calculation',hintUsed:Boolean(hintUsed),correctionSeen:Boolean(correctionSeen),selfEvaluation:evaluation,scoreRatio:null,gradingMode:null},sessionId,testId:null,supersedesEventId:null,deletedAt:null,deviceId};
}
export function createTestEvents(session,{deviceId='local-device'}={}){
 if(session?.status!=='completed'||!session.grading?.finalizedAt)return[];
 const prior=new Map((session.grading.history||[]).map(x=>[x.questionInstanceId,x.eventId]));
 return session.blueprint.questions.flatMap(q=>{const score=session.grading.scores?.[q.instanceId];if(!score||!q.metadata?.notionId||!Number.isFinite(score.points)||!Number.isFinite(q.points)||q.points<=0)return[];const version=session.grading.revision||1;return[{id:`test:${session.id}:${q.instanceId}:v${version}`,version:1,eventType:'test-question-graded',occurredAt:new Date(session.grading.finalizedAt).toISOString(),recordedAt:new Date(session.grading.finalizedAt).toISOString(),partId:q.metadata.partId,chapterId:q.metadata.chapterId,notionId:q.metadata.notionId,source:{type:'chapter-test',sourceId:q.sourceId,sourceVersion:q.sourceVersion||1,variantSignature:q.variantSignature||q.instanceId},evidence:{level:q.metadata.level,questionType:q.metadata.category||'calculation',contentType:q.metadata.category,pointsObtained:score.points,pointsMaximum:q.points,scoreRatio:score.points/q.points,gradingMode:session.grading.role,hintUsed:false,correctionSeen:true},sessionId:null,testId:session.id,supersedesEventId:prior.get(q.instanceId)||null,deletedAt:null,deviceId}]});
}
