import{MASTERY_POLICY,clamp}from'./mastery-policy.js';import{emptyMastery}from'./mastery-model.js';import{activeEvents}from'./mastery-event-validator.js';
const DAY=86400000;
function outcome(e){if(e.eventType==='mastery-migration')return clamp((e.evidence.legacyMastery??0)/100,0,1);if(e.eventType==='test-question-graded')return e.evidence.scoreRatio;return MASTERY_POLICY.outcomes[e.evidence.selfEvaluation]?.value}
function weight(e,index,events,now){const age=Math.max(0,(now-Date.parse(e.occurredAt))/DAY),base=MASTERY_POLICY.sourceWeight[e.source?.type]||1,level=MASTERY_POLICY.levelWeight[e.evidence?.level]||1,grading=MASTERY_POLICY.gradingWeight[e.evidence?.gradingMode]||1,points=e.eventType==='test-question-graded'?clamp(Math.sqrt((e.evidence.pointsMaximum||1)/2),.7,1.45):1;const prior=events.slice(0,index),same=prior.filter(x=>x.source?.sourceId===e.source?.sourceId||x.source?.variantSignature===e.source?.variantSignature).length,sameSession=prior.filter(x=>x.sessionId&&x.sessionId===e.sessionId).length;return Math.min(MASTERY_POLICY.maxSingleEvidenceWeight,base*level*grading*points*Math.pow(.58,same)*Math.pow(.8,sameSession)*Math.pow(.5,age/MASTERY_POLICY.decayHalfLifeDays))}
export function deriveMastery(notionId,all,{now=Date.now()}={}){const events=activeEvents(all).filter(e=>e.notionId===notionId&&['review-evaluation','test-question-graded','mastery-migration'].includes(e.eventType)).sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt));const state=emptyMastery(notionId);if(!events.length)return state;let weighted=0,total=0,stability=0,difficulty=5,streak=0,lapses=0;const levels={1:[0,0],2:[0,0],3:[0,0],4:[0,0]},templates=new Set(),types=new Set(),days=new Set();events.forEach((e,i)=>{const value=outcome(e);if(!Number.isFinite(value))return;const w=weight(e,i,events,now);weighted+=value*w;total+=w;if(e.evidence.level){levels[e.evidence.level][0]+=value*w;levels[e.evidence.level][1]+=w}templates.add(e.source?.variantSignature||e.source?.sourceId);types.add(e.evidence?.questionType);days.add(e.occurredAt.slice(0,10));const result=e.evidence.selfEvaluation||(value>=.8?'easy':value>=.55?'hard':value>=.3?'fragile':'failed'),cfg=MASTERY_POLICY.outcomes[result];if(cfg){stability=stability?stability*cfg.multiplier:cfg.initialDays;difficulty=clamp(difficulty+cfg.difficulty,1,10);if(result==='failed'){lapses++;streak=0}else streak++}state.lastResult=result});
 state.evidenceCount=events.length;state.recentEvidenceCount=events.filter(e=>now-Date.parse(e.occurredAt)<=30*DAY).length;state.distinctTemplateCount=templates.size;state.distinctQuestionTypeCount=[...types].filter(Boolean).length;state.distinctLevelCount=Object.values(levels).filter(([,w])=>w>0).length;state.masteryScore=Math.round(clamp(weighted/Math.max(total,.01)*100,0,100));const diversity=templates.size*8+state.distinctQuestionTypeCount*8+state.distinctLevelCount*7+days.size*6;state.confidenceScore=Math.round(clamp(12*Math.log2(1+total)+diversity,0,100));state.stabilityDays=clamp(stability,MASTERY_POLICY.minStabilityDays,MASTERY_POLICY.maxStabilityDays);state.difficultyScore=Math.round(difficulty*10)/10;state.successStreak=streak;state.lapses=lapses;state.levelMastery=Object.fromEntries(Object.entries(levels).map(([k,[sum,w]])=>[k,w?Math.round(sum/w*100):null]));state.lastReviewedAt=events.at(-1).occurredAt;state.nextReviewAt=new Date(Date.parse(state.lastReviewedAt)+state.stabilityDays*DAY).toISOString();state.status=statusFor(state,now);return state}
export function estimatedRetention(state,now=Date.now()){if(!state.lastReviewedAt||!state.stabilityDays)return 0;const elapsed=Math.max(0,(now-Date.parse(state.lastReviewedAt))/DAY);return Math.round(clamp(state.masteryScore*Math.pow(.5,elapsed/Math.max(state.stabilityDays,.08)),0,100))}
export function statusFor(s,now=Date.now()){if(!s.evidenceCount)return'new';if(s.lastResult==='failed')return'needs-review';if(s.nextReviewAt&&Date.parse(s.nextReviewAt)<now)return'overdue';if(s.evidenceCount<2)return'discovery';if(s.masteryScore<50)return'fragile';if(s.masteryScore>=75&&s.confidenceScore>=60&&s.levelMastery[1]>=60)return'solid';return'progressing'}
export function rebuildMastery(events,notionIds,options){return Object.fromEntries(notionIds.map(id=>[id,deriveMastery(id,events,options)]))}
