const uuid=()=>globalThis.crypto?.randomUUID?.()||`local-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
export function createReviewEvent({question,selfEvaluation,hintUsed=false,correctionSeen,sessionId='review',now=new Date(),deviceId='local-device'}){
 if(!selfEvaluation)return null;
 const evaluation=hintUsed&&selfEvaluation==='easy'?'hard':selfEvaluation;
 const occurredAt=new Date(now).toISOString();
 return{id:uuid(),version:1,eventType:'review-evaluation',occurredAt,recordedAt:occurredAt,partId:question.partId,chapterId:question.chapterId,notionId:question.notionId,source:{type:question.difficulty===4?'trap':question.generator==='fixed'?'course-question':'generated-exercise',sourceId:question.templateId||question.id,sourceVersion:question.templateVersion||1,variantSignature:question.signature||question.fingerprint||question.id},evidence:{level:Number(question.difficulty),questionType:question.questionType||question.kind||'exercise',hintUsed:Boolean(hintUsed),correctionSeen:Boolean(correctionSeen),selfEvaluation:evaluation,scoreRatio:null,gradingMode:null},sessionId,testId:null,supersedesEventId:null,deletedAt:null,deviceId};
}
export function createTestEvents(session,{deviceId='local-device'}={}){
 if(session?.status!=='completed'||!session.grading?.finalizedAt)return[];
 const prior=new Map((session.grading.history||[]).map(x=>[x.questionInstanceId,x.eventId]));
 return session.blueprint.questions.flatMap(q=>{const score=session.grading.scores?.[q.instanceId];if(!score||!q.metadata?.notionId||!Number.isFinite(score.points)||!Number.isFinite(q.points)||q.points<=0)return[];const version=(session.grading.history?.length||0)+1;return[{id:`test:${session.id}:${q.instanceId}:v${version}`,version:1,eventType:'test-question-graded',occurredAt:new Date(session.grading.finalizedAt).toISOString(),recordedAt:new Date(session.grading.finalizedAt).toISOString(),partId:q.metadata.partId,chapterId:q.metadata.chapterId,notionId:q.metadata.notionId,source:{type:'chapter-test',sourceId:q.sourceId,sourceVersion:q.sourceVersion||1,variantSignature:q.variantSignature||q.instanceId},evidence:{level:q.metadata.level,questionType:q.metadata.category||'exercise',contentType:q.metadata.category,pointsObtained:score.points,pointsMaximum:q.points,scoreRatio:score.points/q.points,gradingMode:session.grading.role,hintUsed:false,correctionSeen:true},sessionId:null,testId:session.id,supersedesEventId:prior.get(q.instanceId)||null,deletedAt:null,deviceId}]}).concat({id:`test:${session.id}:final:v${(session.grading.history?.length||0)+1}`,version:1,eventType:'test-result-finalized',occurredAt:new Date(session.grading.finalizedAt).toISOString(),recordedAt:new Date(session.grading.finalizedAt).toISOString(),partId:session.blueprint.scope?.partId||'all',chapterId:session.blueprint.scope?.chapterId||'all',notionId:null,source:{type:'chapter-test',sourceId:session.id,sourceVersion:1,variantSignature:session.blueprint.signature},evidence:{scoreRatio:session.result.percentage/100,gradingMode:session.grading.role},sessionId:null,testId:session.id,supersedesEventId:null,deletedAt:null,deviceId});
}
