import test from'node:test';
import assert from'node:assert/strict';
import{DrawingBoard}from'../scripts/board.js';
import{VectorHistory}from'../scripts/board-model.js';
import{clampShapeCenter,shapeSize}from'../scripts/board-shapes.js';
import{readFile}from'node:fs/promises';

const event=(pointerType,x,y,id=7)=>({pointerType,pointerId:id,clientX:x,clientY:y,pressure:.9,timeStamp:10,preventDefault(){this.prevented=true},stopPropagation(){}});
function boardHarness(){const classes=new Set(),captures=new Set(),changes=[];const board=Object.assign(Object.create(DrawingBoard.prototype),{readOnly:false,shapeSize:'medium',shapeKind:null,activeShape:null,drawing:false,history:new VectorHistory(),space:{width:1024,height:768},transform:{scale:1,offsetX:0,offsetY:0},canvas:{classList:{add:x=>classes.add(x),remove:x=>classes.delete(x)},getBoundingClientRect:()=>({left:0,top:0,width:1024,height:768}),setPointerCapture:id=>captures.add(id),hasPointerCapture:id=>captures.has(id),releasePointerCapture:id=>captures.delete(id)},tool:{value:'pen'},storage:{values:new Map(),setItem(k,v){this.values.set(k,v)}},onPlacementChange:value=>changes.push(value),redraw(){this.redraws=(this.redraws||0)+1},persist(){this.persists=(this.persists||0)+1}});return{board,changes,classes}}

test('sélection et annulation ne créent ni objet ni historique',()=>{const{board,changes}=boardHarness();assert.equal(board.selectShape('circle','medium'),true);assert.equal(board.history.strokes.length,0);assert.equal(board.history.undoStack.length,0);assert.equal(changes.at(-1).active,true);assert.equal(board.cancelShapePlacement(),true);assert.equal(board.history.undoStack.length,0)});
test('seul le Pencil crée un aperçu qui suit la pointe, sans dépendre du hover',()=>{const{board}=boardHarness();board.selectShape('triangle','small');board.begin(event('touch',100,100));assert.equal(board.activeShape,null);board.begin(event('pen',100,120));assert.equal(board.activeShape.x,100);assert.equal(board.history.strokes.length,0);board.move(event('pen',440,360));assert.equal(board.activeShape.x,440);assert.equal(board.activeShape.y,360);assert.equal(board.history.undoStack.length,0)});
test('pointerup place une forme, une seule action undo, sauvegarde puis revient au stylo',()=>{const{board,changes}=boardHarness();board.selectShape('square','large');board.begin(event('pen',500,350));board.move(event('pen',520,370));board.end(event('pen',520,370));assert.equal(board.history.strokes.length,1);assert.equal(board.history.undoStack.length,1);assert.equal(board.persists,1);assert.equal(board.tool.value,'pen');assert.equal(board.shapeKind,null);assert.equal(changes.at(-1).placed,true);board.history.undo();assert.equal(board.history.strokes.length,0);board.history.redo();assert.equal(board.history.strokes.length,1)});
test('pointercancel annule un aperçu sans altérer les traits existants',()=>{const{board}=boardHarness(),existing={id:'ink'};board.history.strokes=[existing];board.selectShape('arrow');board.begin(event('pen',300,300));board.cancelPointer(event('pen',300,300));assert.deepEqual(board.history.strokes,[existing]);assert.equal(board.history.undoStack.length,0);assert.equal(board.persists,undefined)});
test('petite, moyenne et grande sont ordonnées et le placement reste dans les bords',()=>{const visible={width:1024,height:768},small=shapeSize('rectangle',visible,'small'),medium=shapeSize('rectangle',visible,'medium'),large=shapeSize('rectangle',visible,'large');assert.ok(small.width<medium.width&&medium.width<large.width);for(const center of [{x:-30,y:-20},{x:1100,y:900}]){const p=clampShapeCenter(center,large,visible);assert.ok(p.x-large.width/2>=0&&p.x+large.width/2<=visible.width);assert.ok(p.y-large.height/2>=0&&p.y+large.height/2<=visible.height)}});
test('le menu compact expose ouverture, fermeture, neuf choix, annulation et accessibilité',async()=>{const html=await readFile(new URL('../quiz.html',import.meta.url),'utf8'),app=await readFile(new URL('../scripts/app.js',import.meta.url),'utf8');assert.match(html,/aria-label="Choisir une forme mathématique"/);assert.equal((html.match(/data-board-shape=/g)||[]).length,9);assert.match(html,/Annuler le placement/);assert.match(html,/aria-live="polite"/);assert.match(app,/function setShapeMenu\(open\)/);assert.match(app,/shapeToggle.*addEventListener\('click'/);assert.match(app,/setShapeMenu\(false\)/)});
