import test from'node:test';
import assert from'node:assert/strict';
import{createBoardShape,defaultShapeSize,shapeGeometry,shapeTouchesGesture,SHAPE_KINDS}from'../scripts/board-shapes.js';
import{createStroke,deserializeScene,sceneTransform,serializeScene,VectorHistory}from'../scripts/board-model.js';
const shape=(kind,extra={})=>createBoardShape({id:`shape-${kind}`,kind,x:200,y:150,width:extra.width||180,height:extra.height||140,...extra});

test('les neuf formes sont des objets vectoriels valides et non dégénérés',()=>{for(const kind of SHAPE_KINDS){const value=shape(kind),g=shapeGeometry(value);assert.equal(value.type,'shape');assert.ok(g.paths.length+g.circles.length>0,kind);assert.ok(value.bounds.width>=24)}});
test('le repère orthonormé a deux axes orientés et des graduations de même unité',()=>{const g=shapeGeometry(shape('orthonormal-frame',{width:240,height:240})),axes=g.paths.filter(p=>p.arrow==='end');assert.equal(axes.length,2);const ticks=g.paths.filter(p=>p.arrow==='none').filter(p=>Math.hypot(p.to.x-p.from.x,p.to.y-p.from.y)===8);const xs=ticks.filter(p=>p.from.x===p.to.x).map(p=>Math.abs(p.from.x-200)).sort((a,b)=>a-b),ys=ticks.filter(p=>p.from.y===p.to.y).map(p=>Math.abs(p.from.y-150)).sort((a,b)=>a-b);assert.deepEqual([...new Set(xs)],[40,80]);assert.deepEqual([...new Set(ys)],[40,80])});
test('le cercle trigonométrique contient cercle, axes orientés, origine et quatre repères',()=>{const g=shapeGeometry(shape('trig-circle',{width:160}));assert.equal(g.circles.length,1);assert.equal(g.paths.filter(p=>p.arrow==='end').length,2);assert.deepEqual(g.labels.map(x=>x.text),['O','0','π/2','π','3π/2'])});
test('insertion et effacement d’une forme sont chacun groupés dans undo/redo',()=>{const s=shape('triangle'),h=new VectorHistory();h.perform({added:[s],removed:[]});assert.equal(h.strokes.length,1);h.undo();assert.equal(h.strokes.length,0);h.redo();assert.equal(h.strokes.length,1);h.perform({added:[],removed:[s]});assert.equal(h.strokes.length,0);h.undo();assert.equal(h.strokes.length,1)});
test('la gomme touche la géométrie sans viser les traits manuscrits voisins',()=>{const s=shape('rectangle'),gesture=createStroke({points:[{x:110,y:80},{x:112,y:100}],width:3});assert.equal(shapeTouchesGesture(s,gesture),true);const far=createStroke({points:[{x:10,y:10},{x:20,y:20}],width:3});assert.equal(shapeTouchesGesture(s,far),false)});
test('traits et formes coexistent, se sérialisent et se restaurent',()=>{const stroke=createStroke({id:'ink',points:[{x:1,y:2},{x:30,y:40}],width:3}),s=shape('arrow'),raw=serializeScene({space:{width:800,height:600},strokes:[stroke,s]});assert.equal(raw.includes('data:image'),false);const scene=deserializeScene(raw);assert.deepEqual(scene.strokes.map(x=>x.id),['ink','shape-arrow']);assert.equal(scene.strokes[1].type,'shape')});
test('les anciennes scènes version 1 migrent sans perdre leurs traits',()=>{const old={version:1,space:{width:100,height:80},strokes:[{id:'old',tool:'pen',type:'free',width:3,createdAt:1,points:[{x:1,y:2,pressure:.5,time:1},{x:3,y:4,pressure:.5,time:2}]}]},scene=deserializeScene(old);assert.equal(scene.strokes[0].id,'old');assert.equal(JSON.parse(serializeScene(scene)).version,2)});
test('NaN, Infinity, formats corrompus et dimensions dangereuses sont rejetés',()=>{for(const x of [NaN,Infinity,-Infinity])assert.throws(()=>shape('circle',{x}),/invalides/);assert.throws(()=>createBoardShape({kind:'inconnue',x:0,y:0,width:50,height:50}),/inconnue/);assert.throws(()=>deserializeScene({version:2,space:{width:10,height:10},objects:{}}),/invalides/)});
test('taille par défaut laisse de la place et le redimensionnement conserve la géométrie',()=>{for(const kind of SHAPE_KINDS){const size=defaultShapeSize(kind,{width:1000,height:700});assert.ok(size.width<500);assert.ok(size.height<350)}const s=shape('circle'),a=sceneTransform({width:1000,height:700},1000,700),b=sceneTransform({width:1000,height:700},700,1000);assert.equal(s.width*a.scale/s.height/a.scale,1);assert.equal(s.width*b.scale/s.height/b.scale,1)});
test('une scène de brouillon version 2 survit à capture/restore et à plusieurs rotations',()=>{let scene=deserializeScene(serializeScene({space:{width:1024,height:768},strokes:[shape('axes'),shape('circle',{x:400})]}));for(let i=0;i<10;i++){const t=sceneTransform(scene.space,i%2?768:1024,i%2?1024:768);assert.ok(Number.isFinite(t.scale));scene=deserializeScene(serializeScene(scene))}assert.equal(scene.strokes.length,2)});
