import test from'node:test';
import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{HANDEDNESS_KEY,readHandedness,writeHandedness,setDrawerState,setQuestionCollapsed,setToolState}from'../scripts/ui-state.js';

class Classes{constructor(...names){this.names=new Set(names)}toggle(name,force){if(force===undefined)force=!this.names.has(name);force?this.names.add(name):this.names.delete(name)}contains(name){return this.names.has(name)}}
const element=(classes=[])=>({classList:new Classes(...classes),attributes:{},setAttribute(name,value){this.attributes[name]=value}});

test('le tiroir s’ouvre, se ferme et reste un calque sans largeur réservée',async()=>{const drawer=element(),backdrop=element(['hidden']),button=element();setDrawerState({drawer,backdrop,button},true);assert.ok(drawer.classList.contains('open'));assert.equal(drawer.attributes['aria-hidden'],'false');assert.equal(drawer.inert,false);assert.equal(button.attributes['aria-expanded'],'true');setDrawerState({drawer,backdrop,button},false);assert.ok(!drawer.classList.contains('open'));assert.equal(drawer.inert,true);assert.ok(backdrop.classList.contains('hidden'));const css=await readFile(new URL('../styles/app.css',import.meta.url),'utf8');assert.match(css,/\.app-shell\{position:fixed;inset:/);assert.match(css,/\.drawer\{position:absolute;/);assert.doesNotMatch(css,/\.app-shell\{[^}]*grid-template-columns/)});

test('la préférence droitier ou gaucher est normalisée et persistée',()=>{const values=new Map(),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};assert.equal(readHandedness(storage),'right');assert.equal(writeHandedness('left',storage),'left');assert.equal(values.get(HANDEDNESS_KEY),'left');assert.equal(readHandedness(storage),'left');assert.equal(writeHandedness('inconnu',storage),'right')});

test('le bouton flottant bascule stylo et gomme avec un état actif visible',()=>{const select={value:'pen'},label={textContent:''},icon={textContent:''},button=element();button.querySelector=selector=>selector==='span'?icon:label;setToolState(select,button,'eraser');assert.equal(select.value,'eraser');assert.equal(button.attributes['aria-pressed'],'true');assert.equal(label.textContent,'Gomme');assert.match(button.attributes['aria-label'],/gomme/);setToolState(select,button,'pen');assert.equal(label.textContent,'Stylo');assert.equal(button.attributes['aria-pressed'],'false')});

test('la bulle se réduit et s’agrandit sans supprimer son contenu',()=>{const card=element(),button=element();button.textContent='';card.innerHTML='<p>Énoncé conservé</p>';setQuestionCollapsed(card,button,true);assert.ok(card.classList.contains('collapsed'));assert.equal(card.innerHTML,'<p>Énoncé conservé</p>');assert.equal(button.attributes['aria-expanded'],'false');setQuestionCollapsed(card,button,false);assert.ok(!card.classList.contains('collapsed'));assert.equal(card.innerHTML,'<p>Énoncé conservé</p>')});

test('progression de séance et maîtrise de notion sont deux indicateurs distincts',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/id="sessionProgress"/);assert.match(html,/Progression de la séance/);assert.match(html,/id="mastery"/);assert.match(html,/Maîtrise de la notion/);assert.notEqual(html.match(/id="sessionProgress"/)?.index,html.match(/id="mastery"/)?.index)});

test('les changements d’interface ne redimensionnent pas le canvas et la rotation ne déforme pas le dessin',async()=>{const app=await readFile(new URL('../scripts/app.js',import.meta.url),'utf8'),board=await readFile(new URL('../scripts/board.js',import.meta.url),'utf8');assert.doesNotMatch(app,/board\.resize\(.*(?:Drawer|Question)/);assert.match(board,/sceneTransform\(this\.space,r\.width,r\.height\)/);assert.match(board,/this\.redraw\(\)/);assert.doesNotMatch(board,/toDataURL|drawImage\(old/);for(const feature of ['pointerdown','pointermove','setPointerCapture','pressure','destination-out','touch-action:none'])assert.ok((board+await readFile(new URL('../styles/app.css',import.meta.url),'utf8')).includes(feature),`fonction tableau absente : ${feature}`)});

test('l’autoévaluation reste disponible seulement après la correction',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),app=await readFile(new URL('../scripts/app.js',import.meta.url),'utf8');assert.match(html,/id="evaluationButtons" class="evaluation hidden"/);assert.match(app,/correctionSeen=true/);assert.match(app,/if\(baseResult!==\s*'skipped'&&!correctionSeen\)return/);assert.match(app,/evaluationButtons'\)\.classList\.remove\('hidden'\)/)});

test('le cache hors connexion contient tous les modules importés requis',async()=>{const sw=await readFile(new URL('../service-worker.js',import.meta.url),'utf8'),files=[...sw.matchAll(/'\.\/(.*?)'/g)].map(match=>match[1]);for(const required of ['index.html','styles/app.css','scripts/app.js','scripts/board.js','scripts/ui-state.js','scripts/storage.js','scripts/course-map.js','scripts/quiz-engine.js','scripts/scheduler.js','scripts/fixed-questions.js','scripts/generator-utils.js','manifest.webmanifest','icon.svg'])assert.ok(files.includes(required),`cache manquant : ${required}`);const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/(?:src|href)=["']https?:\/\//)});
