import test from'node:test';import assert from'node:assert/strict';
import{legacyHtmlToSegments,normalizeSegments,normalizeSteps}from'../scripts/math/math-segments.js';
import{renderSegments,renderSteps}from'../scripts/math/render-math.js';
class Classes{constructor(){this.values=new Set()}add(...v){v.forEach(x=>this.values.add(x))}contains(v){return this.values.has(v)}}
class Node{constructor(tag='',text=''){this.tagName=tag;this._text=text;this.children=[];this.attributes={};this.classList=new Classes();this._className=''}set className(v){this._className=v;v.split(/\s+/).forEach(x=>x&&this.classList.add(x))}get className(){return this._className}append(...nodes){for(const node of nodes)this.children.push(typeof node==='string'?new Node('',node):node)}replaceChildren(...nodes){this.children=[];this._text='';this.append(...nodes)}setAttribute(k,v){this.attributes[k]=v}get textContent(){return this._text+this.children.map(x=>x.textContent).join('')}set textContent(v){this._text=String(v);this.children=[]}}
const document={createElement:tag=>new Node(tag),createTextNode:value=>new Node('',value)};
const katex={render(source,node,options){if(source.includes('\\bad'))throw Error('ParseError');node.textContent=source;node.setAttribute('data-rendered',String(options.displayMode))}};
const target=()=>new Node('div');

test('texte simple et HTML hostile restent du texte',()=>{const t=target();renderSegments(t,{segments:[{type:'text',value:'<img src=x onerror=alert(1)>'}]},{document,katex});assert.equal(t.textContent,'<img src=x onerror=alert(1)>');assert.equal(t.children[0].tagName,'');assert.equal(t.children.length,1)});
test('formules en ligne, en bloc et mélange texte/mathématiques',()=>{const t=target();renderSegments(t,{segments:[{type:'text',value:'Calculer '},{type:'math',value:'x^2',display:false},{type:'math',value:'\\frac{1}{2}',display:true}]},{document,katex});assert.equal(t.children[1].attributes['data-rendered'],'false');assert.equal(t.children[2].attributes['data-rendered'],'true');assert.ok(t.children[2].classList.contains('math-display'))});
for(const [name,formula]of Object.entries({fraction:'\\frac{a}{b}',exposant:'x^{-2}',indice:'u_{n+1}',racine:'\\sqrt{x}',logarithme:'\\ln|x|','valeur absolue':'\\lvert x\\rvert',trigonometrie:'\\cos(\\theta)',intervalle:']-\\infty,2]','ensemble de solutions':'S=\\{-1;1\\}','texte formule':'x=1\\quad\\text{ou}\\quad x=-1'}))test(`rend ${name}`,()=>{const t=target();renderSegments(t,{segments:[{type:'math',value:formula}]},{document,katex});assert.equal(t.textContent,formula);assert.ok(!t.children[0].classList.contains('math-fallback'))});
test('plusieurs étapes de correction',()=>{const t=target();renderSteps(t,{steps:[{segments:[{type:'text',value:'Étape 1'}]},{segments:[{type:'math',value:'x=2',display:true}]}]},{document,katex});assert.equal(t.children.length,2);assert.equal(t.children[1].textContent,'x=2')});
test('formule invalide utilise un fallback non vide et repérable',()=>{const t=target();renderSegments(t,{segments:[{type:'math',value:'\\bad{'}]},{document,katex,development:false});assert.equal(t.textContent,'\\bad{');assert.ok(t.children[0].classList.contains('math-fallback'));assert.equal(t.children[0].attributes['data-math-fallback'],'true')});
test('ancien format est converti sans interpréter le reste comme HTML',()=>{const segments=legacyHtmlToSegments('Soit <span class="math">x^2</span><script>danger</script>');assert.deepEqual(segments.map(x=>x.type),['text','math','text']);assert.equal(segments[2].value,'<script>danger</script>')});
test('segments invalides sont ignorés ou normalisés sans contenu vide',()=>{assert.equal(normalizeSegments({segments:[null,{type:'video',value:'x'}]})[0].value,'Contenu indisponible');assert.equal(normalizeSegments(42)[0].value,'42');assert.equal(normalizeSteps({steps:[{segments:[{type:'text',value:'ok'}]}]}).length,1)});

test('les exemples de fractions utilisent explicitement une fraction KaTeX verticale',()=>{for(const value of ['\\frac{3}{4}+\\frac{5}{6}','\\frac{x^2-1}{x-1}','\\frac{u_{n+1}}{u_n}','f(x)=\\frac{2x+1}{x-3}','\\frac{\\frac{a}{b}}{\\frac{c}{d}}','\\frac{x+1}{x-2}=3']){const t=target();renderSegments(t,{segments:[{type:'math',value}]},{document,katex});assert.match(t.textContent,/\\frac/);assert.ok(!t.children[0].classList.contains('math-fallback'))}});
test('les styles mathématiques héritent couleur, fond et opacité sans boîte',async()=>{const{readFile}=await import('node:fs/promises'),css=await readFile(new URL('../styles/katex-overrides.css',import.meta.url),'utf8');assert.match(css,/\.katex[^}]*color:inherit/);assert.match(css,/background:transparent/);assert.match(css,/box-shadow:none/);assert.match(css,/opacity:inherit/);assert.match(css,/\.math-inline\{display:inline/)});
test('les contenus représentatifs produisent des fractions LaTeX, pas des quotients typographiques',async()=>{const{generateFractionSimplify}=await import('../scripts/generators/fractions.js'),{generateArithmeticSequence}=await import('../scripts/generators/sequences.js'),{generatePrimitivePolynomial}=await import('../scripts/generators/primitives.js');for(const q of [generateFractionSimplify(),generateArithmeticSequence(),generatePrimitivePolynomial()]){const math=[...q.question.segments,...q.correction.steps.flatMap(step=>step.segments)].filter(s=>s.type==='math').map(s=>s.value).join(' ');assert.match(math,/\\d?frac/);assert.doesNotMatch(math,/[}\w)]\/[({\w]/)}});
