import test from'node:test';import assert from'node:assert/strict';import{UserWorkspace}from'../scripts/workspace/user-workspace.js';import{ProgressOutbox}from'../scripts/progress-sync/progress-outbox.js';import{ProgressSyncCoordinator}from'../scripts/progress-sync/progress-sync-coordinator.js';import{ProgressSyncClient}from'../scripts/progress-sync/progress-sync-client.js';import{safeSyncError}from'../scripts/progress-sync/progress-sync-errors.js';
import{readFile}from'node:fs/promises';
class Memory{constructor(){this.m=new Map}getItem(k){return this.m.get(k)??null}setItem(k,v){this.m.set(k,v)}}
const U1='11111111-1111-4111-8111-111111111111',U2='22222222-2222-4222-8222-222222222222';
const event=(id,notionId='n')=>({id,version:1,eventType:'review-evaluation',notionId,occurredAt:'2026-01-01T00:00:00.000Z',recordedAt:'2026-01-01T00:00:00.000Z',evidence:{level:1,selfEvaluation:'easy'},source:{type:'generated',deviceId:'d'}});
test('outbox ajoute, déduplique, isole et survit au rechargement',()=>{const storage=new Memory,a=new ProgressOutbox(new UserWorkspace(U1,{storage})),b=new ProgressOutbox(new UserWorkspace(U2,{storage}));a.enqueue(['e1','e1']);assert.deepEqual(new ProgressOutbox(new UserWorkspace(U1,{storage})).read().eventIds,['e1']);assert.deepEqual(b.read().eventIds,[])});
test('première synchronisation inscrit tout l historique une seule fois',()=>{const o=new ProgressOutbox(new UserWorkspace(U1,{storage:new Memory}));o.initialize([event('a'),event('b')]);o.initialize([event('a')]);assert.deepEqual(o.read().eventIds,['a','b'])});
test('client impose user_id et insertion idempotente',async()=>{let rows,options;const query={upsert:async(r,o)=>(rows=r,options=o,{error:null})};const client=new ProgressSyncClient({from:()=>query},U1);await client.push([event('a')]);assert.equal(rows[0].user_id,U1);assert.equal(options.ignoreDuplicates,true)});
function coordinator({events=[event('local')],pages=[],saveFails=false}={}){const workspace=new UserWorkspace(U1,{storage:new Memory});let state={masteryEvents:events,masteryStates:{},reviewQueue:[]},pushes=[];const client={pageSize:2,push:async es=>(pushes.push(...es),es.map(e=>e.id)),pull:async()=>pages.shift()||[]};const c=new ProgressSyncCoordinator({workspace,client,loadState:()=>state,saveState:s=>{if(saveFails)throw Error('disk');state=s;return s},notions:[{id:'n',chapterId:'c'}]});return{c,state:()=>state,pushes}}
test('erreur réseau conserve l outbox et le curseur',async()=>{const x=coordinator();x.c.client.push=async()=>{throw Error('network')};x.c.start();await assert.rejects(x.c.sync());assert.deepEqual(x.c.outbox.read().eventIds,['local']);assert.equal(x.c.outbox.read().lastPulledServerSeq,0)});
test('fusion paginée déduplique, conserve le local et recalcule la maîtrise',async()=>{const remote=event('remote'),row={event_id:'remote',event_version:1,event_type:remote.eventType,event_payload:remote,server_seq:2};const x=coordinator({pages:[[row],[]]});x.c.start();await x.c.sync();assert.deepEqual(x.state().masteryEvents.map(e=>e.id),['local','remote']);assert.equal(x.state().masteryStates.n.evidenceCount,2);assert.equal(x.c.outbox.read().lastPulledServerSeq,2)});
test('événement distant invalide est mis en quarantaine sans bloquer',async()=>{const x=coordinator({pages:[[{event_id:'bad',event_version:1,event_type:'bad',event_payload:{id:'bad'},server_seq:3}]]});x.c.start();await x.c.sync();assert.equal(x.c.outbox.read().quarantine[0].event_id,'bad');assert.equal(x.c.outbox.read().lastPulledServerSeq,3)});
test('curseur avance uniquement après sauvegarde',async()=>{const e=event('r'),x=coordinator({saveFails:true,pages:[[{event_id:'r',event_version:1,event_type:e.eventType,event_payload:e,server_seq:4}]]});x.c.start();await assert.rejects(x.c.sync());assert.equal(x.c.outbox.read().lastPulledServerSeq,0)});
test('changement de compte invalide une réponse tardive',async()=>{let release;const x=coordinator();x.c.client.push=()=>new Promise(r=>release=()=>r(['local']));x.c.start();const pending=x.c.sync();x.c.stop();release();await pending;assert.deepEqual(x.c.outbox.read().eventIds,['local'])});
test('synchronisation manuelle ignore navigator.onLine',async()=>{const x=coordinator({events:[]});let calls=0;x.c.client.pull=async()=>{calls++;return[]};x.c.start();await x.c.sync();assert.equal(calls,1)});
test('diagnostic expurge secrets et clés',()=>{assert.doesNotMatch(safeSyncError('access_token password sb_secret_ eyJabc'),/access_token|password|sb_secret_|eyJabc/i)});
test('migration SQL est append-only, privée et sans privilège admin',async()=>{const sql=await readFile(new URL('../supabase/migrations/20260727210000_progress_events.sql',import.meta.url),'utf8');assert.match(sql,/enable row level security/i);assert.match(sql,/grant select, insert[^;]+authenticated/i);assert.doesNotMatch(sql,/grant[^;]+update|grant[^;]+delete/i);assert.equal((sql.match(/auth\.uid\(\)/g)||[]).length,2);assert.doesNotMatch(sql,/profiles|admin|owner|email/i);assert.match(sql,/primary key \(user_id, event_id\)/i);assert.match(sql,/jsonb_typeof\(event_payload\) = 'object'/i)});
