import test from'node:test';
import assert from'node:assert/strict';
import{readFile}from'node:fs/promises';
import{SESSION_MODES,QUESTION_TYPES,DIFFICULTIES,RESULT_STATES,normalizeQuestion,resolveEvaluation,buildSessionPlan,normalizeSessionConfig,recordPlanResult}from'../scripts/session/session-model.js';

test('la refonte expose exactement quatre séances, quatre types et trois difficultés',()=>{assert.deepEqual(Object.values(SESSION_MODES),['daily','consolidation','free','chapter-test']);assert.deepEqual(Object.values(QUESTION_TYPES),['formula','course','calculation','reflex']);assert.deepEqual(Object.values(DIFFICULTIES),[1,2,4])});
test('indice ou dépassement transforme une réussite en réussite partielle',()=>{assert.equal(resolveEvaluation({choice:'success'}),RESULT_STATES.SUCCESS);assert.equal(resolveEvaluation({choice:'success',hintUsed:true}),RESULT_STATES.PARTIAL);assert.equal(resolveEvaluation({choice:'success',timeExceeded:true}),RESULT_STATES.PARTIAL);assert.equal(resolveEvaluation({choice:'failed',hintUsed:true,timeExceeded:true}),RESULT_STATES.FAILED)});
test('une ancienne difficulté 3 devient un type Réflexe chronométré',()=>{const question=normalizeQuestion({id:'legacy',difficulty:3,kind:'Calcul'});assert.equal(question.questionType,'reflex');assert.equal(question.difficulty,null);assert.equal(question.masteryLevel,3);assert.equal(question.timeLimitSeconds,60)});
test('la révision du jour suit les erreurs du dernier test',()=>{const state={masteryEvents:[{eventType:'test-question-graded',testId:'test-old',notionId:'powers-product',occurredAt:'2026-07-20T10:00:00.000Z',evidence:{scoreRatio:0}},{eventType:'test-question-graded',testId:'test-latest',notionId:'powers-product',occurredAt:'2026-07-28T10:00:00.000Z',evidence:{scoreRatio:0}},{eventType:'test-question-graded',testId:'test-latest',notionId:'powers-product',occurredAt:'2026-07-28T10:01:00.000Z',evidence:{scoreRatio:0}},{eventType:'test-question-graded',testId:'test-latest',notionId:'powers-negative',occurredAt:'2026-07-28T10:02:00.000Z',evidence:{scoreRatio:1}}]};const plan=buildSessionPlan({mode:'daily'},state);assert.equal(plan.length,1);assert.equal(plan[0].notionId,'powers-product');assert.equal(plan[0].questionCount,4);assert.equal(plan[0].successes,0)});
test('le score de notion compte les réussites et les réussites partielles séparément',()=>{let config=normalizeSessionConfig({mode:'daily',plan:[{notionId:'powers-product',label:'Produit',questionCount:2}]},{});config=recordPlanResult(config,'success');config=recordPlanResult(config,'partial');assert.equal(config.plan[0].answered,2);assert.equal(config.plan[0].successes,1);assert.equal(config.plan[0].partials,1);assert.equal(config.plan[0].failures,0)});
test('les interfaces ne proposent plus Presque réussi ni la difficulté Réflexe prépa',async()=>{const[sessionPage,questions,app,dom]=await Promise.all([readFile(new URL('../scripts/pages/session-page.js',import.meta.url),'utf8'),readFile(new URL('../questions.html',import.meta.url),'utf8'),readFile(new URL('../scripts/app.js',import.meta.url),'utf8'),readFile(new URL('../scripts/session/session-dom.js',import.meta.url),'utf8')]);assert.doesNotMatch(sessionPage,/Révision intelligente|Cours express|Formules essentielles/);assert.match(sessionPage,/Révision du jour/);assert.match(sessionPage,/Consolidation des points faibles/);assert.doesNotMatch(questions,/Réflexe prépa/);assert.doesNotMatch(app,/almostButton/);assert.match(dom,/questionTimer/)});
