import test from'node:test';import assert from'node:assert/strict';
import{createOperation,validateOperation,serializeOperation}from'../scripts/sync/operation.js';import{sha256}from'../scripts/sync/integrity.js';import{calculateBackoff,SyncOutbox}from'../scripts/sync/outbox.js';import{SyncClient}from'../scripts/sync/client.js';import{applyBatch,createManifest,validateManifest,stateFingerprint}from'../scripts/sync/server-core.js';import{mergeDraft,mergeEvents,mergePreference,reconstructSnapshot}from'../scripts/sync/merge.js';import{createSyncDiagnostic}from'../scripts/sync/diagnostic.js';
const deviceId='11111111-1111-4111-8111-111111111111';
const make=(overrides={})=>createOperation({deviceId,operationType:'append-event',entityType:'mastery-event',entityId:overrides.payload?.id||crypto.randomUUID(),payload:{id:crypto.randomUUID(),value:1},...overrides});
class MemoryOutbox extends SyncOutbox{constructor(now=()=>1000){super({},now);this.records=new Map()}async tx(mode,callback){const request={result:undefined},store={get:id=>(request.result=structuredClone(this.records.get(id)),request),getAll:()=>(request.result=[...this.records.values()].map(value=>structuredClone(value)),request),add:value=>{if(this.records.has(value.operationId))throw Error('duplicate');this.records.set(value.operationId,structuredClone(value));return request},put:value=>{this.records.set(value.operationId,structuredClone(value));return request},delete:id=>{this.records.delete(id);return request}};callback(store);return request.result}}

test('création, UUID unique, validation, sérialisation et checksum stable',async()=>{const a=await make(),b=await make();assert.notEqual(a.operationId,b.operationId);assert.equal((await validateOperation(a)).valid,true);assert.equal(await sha256({b:2,a:1}),await sha256({a:1,b:2}));assert.equal(serializeOperation(a),serializeOperation(structuredClone(a)))});
test('NaN, Infinity, mauvais checksum et limite de taille sont rejetés',async()=>{await assert.rejects(()=>make({payload:{n:NaN}}),/non finie/);await assert.rejects(()=>make({payload:{n:Infinity}}),/non finie/);const op=await make();op.checksum='0'.repeat(64);assert.equal((await validateOperation(op)).errors[0].code,'CHECKSUM_INVALID');await assert.rejects(()=>make({payload:{text:'x'.repeat(260000)}}),error=>error.code==='PAYLOAD_TOO_LARGE')});
test('outbox persistante: ajout idempotent, lot, confirmation et purge sélective',async()=>{const box=new MemoryOutbox(),a=await make(),b=await make();await box.add(a);await box.add(a);await box.add(b);assert.equal((await box.batch(1)).operations.length,1);await box.confirm([a.operationId]);assert.equal((await box.get(a.operationId)).status,'confirmed');await box.purgeConfirmed();assert.equal(await box.get(a.operationId),undefined);assert.ok(await box.get(b.operationId))});
test('rejet et nouvel essai conservent les données avec backoff',async()=>{let now=1000;const box=new MemoryOutbox(()=>now),op=await make();await box.add(op);assert.deepEqual([1,2,3,4].map(n=>calculateBackoff(n,{baseMs:1000,jitter:0})),[1000,2000,4000,8000]);await box.retry(op.operationId,{code:'NETWORK_OFFLINE',message:'secret sans contenu'});const retry=await box.get(op.operationId);assert.equal(retry.attemptCount,1);assert.equal(retry.nextRetryAt,2000);assert.equal(retry.status,'retry');await box.reject(op.operationId,new Error('refus'));assert.equal((await box.get(op.operationId)).status,'rejected')});
test('UUID local dupliqué avec contenu différent produit un conflit',async()=>{const box=new MemoryOutbox(),a=await make();await box.add(a);const b=await make({operationId:a.operationId});await assert.rejects(()=>box.add(b),error=>error.code==='SERVER_CONFLICT')});
const response=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>typeof body==='string'?JSON.parse(body):body});
test('client utilise POST text/plain, sans clé dans URL, et expose toutes les actions',async()=>{const calls=[];const client=new SyncClient({endpointUrl:'https://example.test/exec',key:'cle-test-seulement',fetchImpl:async(url,options)=>(calls.push({url:String(url),options}),response({ok:true,protocolVersion:1}))});for(const call of [()=>client.health(),()=>client.initialize({}),()=>client.push({}),()=>client.pull({}),()=>client.sync({}),()=>client.getManifest()])await call();assert.equal(calls.length,6);assert.equal(calls[0].options.method,'POST');assert.equal(calls[0].options.headers['Content-Type'],'text/plain;charset=utf-8');assert.doesNotMatch(calls[0].url,/cle-test/);assert.match(calls[0].options.body,/"key"/) });
test('client classe réseau absent, timeout, JSON invalide et erreurs HTTP',async()=>{await assert.rejects(()=>new SyncClient({endpointUrl:'https://x.test',key:'x',fetchImpl:async()=>{throw Error('offline')}}).health(),e=>e.code==='NETWORK_OFFLINE');await assert.rejects(()=>new SyncClient({endpointUrl:'https://x.test',key:'x',timeoutMs:2,fetchImpl:(u,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error(),{name:'AbortError'}))))}).health(),e=>e.code==='NETWORK_OFFLINE');await assert.rejects(()=>new SyncClient({endpointUrl:'https://x.test',key:'x',fetchImpl:async()=>response('pas json')}).health(),e=>e.code==='REMOTE_DATA_CORRUPTED');for(const [status,code]of[[403,'AUTH_INVALID'],[429,'QUOTA_EXCEEDED'],[500,'APPS_SCRIPT_ERROR']])await assert.rejects(()=>new SyncClient({endpointUrl:'https://x.test',key:'x',fetchImpl:async()=>response({},status)}).health(),e=>e.code===code)});
test('manifest checksum et révision monotone',async()=>{const manifest=await createManifest({serverRevision:2,installationId:deviceId});assert.equal(await validateManifest(manifest),true);manifest.serverRevision=3;assert.equal(await validateManifest(manifest),false)});
test('backend pur déduplique et reste idempotent',async()=>{const op=await make({payload:{id:'event-1',value:1},entityId:'event-1'}),initial={serverRevision:0,events:[],entities:{},preferences:{},processedOperations:{}};const first=await applyBatch(initial,{baseServerRevision:0,operations:[op,op]});assert.equal(first.state.events.length,1);assert.deepEqual(first.response.acceptedOperationIds,[op.operationId,op.operationId]);const second=await applyBatch(first.state,{baseServerRevision:1,operations:[op]});assert.equal(second.state.events.length,1);assert.equal(stateFingerprint(first.state).includes('event-1'),true);await assert.rejects(()=>applyBatch(first.state,{baseServerRevision:0,operations:[]}),e=>e.code==='SERVER_CONFLICT')});
test('même événement divergent et brouillons divergents restent en conflit',()=>{const a={id:'e',value:1},b={id:'e',value:2};assert.equal(mergeEvents([a],[a]).events.length,1);assert.equal(mergeEvents([a],[b]).conflicts[0].type,'event-content-mismatch');const draft=mergeDraft({id:'d',strokes:[1]},{id:'d',strokes:[2]});assert.equal(draft.variants.length,2);assert.equal(draft.conflicts[0].type,'draft-diverged')});
test('préférences fusionnées par date puis deviceId et reconstruction snapshot',()=>{assert.equal(mergePreference({value:1,updatedAt:'2026-01-01',deviceId:'a'},{value:2,updatedAt:'2026-01-01',deviceId:'b'}).value,2);const result=reconstructSnapshot({events:[{id:'a'}]},[{id:'b'}]);assert.deepEqual(result.snapshot.events.map(e=>e.id),['a','b'])});
test('diagnostic exclut endpoint, clé et contenu des brouillons',()=>{const diagnostic=createSyncDiagnostic({config:{endpointUrl:'https://secret',protocolVersion:1},outbox:[{status:'pending',payload:{draft:'personnel'}}]});const raw=JSON.stringify(diagnostic);assert.doesNotMatch(raw,/https:\/\/secret|personnel|token/i);assert.equal(diagnostic.keyConfigured,false)});

test('Apps Script limite les actions, verrouille, hash la clé et interdit les entrées Drive client',async()=>{const{readFile}=await import('node:fs/promises'),source=await readFile(new URL('../apps-script/Code.gs',import.meta.url),'utf8');assert.match(source,/SYNC_ACTIONS=Object\.freeze/);assert.match(source,/LockService\.getScriptLock/);assert.match(source,/SYNC_KEY_SHA256/);assert.match(source,/constantTimeEqual_/);assert.doesNotMatch(source,/\beval\s*\(/);assert.doesNotMatch(source,/data\.(?:fileId|path|folder)/);assert.match(source,/serverRevision:revision/)});
test('moteur écrit avant réseau et conserve chaque opération après panne',async()=>{const{LocalFirstSyncEngine}=await import('../scripts/sync/engine.js');const box=new MemoryOutbox(),config={deviceId,lastServerRevision:0},saved=[];let called=false;const engine=new LocalFirstSyncEngine({outbox:box,config,saveConfig:c=>saved.push({...c}),client:{sync:async()=>{called=true;throw Error('offline')}}});const record=await engine.enqueue({operationType:'upsert-entity',entityType:'test-result',entityId:'result-1',payload:{version:1}});assert.ok(await box.get(record.operationId));await assert.rejects(()=>engine.syncOnce());assert.equal(called,true);const pending=await box.get(record.operationId);assert.equal(pending.status,'retry');assert.equal(pending.attemptCount,1);assert.ok(saved[0].lastAttemptAt)});
