import test from'node:test';import assert from'node:assert/strict';
import{TRAP_TEMPLATES}from'../scripts/traps/templates/catalog.js';
import{TrapRegistry}from'../scripts/traps/trap-registry.js';
import{validateGeneratedTrap,validateTrapTemplate}from'../scripts/traps/trap-validator.js';
import{validateTrapTemplateSchema}from'../scripts/traps/trap-schema.js';
import{fraction}from'../scripts/traps/trap-utils.js';

test('la banque contient 25 modèles validés et les sept chapitres centraux',()=>{assert.equal(TRAP_TEMPLATES.length,25);for(const template of TRAP_TEMPLATES)assert.deepEqual(validateTrapTemplate(template),{valid:true,errors:[]});const chapters=new Set(TRAP_TEMPLATES.map(t=>t.chapterId));for(const id of ['powers','rational','equations','sequences','derivatives','primitives','trigonometry','differential'])assert.ok(chapters.has(id))});
test('le schéma rejette explicitement un modèle incomplet ou ordinaire',()=>{const result=validateTrapTemplateSchema({id:'bad.template',version:1,level:3});assert.equal(result.valid,false);assert.match(result.errors.join(' '),/niveau 4|manquant/)});
test('les fractions exactes refusent zéro et normalisent les signes',()=>{assert.deepEqual(fraction(6,-8),{numerator:-3,denominator:4});assert.throws(()=>fraction(1,0),/invalide/)});
for(const template of TRAP_TEMPLATES)test(`${template.id} produit 200 variantes cohérentes et au moins vingt signatures`,()=>{const signatures=new Set(),forms=new Set();for(let seed=1;seed<=200;seed++){const question=template.generate(seed),validation=validateGeneratedTrap(question),correctionText=question.correction.steps.flatMap(step=>step.segments).map(segment=>segment.value).join(' ');assert.equal(validation.valid,true,validation.errors.join(' '));assert.equal(question.difficulty,4);assert.equal(question.templateId,template.id);assert.equal(question.oracle(),question.finalAnswer.value);assert.ok(correctionText.includes(question.finalAnswer.value),'la correction doit aboutir à la réponse exacte');assert.equal(question.validation.correctionMatchesOracle,true);assert.ok(question.question.segments.some(segment=>segment.type==='math'));assert.ok(question.correction.steps.length>=3);assert.ok(question.trapExplanation.commonMistake);assert.doesNotMatch(JSON.stringify(question),/NaN|Infinity/);signatures.add(question.signature);forms.add(question.kind)}assert.ok(signatures.size>=20,`${signatures.size} signatures`);assert.ok(forms.size>=2,'les formulations doivent varier')});
test('le registre ne fournit aucun fallback silencieux de niveau 4',()=>{const registry=new TrapRegistry(TRAP_TEMPLATES);const missing=registry.generate({notionId:'limit-polynomial'},{},1);assert.equal(missing.status,'missing-coverage');assert.equal(missing.reason,'no-validated-template')});
test('la sélection varie modèles, signatures et taxonomies pendant une séance',()=>{const registry=new TrapRegistry(TRAP_TEMPLATES),session={templates:[],signatures:[],taxonomies:[]};for(let seed=1;seed<=12;seed++){const q=registry.generate({chapterId:'powers'},session,seed);assert.notEqual(q.status,'missing-coverage');session.templates.push(q.templateId);session.signatures.push(q.signature);session.taxonomies.push(q.trap.taxonomyId)}assert.ok(new Set(session.templates).size>=3);assert.equal(new Set(session.signatures).size,12);assert.ok(new Set(session.taxonomies).size>=2)});
