import{TeamAdminClient}from'./team-admin-client.js';import{counts,filterUsers}from'./team-model.js';import{userCard,renderAudit}from'./team-view.js';import{invitationDialog,roleDialog,suspensionDialog,reactivationDialog}from'./team-dialogs.js';import{toast}from'../shell/toast.js';
const PAGE_SIZE=12;let users=[],filter='all',page=1,busy=false,api;
export async function init({client}){api=client?new TeamAdminClient(client):null;const offline=!navigator.onLine||!client;setOffline(offline);document.querySelector('[data-invite]').onclick=()=>invitationDialog(async data=>{await locked(async()=>{await api.invoke('invite-user',data);toast(`Invitation envoyée à ${data.email}.`,{timeout:0});await load()})});document.querySelector('[data-refresh]').onclick=load;document.querySelector('[data-audit-refresh]').onclick=loadAudit;document.querySelector('[data-search]').oninput=()=>{page=1;render()};document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;page=1;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===button)));render()});addEventListener('online',()=>{setOffline(false);load();loadAudit()});addEventListener('offline',()=>{users=[];setOffline(true);render()});if(!offline){await Promise.all([load(),loadAudit()])}}
async function locked(work){if(busy)return;busy=true;document.querySelectorAll('.team-page button').forEach(x=>x.disabled=true);try{await work()}finally{busy=false;document.querySelectorAll('.team-page button').forEach(x=>x.disabled=false)}}
async function load(){if(!api||!navigator.onLine)return;try{const data=await api.invoke('list-users');users=data.users;render()}catch(e){users=[];message(e.message);toast(e.message,{type:'error'});renderCounts()}}
async function loadAudit(){if(!api||!navigator.onLine)return;try{const data=await api.invoke('list-audit',{page:1,perPage:20});renderAudit(document.querySelector('[data-audit]'),data.entries)}catch(e){document.querySelector('[data-audit]').textContent=e.message}}
function render(){const found=filterUsers(users,document.querySelector('[data-search]').value,filter),start=(page-1)*PAGE_SIZE,shown=found.slice(start,start+PAGE_SIZE),root=document.querySelector('[data-users]');renderCounts();root.hidden=!shown.length;root.replaceChildren(...shown.map(x=>userCard(x,{role:u=>roleDialog(u,next=>changeRole(u,next)),suspend:u=>suspensionDialog(u,()=>suspend(u)),reactivate:u=>reactivationDialog(u,()=>reactivate(u))})));message(shown.length?'':users.length?'Aucun compte ne correspond à cette recherche.':'Aucun compte disponible.');const pages=Math.ceil(found.length/PAGE_SIZE),nav=document.querySelector('[data-pagination]');nav.replaceChildren(...Array.from({length:pages},(_,i)=>{const b=document.createElement('button');b.className='secondary';b.textContent=String(i+1);b.setAttribute('aria-current',i+1===page?'page':'false');b.onclick=()=>{page=i+1;render()};return b}))}
function renderCounts(){const c=counts(users);for(const[k,v]of Object.entries(c))document.querySelector(`[data-count=${k}]`).textContent=String(v)}function message(text){const n=document.querySelector('[data-team-message]');n.hidden=!text;n.textContent=text}function setOffline(value){document.querySelector('[data-offline]').hidden=!value;document.querySelectorAll('[data-invite],[data-refresh],[data-audit-refresh]').forEach(x=>x.disabled=value);if(value)message('La gestion de l’équipe nécessite une connexion Internet.')}
async function changeRole(user,role){await locked(async()=>{try{await api.invoke('set-role',{userId:user.id,role,expectedRole:user.role});toast('Les droits ont été mis à jour.')}finally{await load()}})}async function suspend(user){await locked(async()=>{await api.invoke('suspend-user',{userId:user.id});toast('Le compte est suspendu.');await load();await loadAudit()})}async function reactivate(user){await locked(async()=>{await api.invoke('reactivate-user',{userId:user.id});toast('Le compte est réactivé.');await load();await loadAudit()})}
