import{COURSE_MAP,allNotions}from'../course-map.js';
import{SESSION_MODES,QUESTION_TYPES,buildSessionPlan,normalizeSessionConfig}from'./session-model.js';
import{SESSION_CHOICES,renderSessionContent}from'./session-drawer-view.js';
const $=id=>document.getElementById(id);const option=(select,value,label)=>select.append(new Option(label,value));
export function initSessionDrawer({workspace,state,getConfig,onPending,onOpenTest,onClear,applyHandedness}){let config=getConfig(),noticeTimer;const preferences=workspace.read('pencil-preferences',{})||{};
 $('modeSelect').replaceChildren();SESSION_CHOICES.forEach(([value,label])=>option($('modeSelect'),value,label));$('partSelect').replaceChildren();option($('partSelect'),'all','Toutes les parties');COURSE_MAP.forEach(part=>option($('partSelect'),part.id,part.label));$('testChapterSelect').replaceChildren();COURSE_MAP.flatMap(p=>p.chapters).forEach(c=>option($('testChapterSelect'),c.id,c.label));
 function chapters(){const value=$('partSelect').value;$('chapterSelect').replaceChildren();option($('chapterSelect'),'all','Tous les chapitres');COURSE_MAP.filter(p=>value==='all'||p.id===value).flatMap(p=>p.chapters).forEach(c=>option($('chapterSelect'),c.id,c.label));notions()}
 function notions(){const part=$('partSelect').value,chapter=$('chapterSelect').value;$('notionSelect').replaceChildren();option($('notionSelect'),'all','Toutes les notions');allNotions().filter(n=>(part==='all'||n.partId===part)&&(chapter==='all'||n.chapterId===chapter)).forEach(n=>option($('notionSelect'),n.id,n.label))}
 function notify(){const n=$('sessionSettingsNotice');n.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.hidden=true,3200)}
 function queue(){const mode=$('modeSelect').value,next=normalizeSessionConfig({...config,mode,partId:$('partSelect').value,chapterId:$('chapterSelect').value,notionId:$('notionSelect').value,questionType:$('questionTypeSelect').value,difficulty:$('difficultySelect').value,plan:[]},state);next.plan=buildSessionPlan(next,state);workspace.write('active-session',next);config=next;render();notify();onPending(next)}
 function render(){const mode=$('modeSelect').value,type=$('questionTypeSelect').value;$('difficultySelect').closest('label').hidden=mode===SESSION_MODES.FREE&&type===QUESTION_TYPES.REFLEX;renderSessionContent({mode,plan:config.plan})}
 chapters();$('modeSelect').value=config.mode;$('partSelect').value=config.partId||'all';chapters();$('chapterSelect').value=config.chapterId||'all';notions();$('notionSelect').value=config.notionId||'all';$('questionTypeSelect').value=config.questionType||QUESTION_TYPES.CALCULATION;if(config.difficulty)$('difficultySelect').value=String(config.difficulty);render();
 $('partSelect').onchange=()=>{chapters();queue()};$('chapterSelect').onchange=()=>{notions();queue()};for(const id of['modeSelect','notionSelect','questionTypeSelect','difficultySelect'])$(id).addEventListener('change',queue);$('startChapterTest').onclick=onOpenTest;
 const savePrefs=()=>{const next={size:$('sizeRange').value,grid:$('gridToggle').checked,straight:$('straightToggle').checked,handedness:document.querySelector('input[name="handedness"]:checked')?.value||'right'};workspace.write('pencil-preferences',next)};
 if(preferences.size)$('sizeRange').value=preferences.size;if(typeof preferences.grid==='boolean')$('gridToggle').checked=preferences.grid;if(typeof preferences.straight==='boolean')$('straightToggle').checked=preferences.straight;if(preferences.handedness){document.querySelector(`input[name="handedness"][value="${preferences.handedness}"]`).checked=true;applyHandedness(preferences.handedness)}$('sizeValue').textContent=$('sizeRange').value;
 ['sizeRange','gridToggle','straightToggle'].forEach(id=>$(id).addEventListener('input',savePrefs));document.querySelectorAll('input[name="handedness"]').forEach(input=>input.addEventListener('change',savePrefs));$('clearButton').onclick=()=>$('clearBoardDialog').showModal();$('cancelClearBoard').onclick=()=>$('clearBoardDialog').close();$('confirmClearBoard').onclick=()=>{onClear();$('clearBoardDialog').close()};
 return{render:()=>{config=getConfig();$('modeSelect').value=config.mode;render()}}}
