import{allNotions,findNotion}from'../course-map.js';
import{dueNotions,weakNotions}from'../scheduler.js';

export const SESSION_MODES=Object.freeze({DAILY:'daily',WEAK:'consolidation',FREE:'free',CHAPTER_TEST:'chapter-test'});
export const QUESTION_TYPES=Object.freeze({FORMULA:'formula',COURSE:'course',CALCULATION:'calculation',REFLEX:'reflex'});
export const DIFFICULTIES=Object.freeze({FUNDAMENTAL:1,STANDARD:2,TRAP:4});
export const RESULT_STATES=Object.freeze({SUCCESS:'success',PARTIAL:'partial',FAILED:'failed',SKIPPED:'skipped'});
export const TYPE_LABELS=Object.freeze({formula:'Formules',course:'Cours',calculation:'Calcul',reflex:'Réflexe'});
export const DIFFICULTY_LABELS=Object.freeze({1:'Fondamental',2:'Standard',4:'Piège'});

const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
const uniq=rows=>[...new Set(rows.filter(Boolean))];
const textOf=q=>[q.kind,q.category,q.questionHtml,q.question?.segments?.map(s=>s.value).join(' '),q.prompt_content?.segments?.map(s=>s.value).join(' ')].filter(Boolean).join(' ');
const hasFormula=q=>/\\frac|\\sqrt|\\sum|\\int|\\(?:ln|exp)|[=≤≥≠×÷^_]|[⁰¹²³⁴⁵⁶⁷⁸⁹]/.test(textOf(q));

export function normalizeQuestionType(question={}){const explicit=question.questionType||question.question_type;if(Object.values(QUESTION_TYPES).includes(explicit))return explicit;if(explicit==='parameterized')return QUESTION_TYPES.CALCULATION;if(Number(question.difficulty)===3)return QUESTION_TYPES.REFLEX;if(/cours|définition|propriété|théorème/i.test(String(question.kind||''))||question.generator==='course-bank')return QUESTION_TYPES.COURSE;if(/formule/i.test(String(question.kind||''))||hasFormula(question))return QUESTION_TYPES.FORMULA;return QUESTION_TYPES.CALCULATION}
export function normalizeDifficulty(value,{questionType}={}){if(questionType===QUESTION_TYPES.REFLEX)return null;if(['fundamental','1',1].includes(value))return DIFFICULTIES.FUNDAMENTAL;if(['standard','2',2,3,'3'].includes(value))return DIFFICULTIES.STANDARD;if(['trap','4',4].includes(value))return DIFFICULTIES.TRAP;return DIFFICULTIES.STANDARD}
export function normalizeQuestion(question={}){const legacyDifficulty=Number(question.difficulty)||2,questionType=normalizeQuestionType(question),difficulty=normalizeDifficulty(question.difficulty,{questionType});return{...question,questionType,difficulty,masteryLevel:questionType===QUESTION_TYPES.REFLEX?clamp(legacyDifficulty,1,4):difficulty,timeLimitSeconds:questionType===QUESTION_TYPES.REFLEX?60:null}}
export function resolveEvaluation({choice,hintUsed=false,timeExceeded=false}={}){if(choice===RESULT_STATES.SKIPPED)return RESULT_STATES.SKIPPED;if(choice==='failed'||choice===RESULT_STATES.FAILED)return RESULT_STATES.FAILED;if(choice==='success'||choice===RESULT_STATES.SUCCESS)return hintUsed||timeExceeded?RESULT_STATES.PARTIAL:RESULT_STATES.SUCCESS;throw new TypeError(`Évaluation inconnue : ${choice}`)}
function latestTestRows(state){const rows=(state.masteryEvents||[]).filter(event=>event.eventType==='test-question-graded'&&event.notionId).sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt));if(!rows.length)return[];const latestTestId=rows.find(row=>row.testId)?.testId;if(latestTestId)return rows.filter(row=>row.testId===latestTestId);const latestAt=Date.parse(rows[0].occurredAt),windowMs=21600000;return rows.filter(row=>latestAt-Date.parse(row.occurredAt)<=windowMs)}
function planItem(notionId,{questionCount=3,priority=null,recommendedDifficulty=2,reason='Révision'}={}){const notion=findNotion(notionId);return{id:`${notionId}:${priority||0}`,notionId,partId:notion?.partId||'all',chapterId:notion?.chapterId||'all',label:notion?.label||notionId,chapterLabel:notion?.chapterLabel||'',questionCount,answered:0,successes:0,partials:0,failures:0,priority,recommendedDifficulty,reason}}
function testPlan(state){const grouped=new Map();for(const event of latestTestRows(state)){const ratio=Number(event.evidence?.scoreRatio);if(!Number.isFinite(ratio))continue;const row=grouped.get(event.notionId)||{sum:0,count:0};row.sum+=ratio;row.count+=1;grouped.set(event.notionId,row)}return[...grouped.entries()].map(([notionId,row])=>({notionId,score:row.sum/row.count})).filter(row=>row.score<1).sort((a,b)=>a.score-b.score).map((row,index)=>planItem(row.notionId,{questionCount:row.score<.5?4:row.score<.8?3:2,priority:index+1,recommendedDifficulty:row.score<.45?1:row.score<.75?2:4,reason:'Dernier test'}))}
function duePlan(state){return dueNotions(state).slice(0,8).map((id,index)=>planItem(id,{questionCount:3,priority:index+1,recommendedDifficulty:state.masteryStates?.[id]?.masteryScore<40?1:2,reason:'Échéance du jour'}))}
function weakPlan(state){return weakNotions(state).slice(0,8).map((id,index)=>{const score=state.masteryStates?.[id]?.masteryScore??0;return planItem(id,{questionCount:score<35?4:3,priority:index+1,recommendedDifficulty:score<35?1:score<65?2:4,reason:'Point faible'})})}
export function buildSessionPlan(config,state){const mode=config?.mode;if(mode===SESSION_MODES.DAILY){const fromTests=testPlan(state);return(fromTests.length?fromTests:duePlan(state)).slice(0,8)}if(mode===SESSION_MODES.WEAK)return weakPlan(state);if(mode===SESSION_MODES.FREE){const notion=findNotion(config.notionId);return[{...planItem(config.notionId,{questionCount:0,recommendedDifficulty:normalizeDifficulty(config.difficulty,{questionType:config.questionType}),reason:'Révision libre'}),partId:config.partId||notion?.partId||'all',chapterId:config.chapterId||notion?.chapterId||'all',questionType:config.questionType||QUESTION_TYPES.CALCULATION}]}return[]}
export function normalizeSessionConfig(config={},state={}){const mode=Object.values(SESSION_MODES).includes(config.mode)?config.mode:SESSION_MODES.DAILY,questionType=Object.values(QUESTION_TYPES).includes(config.questionType)?config.questionType:QUESTION_TYPES.CALCULATION,next={...config,mode,questionType,difficulty:normalizeDifficulty(config.difficulty,{questionType})},plan=Array.isArray(config.plan)&&config.plan.length?config.plan:buildSessionPlan(next,state);return{...next,plan:plan.map(item=>({...item,answered:Number(item.answered)||0,successes:Number(item.successes)||0,partials:Number(item.partials)||0,failures:Number(item.failures)||0}))}}
export function currentPlanItem(config){return(config.plan||[]).find(item=>!item.questionCount||item.answered<item.questionCount)||null}
export function recordPlanResult(config,result){const item=currentPlanItem(config);if(!item)return config;const plan=config.plan.map(row=>row!==item?row:{...row,answered:row.answered+1,successes:row.successes+(result===RESULT_STATES.SUCCESS?1:0),partials:row.partials+(result===RESULT_STATES.PARTIAL?1:0),failures:row.failures+(result===RESULT_STATES.FAILED?1:0)});return{...config,plan}}
export function planNotionIds(config){return uniq((config.plan||[]).map(item=>item.notionId))}
export function isSessionComplete(config){return Boolean(config.plan?.length)&&config.plan.every(item=>item.questionCount>0&&item.answered>=item.questionCount)}
export function difficultyLabel(value){return DIFFICULTY_LABELS[normalizeDifficulty(value)]||'Adaptative'}
export function questionTypeLabel(value){return TYPE_LABELS[value]||'Question'}
export function allSelectableNotions(){return allNotions()}
