const NUMBER_LIST=/[;,\s]+/;
const finite=value=>Number.isFinite(value)?value:null;
export function insertAtSelection(value,start,end,insertion,selectionOffset=null){const source=String(value??''),from=Math.max(0,Number(start)||0),to=Math.max(from,Number(end)||from),next=`${source.slice(0,from)}${insertion}${source.slice(to)}`,cursor=from+(selectionOffset??String(insertion).length);return{value:next,start:cursor,end:cursor}}
export function mathSnippet({display=false,variable='a'}={}){const formula=`\\frac{x}{x+{{${variable}}}}`;return display?`\n\\[${formula}\\]\n`:`\\(${formula}\\)`}
export function parameterizedExample(variable='a'){return{prompt:`Simplifier puis dériver la fonction :\n\n\\[f(x)=\\frac{x}{x+{{${variable}}}}\\]`,hint:`Écrire \\(x=(x+{{${variable}}})-{{${variable}}}\\).`,correction:`Domaine : \\(x\\neq -{{${variable}}}\\).\n\\[f(x)=1-\\frac{ {{${variable}}} }{x+{{${variable}}}}\\]\n\\[f'(x)=\\frac{ {{${variable}}} }{(x+{{${variable}}})^2}\\]`,concept:'Vérifier la valeur interdite avant de simplifier.',oral:'Je transforme le numérateur pour faire apparaître une forme simple à dériver.'}}
export function pedagogicalError(type,difficulty){if(type==='reflex'&&difficulty!=null&&String(difficulty)!=='')return'Le type Réflexe choisit automatiquement la difficulté : retire le niveau imposé.';return''}
export function inferVariableType(variable={}){const mode=variable.sampling?.mode;if(mode==='decimal')return'decimal';if(mode==='finite-set')return'list';if(/\\\s*\{\s*0\s*\}/.test(variable.domain||''))return'nonzero';if(/^(?:N|ℕ)/.test(variable.domain||''))return'natural';return'integer'}
export function variableDraft(variable={},index=0){const type=variable.uiType||inferVariableType(variable),values=(variable.sampling?.values||[]).join('; ');return{name:variable.name||String.fromCharCode(97+index),type,minimum:finite(Number(variable.sampling?.minimum))??(type==='natural'?0:1),maximum:finite(Number(variable.sampling?.maximum))??10,precision:finite(Number(variable.sampling?.precision))??2,excluded:String(variable.excluded||''),values}}
const numbers=value=>String(value||'').split(NUMBER_LIST).map(Number).filter(Number.isFinite);
export function variableSpec(draft={}){const name=String(draft.name||'').trim(),type=draft.type||'integer',minimum=Number(draft.minimum),maximum=Number(draft.maximum),excluded=numbers(draft.excluded),listed=numbers(draft.values);if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(name))throw new TypeError('Le nom d’une variable doit commencer par une lettre.');if(type==='list'){if(!listed.length)throw new TypeError(`Indique au moins une valeur possible pour ${name}.`);return{name,domain:`{${listed.join(';')}}`,sampling:{mode:'finite-set',values:listed}}}if(!Number.isFinite(minimum)||!Number.isFinite(maximum)||minimum>maximum)throw new TypeError(`Les limites de ${name} sont invalides.`);const forbidden=[...(type==='nonzero'?[0]:[]),...excluded];const base=type==='natural'?'N':type==='decimal'?'R':'Z',domain=forbidden.length?`${base} \\ {${[...new Set(forbidden)].join(';')}}`:base;if(type==='decimal')return{name,domain,sampling:{mode:'decimal',minimum,maximum,precision:Math.max(0,Math.min(6,Number(draft.precision)||2))}};return{name,domain,sampling:{mode:'integer',minimum:type==='natural'?Math.max(0,minimum):minimum,maximum}}}
