const gcdInt=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b)[a,b]=[b,a%b];return a||1};
export const rational=(n,d=1)=>{if(!Number.isInteger(n)||!Number.isInteger(d)||!d)throw new TypeError('Rationnel invalide');const g=gcdInt(n,d),s=d<0?-1:1;return{numerator:s*n/g,denominator:Math.abs(d)/g}};
export const valueToLatex=v=>v&&Number.isInteger(v.numerator)?(v.denominator===1?String(v.numerator):`\\frac{${v.numerator}}{${v.denominator}}`):String(v);
const num=v=>v&&Number.isInteger(v.numerator)?v.numerator/v.denominator:v;
const tokenize=s=>{const out=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const m=s.slice(i).match(/^(\d+(?:\.\d+)?|[A-Za-zÀ-ÿ_][\wÀ-ÿ]*|!=|<=|>=|&&|\|\||[!()+\-*/^,=<>])/);if(!m)throw new SyntaxError(`Symbole interdit près de « ${s.slice(i,i+8)} »`);out.push(m[1]);i+=m[1].length}return out};
export function parseExpression(source,allowed=[]){const t=tokenize(source.replace(/\b(et|and)\b/gi,'&&').replace(/\b(ou|or)\b/gi,'||').replace(/\b(non|not)\b/gi,'!'));let p=0;const expr=(min=0)=>{let token=t[p++],left;if(token==='-'||token==='!')left={type:'unary',op:token,value:expr(8)};else if(token==='('){left=expr();if(t[p++]!==')')throw new SyntaxError('Parenthèse fermante attendue')}else if(/^\d/.test(token||''))left={type:'number',value:token};else if(/^[A-Za-zÀ-ÿ_]/.test(token||'')){if(t[p]==='('){p++;const args=[];if(t[p]!==')')do{args.push(expr())}while(t[p++]===',');if(t[p-1]!==')')throw new SyntaxError('Parenthèse attendue');left={type:'call',name:token,args}}else{if(!allowed.includes(token))throw new SyntaxError(`Variable inconnue : ${token}`);left={type:'variable',name:token}}}else throw new SyntaxError('Expression attendue');const prec={"||":1,"&&":2,'=':3,'!=':3,'<':3,'<=':3,'>':3,'>=':3,'+':4,'-':4,'*':5,'/':5,'^':7};while(prec[t[p]]>min){const op=t[p++];left={type:'binary',op,left,right:expr(op==='^'?prec[op]-1:prec[op])}}return left};const ast=expr();if(p<t.length)throw new SyntaxError(`Jeton inattendu : ${t[p]}`);return ast}
const functions={abs:a=>Math.abs(num(a)),gcd:(a,b)=>gcdInt(num(a),num(b)),pgcd:(a,b)=>gcdInt(num(a),num(b)),min:(a,b)=>Math.min(num(a),num(b)),max:(a,b)=>Math.max(num(a),num(b)),even:a=>num(a)%2===0,pair:a=>num(a)%2===0,odd:a=>Math.abs(num(a)%2)===1,impair:a=>Math.abs(num(a)%2)===1,divides:(a,b)=>num(a)!==0&&num(b)%num(a)===0,divise:(a,b)=>num(a)!==0&&num(b)%num(a)===0};
export function evaluate(ast,vars={}){if(ast.type==='number')return ast.value.includes('.')?Number(ast.value):rational(Number(ast.value));if(ast.type==='variable')return vars[ast.name];if(ast.type==='call'){if(!functions[ast.name])throw new SyntaxError(`Fonction interdite : ${ast.name}`);return functions[ast.name](...ast.args.map(a=>evaluate(a,vars)))}if(ast.type==='unary'){const v=evaluate(ast.value,vars);return ast.op==='!'?!v:-num(v)}const a=evaluate(ast.left,vars),b=evaluate(ast.right,vars),x=num(a),y=num(b);return({'+':()=>x+y,'-':()=>x-y,'*':()=>x*y,'/':()=>rational(Number.isInteger(x)?x*a.denominator||x:x,Number.isInteger(y)?y:1),'^':()=>x**y,'=':()=>x===y,'!=':()=>x!==y,'<':()=>x<y,'<=':()=>x<=y,'>':()=>x>y,'>=':()=>x>=y,'&&':()=>Boolean(a&&b),'||':()=>Boolean(a||b)}[ast.op])()}
export function renderTemplate(template,vars){return template.replace(/{{\s*([^{}]+)\s*}}/g,(_,e)=>valueToLatex(evaluate(parseExpression(e,Object.keys(vars)),vars)))}
