import{halfUnits}from'./test-utils.js';
const scoreUnits=(points,max)=>{const u=halfUnits(points);if(u>halfUnits(max))throw new RangeError('Note supérieure au barème');return u};
export function beginGrading(session,{role='self',graderName='',now=Date.now()}={}){if(!['submitted','grading','completed'].includes(session.status))throw new Error('La correction est inaccessible avant la remise');if(!['self','teacher','other'].includes(role))throw new TypeError('Rôle de correction invalide');session.status='grading';session.grading={role,graderName:String(graderName).slice(0,80),mode:'criteria',scores:{},startedAt:now,finalizedAt:null,history:session.grading?.history||[]};return session}
export function gradeDirect(session,instanceId,points){if(session.status!=='grading')throw new Error('Correction figée');const q=session.blueprint.questions.find(x=>x.instanceId===instanceId);if(!q)throw new RangeError('Question inconnue');const units=scoreUnits(points,q.points);session.grading.scores[instanceId]={mode:'direct',points:units/2};return session}
export function gradeCriteria(session,instanceId,values){if(session.status!=='grading')throw new Error('Correction figée');const q=session.blueprint.questions.find(x=>x.instanceId===instanceId);if(!q)throw new RangeError('Question inconnue');const criteria={};let units=0;for(const c of q.rubric.criteria){const u=scoreUnits(values[c.id]??0,c.points);criteria[c.id]=u/2;units+=u}session.grading.scores[instanceId]={mode:'criteria',points:units/2,criteria};return session}
export function gradingTotal(session){return Object.values(session.grading?.scores||{}).reduce((n,s)=>n+halfUnits(s.points),0)/2}
export function finalizeGrading(session,now=Date.now()){if(session.status!=='grading')throw new Error('Correction inactive');const missing=session.blueprint.questions.filter(q=>!session.grading.scores[q.instanceId]);if(missing.length)throw new Error(`${missing.length} question(s) non corrigée(s)`);const points=gradingTotal(session);session.grading.finalizedAt=now;session.status='completed';session.result={points,maxPoints:session.blueprint.scale,percentage:points/session.blueprint.scale*100,equivalent20:session.blueprint.scale===40?points/2:points,completedAt:now};return session}
export function reopenGrading(session,now=Date.now()){if(session.status!=='completed')throw new Error('Résultat non finalisé');session.grading.history.push({points:session.result.points,finalizedAt:session.grading.finalizedAt,reopenedAt:now});session.status='grading';session.grading.finalizedAt=null;return session}
export const formatFrenchPoints=value=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(value);
