import{halfUnits}from'./test-utils.js';
const isBinary=session=>session.blueprint.version===2||session.blueprint.gradingMode==='binary';
const scoreUnits=(points,max)=>{const u=halfUnits(points);if(u>halfUnits(max))throw new RangeError('Note supérieure au barème');return u};
export function beginGrading(session,{role='self',graderName='',now=Date.now()}={}){if(!['submitted','grading','completed'].includes(session.status))throw new Error('La correction est inaccessible avant la remise');if(!['self','teacher','other'].includes(role))throw new TypeError('Rôle de correction invalide');session.status='grading';session.grading={role,graderName:String(graderName).slice(0,80),mode:isBinary(session)?'binary':'criteria',scores:{},startedAt:now,finalizedAt:null,history:session.grading?.history||[],revision:session.grading?.revision||1};return session}
export function gradeBinary(session,instanceId,succeeded){if(session.status!=='grading')throw new Error('Correction figée');if(!isBinary(session))throw new Error('Cette session utilise un ancien barème');if(typeof succeeded!=='boolean')throw new TypeError('Choisissez Réussie ou Ratée');const q=session.blueprint.questions.find(x=>x.instanceId===instanceId);if(!q)throw new RangeError('Question inconnue');session.grading.scores[instanceId]={mode:'binary',succeeded,points:succeeded?1:0};return session}
export function gradeDirect(session,instanceId,points){if(isBinary(session)){if(points!==0&&points!==1)throw new TypeError('Une note binaire vaut uniquement 0 ou 1');return gradeBinary(session,instanceId,points===1)}if(session.status!=='grading')throw new Error('Correction figée');const q=session.blueprint.questions.find(x=>x.instanceId===instanceId);if(!q)throw new RangeError('Question inconnue');const units=scoreUnits(points,q.points);session.grading.scores[instanceId]={mode:'direct',points:units/2};return session}
export function gradeCriteria(session,instanceId,values){if(isBinary(session))throw new Error('Aucun barème intermédiaire en mode binaire');if(session.status!=='grading')throw new Error('Correction figée');const q=session.blueprint.questions.find(x=>x.instanceId===instanceId);if(!q)throw new RangeError('Question inconnue');const criteria={};let units=0;for(const c of q.rubric.criteria){const u=scoreUnits(values[c.id]??0,c.points);criteria[c.id]=u/2;units+=u}session.grading.scores[instanceId]={mode:'criteria',points:units/2,criteria};return session}
export function gradingTotal(session){return Object.values(session.grading?.scores||{}).reduce((n,s)=>n+halfUnits(s.points),0)/2}
export function gradingProgress(session){const corrected=Object.keys(session.grading?.scores||{}).length,total=session.blueprint.questions.length;return{corrected,total,complete:corrected===total}}
export function finalizeGrading(session,now=Date.now()){if(session.status!=='grading')throw new Error('Correction inactive');const {corrected,total,complete}=gradingProgress(session);if(!complete)throw new Error(`${total-corrected} question(s) non corrigée(s)`);const points=gradingTotal(session),maxPoints=session.blueprint.scale;session.grading.finalizedAt=now;session.status='completed';session.result={points,maxPoints,successes:isBinary(session)?points:null,failures:isBinary(session)?maxPoints-points:null,percentage:points/maxPoints*100,equivalent20:maxPoints===40?points/2:points,completedAt:now,gradingMode:isBinary(session)?'binary':'legacy'};return session}
export function reopenGrading(session,now=Date.now()){if(session.status!=='completed')throw new Error('Résultat non finalisé');for(const q of session.blueprint.questions){const score=session.grading.scores[q.instanceId];if(score)session.grading.history.push({questionInstanceId:q.instanceId,eventId:`test:${session.id}:${q.instanceId}:v${session.grading.revision||1}`,points:score.points,finalizedAt:session.grading.finalizedAt,reopenedAt:now})}session.grading.revision=(session.grading.revision||1)+1;session.status='grading';session.grading.finalizedAt=null;return session}
export const formatFrenchPoints=value=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(value);
