import{clone}from'./test-utils.js';import{validateBlueprint}from'./test-validator.js';
const STATUSES=['unvisited','visited','started','review','completed'];
export function createTestSession(blueprint,{now=Date.now()}={}){const validation=validateBlueprint(blueprint);if(!validation.valid)throw new TypeError(validation.errors.join(', '));const deadlineAt=blueprint.settings.durationMinutes?now+blueprint.settings.durationMinutes*60000:null;return{id:blueprint.id,version:1,blueprint:clone(blueprint),status:'in-progress',currentIndex:0,questionStates:Object.fromEntries(blueprint.questions.map((q,i)=>[q.instanceId,{status:i?'unvisited':'visited',draft:null,updatedAt:now}])),createdAt:now,startedAt:now,deadlineAt,submittedAt:null,elapsedMs:0,grading:null,result:null,updatedAt:now}}
function editable(s){if(s.status!=='in-progress')throw new Error('La copie est figée')}
export function navigate(session,index,{draft,now=Date.now()}={}){editable(session);if(!Number.isInteger(index)||index<0||index>=session.blueprint.questions.length)throw new RangeError('Question inaccessible');const old=session.blueprint.questions[session.currentIndex].instanceId;if(draft!==undefined)session.questionStates[old]={...session.questionStates[old],draft:clone(draft),status:draft?.strokes?.length?'started':session.questionStates[old].status,updatedAt:now};const next=session.blueprint.questions[index].instanceId;if(session.questionStates[next].status==='unvisited')session.questionStates[next].status='visited';session.currentIndex=index;session.updatedAt=now;return session}
export function setQuestionStatus(session,instanceId,status,now=Date.now()){editable(session);if(!STATUSES.includes(status))throw new TypeError('Statut de question invalide');if(!session.questionStates[instanceId])throw new RangeError('Question inconnue');session.questionStates[instanceId].status=status;session.questionStates[instanceId].updatedAt=now;session.updatedAt=now;return session}
export function remainingMs(session,now=Date.now()){return session.deadlineAt===null?null:Math.max(0,session.deadlineAt-now)}
export function submissionSummary(session,now=Date.now()){const values=Object.values(session.questionStates);return{questions:values.length,unvisited:values.filter(x=>x.status==='unvisited').length,started:values.filter(x=>x.status==='started').length,review:values.filter(x=>x.status==='review').length,remainingMs:remainingMs(session,now),maxPoints:session.blueprint.scale}}
export function submitTest(session,{now=Date.now(),expired=false}={}){editable(session);session.status='submitted';session.submittedAt=now;session.elapsedMs=Math.min(now-session.startedAt,session.deadlineAt?session.deadlineAt-session.startedAt:Infinity);session.expired=expired;session.updatedAt=now;return session}
export function abandonTest(session,now=Date.now()){editable(session);session.status='abandoned';session.abandonedAt=now;session.updatedAt=now;return session}
export function shouldExpire(session,now=Date.now()){return session.status==='in-progress'&&session.deadlineAt!==null&&now>=session.deadlineAt}
