import{createClient, type SupabaseClient}from'npm:@supabase/supabase-js@2';
import{AdminError,errorResponse}from'../_shared/admin-errors.ts';
import{corsHeaders}from'../_shared/cors.ts';
import{displayName,email,role,userId}from'../_shared/admin-validation.ts';

const ACTIONS=new Set(['list-users','invite-user','set-role','suspend-user','reactivate-user','list-audit']);
const MAX_BODY=16_384, PAGE_SIZE=50, SUSPEND_DURATION='876000h';
type Dependencies={userClient:SupabaseClient;adminClient:SupabaseClient;appBaseUrl:string;now?:()=>Date;inviteLimit?:number;inviteWindowMinutes?:number};
const ok=(data:unknown,headers:HeadersInit={})=>new Response(JSON.stringify({ok:true,data}),{headers:{...headers,'content-type':'application/json; charset=utf-8'}});
const suspended=(user:any)=>Boolean(user.banned_until&&new Date(user.banned_until)>new Date());
const cleanUser=(user:any,profile:any={})=>{const isSuspended=suspended(user);const pending=!user.email_confirmed_at;return{id:user.id,email:user.email||'',displayName:profile.display_name||'',role:profile.role||'user',createdAt:user.created_at,emailConfirmedAt:user.email_confirmed_at||null,lastSignInAt:user.last_sign_in_at||null,invitedAt:user.invited_at||user.confirmation_sent_at||null,suspended:isSuspended,suspendedUntil:isSuspended?user.banned_until:null,status:isSuspended?'suspended':pending?'invitation-pending':'active',protected:profile.role==='owner'}};
async function audit(admin:SupabaseClient,row:Record<string,unknown>){await admin.from('team_admin_audit').insert(row)}
async function profile(admin:SupabaseClient,id:string){const{data,error}=await admin.from('profiles').select('id,display_name,role,created_at').eq('id',id).single();if(error||!data)throw new AdminError('USER_NOT_FOUND',404);return data}

export async function dispatch(action:string,payload:any,actorId:string,deps:Dependencies){const admin=deps.adminClient;
 if(action==='list-users'){const users:any[]=[];for(let page=1;;page++){const{data,error}=await admin.auth.admin.listUsers({page,perPage:PAGE_SIZE});if(error)throw new AdminError('SERVICE_UNAVAILABLE',503);users.push(...data.users);if(data.users.length<PAGE_SIZE)break}const profiles:any[]=[];for(let i=0;i<users.length;i+=100){const{data,error}=await admin.from('profiles').select('id,display_name,role,created_at').in('id',users.slice(i,i+100).map(x=>x.id));if(error)throw new AdminError('SERVICE_UNAVAILABLE',503);profiles.push(...(data||[]))}const map=new Map(profiles.map(x=>[x.id,x]));const rank:any={'invitation-pending':0,active:2,suspended:3};const roleRank:any={admin:0,owner:1,user:2};const result=users.map(x=>cleanUser(x,map.get(x.id))).sort((a,b)=>rank[a.status]-rank[b.status]||(a.status==='active'?roleRank[a.role]-roleRank[b.role]:0)||a.email.localeCompare(b.email));return{users:result}}
 if(action==='list-audit'){const page=Math.max(1,Number(payload?.page)||1),perPage=Math.min(50,Math.max(1,Number(payload?.perPage)||20));const{data,error,count}=await admin.from('team_admin_audit').select('id,actor_id,target_user_id,target_email,action,previous_role,new_role,success,error_code,metadata,created_at',{count:'exact'}).order('created_at',{ascending:false}).range((page-1)*perPage,page*perPage-1);if(error)throw new AdminError('SERVICE_UNAVAILABLE',503);return{entries:data||[],page,total:count||0}}
 if(action==='invite-user'){const normalized=email(payload?.email),name=displayName(payload?.displayName),newRole=role(payload?.role);const limit=deps.inviteLimit??Number(Deno.env.get('INVITE_RATE_LIMIT')||5),window=deps.inviteWindowMinutes??Number(Deno.env.get('INVITE_RATE_WINDOW_MINUTES')||10);const since=new Date((deps.now?.()||new Date()).getTime()-window*60_000).toISOString();const{count}=await admin.from('team_admin_audit').select('id',{count:'exact',head:true}).eq('actor_id',actorId).eq('action','invite-user').gte('created_at',since);if((count||0)>=limit)throw new AdminError('RATE_LIMITED',429);let invited:any;const redirectTo=new URL('accept-invite.html',deps.appBaseUrl).href;const invite=await admin.auth.admin.inviteUserByEmail(normalized,{redirectTo,data:{display_name:name}});if(invite.error){const code=/already|registered|exists/i.test(invite.error.message)?'USER_ALREADY_EXISTS':'INVITATION_FAILED';await audit(admin,{actor_id:actorId,target_email:normalized,action:'invite-user',success:false,error_code:code,metadata:{stage:'invitation'}});throw new AdminError(code,code==='USER_ALREADY_EXISTS'?409:502)}invited=invite.data.user;const targetId=invited?.id;if(!targetId)throw new AdminError('INVITATION_FAILED',502);const current=await profile(admin,targetId);const update=await admin.from('profiles').update({role:newRole,display_name:name||current.display_name}).eq('id',targetId).eq('role','user').select('id,display_name,role,created_at').single();if(update.error||!update.data){await admin.from('profiles').update({role:'user'}).eq('id',targetId);await audit(admin,{actor_id:actorId,target_user_id:targetId,target_email:normalized,action:'invite-user',success:false,error_code:'ROLE_UPDATE_FAILED',metadata:{stage:'profile'}});throw new AdminError('ROLE_UPDATE_FAILED',502)}await audit(admin,{actor_id:actorId,target_user_id:targetId,target_email:normalized,action:'invite-user',new_role:newRole,success:true,metadata:{}});return{user:cleanUser(invited,update.data)}}
 const targetId=userId(payload?.userId),target=await profile(admin,targetId);if(target.role==='owner'||targetId===actorId)throw new AdminError('OWNER_PROTECTED',403);
 if(action==='set-role'){const next=role(payload?.role),expected=role(payload?.expectedRole);if(target.role!==expected)throw new AdminError('ROLE_CONFLICT',409);if(next===expected)return{profile:target,unchanged:true};const{data,error}=await admin.from('profiles').update({role:next}).eq('id',targetId).eq('role',expected).select('id,display_name,role,created_at').maybeSingle();if(error)throw new AdminError('ROLE_UPDATE_FAILED',502);if(!data)throw new AdminError('ROLE_CONFLICT',409);await audit(admin,{actor_id:actorId,target_user_id:targetId,action:'set-role',previous_role:expected,new_role:next,success:true,metadata:{}});return{profile:data}}
 const authUser=await admin.auth.admin.getUserById(targetId);if(authUser.error||!authUser.data.user)throw new AdminError('USER_NOT_FOUND',404);const wasSuspended=suspended(authUser.data.user),wantsSuspend=action==='suspend-user';if(wasSuspended===wantsSuspend)return{user:cleanUser(authUser.data.user,target),unchanged:true};const changed=await admin.auth.admin.updateUserById(targetId,{ban_duration:wantsSuspend?SUSPEND_DURATION:'none'});if(changed.error)throw new AdminError('SUSPENSION_FAILED',502);const verified=await admin.auth.admin.getUserById(targetId);if(verified.error||!verified.data.user||suspended(verified.data.user)!==wantsSuspend)throw new AdminError('SUSPENSION_FAILED',502);await audit(admin,{actor_id:actorId,target_user_id:targetId,action:wantsSuspend?'suspend-user':'reactivate-user',success:true,metadata:{}});return{user:cleanUser(verified.data.user,target)}}

export async function handle(req:Request,create=createClient){let cors:HeadersInit={};try{cors=corsHeaders(req);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST'||!(req.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))throw new AdminError('INVALID_REQUEST',400);const length=Number(req.headers.get('content-length')||0);if(length>MAX_BODY)throw new AdminError('INVALID_REQUEST',413);const raw=await req.text();if(raw.length>MAX_BODY)throw new AdminError('INVALID_REQUEST',413);let body:any;try{body=JSON.parse(raw)}catch{throw new AdminError('INVALID_REQUEST')}if(!body||!ACTIONS.has(body.action)||body.payload&&typeof body.payload!=='object')throw new AdminError('INVALID_REQUEST');const authorization=req.headers.get('authorization')||'';const token=authorization.match(/^Bearer\s+(.+)$/i)?.[1];if(!token)throw new AdminError('UNAUTHENTICATED',401);const url=Deno.env.get('SUPABASE_URL'),publishable=Deno.env.get('SUPABASE_ANON_KEY'),secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),appBaseUrl=Deno.env.get('APP_BASE_URL');if(!url||!publishable||!secret||!appBaseUrl)throw new AdminError('SERVICE_UNAVAILABLE',503);const userClient=create(url,publishable,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const verified=await userClient.auth.getUser(token);if(verified.error||!verified.data.user)throw new AdminError('UNAUTHENTICATED',401);const actorId=verified.data.user.id;const actor=await userClient.from('profiles').select('role').eq('id',actorId).single();if(actor.error||actor.data?.role!=='owner')throw new AdminError('FORBIDDEN',403);const adminClient=create(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});return ok(await dispatch(body.action,body.payload||{},actorId,{userClient,adminClient,appBaseUrl}),cors)}catch(error){return errorResponse(error,cors)}}

if(import.meta.main)Deno.serve(handle);
