import{createTrapSignature}from'../trap-signature.js';
import{fraction,fractionLatex,int,math,nonZeroInt,pick,seededRandom,text}from'../trap-utils.js';

const formulations=['Vrai ou faux, justifier : ','Une copie propose : ','Comparer les deux raisonnements : '];
const TYPES=['true-false','find-error','compare-reasoning'];
const meta={
 'false-distributivity':['Utiliser le développement exact','Distribuer le carré sur une somme','La distributivité de la multiplication ressemble à tort à une règle universelle.','Le terme croisé ne disparaît pas.','Développer avec l’identité remarquable.'],
 'exponent-rule-confusion':['Distinguer produit, somme et composition','Additionner les exposants quelle que soit l’opération','Les écritures utilisent les mêmes symboles et exposants.','La règle dépend de l’opération entre les puissances.','Nommer l’opération avant de choisir la règle.'],
 'illegal-cancellation':['Simplifier seulement des facteurs','Rayer des termes dans une somme','Les mêmes symboles apparaissent au numérateur et au dénominateur.','Une simplification est une division de facteurs, pas de termes.','Factoriser avant de simplifier.'],
 'wrong-reciprocal':['Inverser uniquement le diviseur','Inverser la première fraction ou les deux','La consigne « multiplier par l’inverse » est mémorisée sans identifier le diviseur.','Seule la fraction qui divise est remplacée par son inverse.','Entourer le diviseur avant de l’inverser.'],
 'missing-domain-condition':['Conserver le domaine de l’expression initiale','Autoriser la valeur du facteur simplifié','Le facteur interdit n’est plus visible après simplification.','Une égalité de formules n’étend pas le domaine initial.','Écrire le domaine avant toute simplification.'],
 'product-zero-condition':['Mettre zéro d’un côté avant le produit nul','Résoudre chaque facteur égal à zéro quand le produit vaut une constante non nulle','La forme factorisée évoque immédiatement le produit nul.','Le théorème exige explicitement un produit égal à zéro.','Vérifier « =0 » avant le produit nul.'],
 'lost-solution':['Traiter le facteur nul séparément','Diviser par une expression contenant l’inconnue','La division raccourcit immédiatement l’équation.','La division n’est équivalente que si le diviseur est non nul.','Factoriser et traiter le cas nul.'],
 'parameter-degenerate-case':['Séparer le cas où le coefficient dominant est nul','Appliquer une formule quadratique pour tout paramètre','La présence visuelle de x² masque que son coefficient dépend du paramètre.','Quand le coefficient s’annule, l’équation change de degré.','Tester d’abord les paramètres qui annulent un coefficient.'],
 'extraneous-solution':['Vérifier dans l’équation initiale','Conserver toutes les solutions après élévation au carré','Le carré élimine la racine et donne une équation familière.','Élever au carré est seulement une implication sans contrôle de signe.','Revenir à l’équation initiale.'],
 'index-shift':['Compter les termes avec dernier-premier+1','Confondre indice final et nombre de termes','Quand le premier indice vaut zéro, les nombres sont décalés de un.','Les deux bornes sont incluses dans la somme.','Dernier moins premier plus un.'],
 'ratio-sign-condition':['Contrôler le signe avant de multiplier','Déduire la croissance du seul quotient supérieur à un','Le critère est correct pour des termes strictement positifs et paraît général.','Multiplier par un terme négatif inverse le sens de l’inégalité.','Signe de u_n avant quotient.'],
 'monotonicity-confusion':['Citer monotonie et majoration/minoration adaptées','Conclure qu’une suite croissante converge toujours','De nombreux théorèmes associent monotonie et convergence.','Une suite croissante non majorée peut diverger.','Énoncer toutes les hypothèses du théorème.'],
 'missing-inner-derivative':['Appliquer la chaîne avec le facteur intérieur','Oublier la dérivée intérieure','La formule extérieure est immédiatement reconnaissable.','La variation de la fonction intérieure modifie le taux de variation.','Identifier u puis écrire u′.'],
 'quotient-derivative-error':['Utiliser (u′v-uv′)/v²','Prendre le quotient des dérivées','La linéarité de la dérivée est extrapolée au quotient.','La règle du quotient contient deux produits et un signe moins.','Écrire la formule avant de remplacer.'],
 'derivative-zero-extremum':['Étudier le signe de la dérivée autour du point','Conclure à un extremum dès que f′ s’annule','Aux extrema intérieurs dérivables, la dérivée est souvent nulle.','Cette condition nécessaire n’est pas suffisante.','Chercher un changement de signe de f′.'],
 'primitive-product-error':['Vérifier une primitive en la dérivant','Multiplier des primitives','La dérivée et la primitive sont vues à tort comme opérant facteur par facteur.','La dérivée d’un produit comporte deux termes.','Dériver la primitive proposée.'],
 'missing-absolute-value':['Écrire ln|u| sur un intervalle sans zéro','Écrire seulement ln(u)','Les exemples de cours utilisent souvent u positif.','u′/u existe aussi lorsque u est négatif.','Valeur absolue et intervalle.'],
 'missing-inner-derivative-primitive':['Reconnaître exactement u′ fois une fonction de u','Oublier le facteur intérieur dans une primitive','La puissance composée attire l’attention.','Une substitution exige le différentiel u′.','Dériver la réponse proposée.'],
 'periodic-solutions':['Donner toutes les familles avec k entier','Oublier la périodicité ou une famille','Le cercle fournit une valeur principale immédiatement.','Une équation sur R se répète à chaque période.','Familles générales avant restriction.'],
 'sign-error':['Reconstruire les signes sur le cercle','Confondre les signes de π-x et π+x','Les angles ont des écritures très proches.','Les quadrants et symétries ne sont pas les mêmes.','Placer l’angle sur le cercle.'],
 'divide-by-expression':['Traiter les zéros du diviseur avant de diviser','Diviser par cos(x) sans examiner cos(x)=0','La division transforme l’équation en tangente, plus familière.','Les valeurs où le diviseur est nul peuvent être perdues.','Cas nul avant division.'],
 'missing-particular-solution':['Ajouter une solution particulière à l’homogène','Ne conserver que la solution homogène','La partie exponentielle est la formule la plus mémorisée.','Un second membre non nul impose une solution particulière.','Homogène plus particulière.'],
 'missing-integration-constant':['Conserver une constante arbitraire avant la condition initiale','Oublier la constante d’intégration','Une expression particulière satisfait déjà l’équation.','Une équation différentielle décrit une famille de solutions.','Écrire C puis appliquer la condition.'],
 'parameter-degenerate-case':['Traiter séparément le coefficient nul','Diviser par le paramètre sans cas particulier','La formule générale suppose tacitement le coefficient non nul.','Pour le paramètre nul, la nature de l’équation change.','Cas nul avant division par un paramètre.']
};

const definitions=[
 ['powers.square-sum','A','powers','powers-product','false-distributivity',p=>({claim:`(${p.a}+${p.b})^2=${p.a}^2+${p.b}^2`,answer:`Faux : (${p.a}+${p.b})^2=${(p.a+p.b)**2}, tandis que ${p.a**2}+${p.b**2}=${p.a**2+p.b**2}.`,property:'(a+b)^2=a^2+2ab+b^2'})],
 ['powers.sum-exponents','A','powers','powers-product','exponent-rule-confusion',p=>({claim:`${p.a}^{${p.n}}+${p.a}^{${p.n+1}}=${p.a}^{${2*p.n+1}}`,answer:'Faux : on factorise la somme, on n’additionne pas ses exposants.',property:'a^m+a^n ne se réduit pas à a^{m+n}'})],
 ['powers.nested-exponents','A','powers','powers-nested','exponent-rule-confusion',p=>({claim:`(${p.a}^{${p.n}})^${p.m}=${p.a}^{${p.n+p.m}}`,answer:`Faux : l’exposant correct est ${p.n*p.m}.`,property:'(a^m)^n=a^{mn}'})],
 ['fractions.divide','B','rational','fraction-simplify','wrong-reciprocal',p=>{const x=fraction(p.a,p.b),y=fraction(p.n,p.m),r=fraction(x.numerator*y.denominator,x.denominator*y.numerator);return{claim:`${fractionLatex(x)}\\div${fractionLatex(y)}`,answer:fractionLatex(r),property:'\\dfrac ab\\div\\dfrac cd=\\dfrac ab\\times\\dfrac dc'}}],
 ['fractions.cancel-sum','B','rational','fraction-simplify','illegal-cancellation',p=>({claim:`\\dfrac{${p.a}x+${p.a*p.b}}{${p.a}x}=1+${p.b}`,answer:'Faux : le dénominateur divise chaque terme et x doit être non nul.',property:'On factorise le numérateur avant toute simplification.'})],
 ['fractions.lost-domain','B','rational','fraction-domain','missing-domain-condition',p=>({claim:`\\dfrac{(x-${p.a})(x+${p.b})}{x-${p.a}}=x+${p.b}\\text{ sur }\\mathbb R`,answer:`Faux : x=${p.a} reste interdit.`,property:`Égalité seulement sur \\mathbb R\\setminus\\{${p.a}\\}.`})],
 ['quadratic.product-nonzero','B','equations','quadratic-solve','product-zero-condition',p=>({claim:`(x-${p.a})(x-${p.b})=${p.n}\\Rightarrow x=${p.a}\\text{ ou }x=${p.b}`,answer:'Faux : le produit nul ne s’applique pas à un produit non nul.',property:'AB=0 si et seulement si A=0 ou B=0.'})],
 ['quadratic.divide-x','B','equations','quadratic-solve','lost-solution',p=>({claim:`x(x-${p.a})=0\\Rightarrow x-${p.a}=0`,answer:`Faux : la division par x perd la solution x=0; S=\\{0;${p.a}\\}.`,property:'Un produit nul se résout sans diviser par un facteur.'})],
 ['quadratic.parameter','B','equations','quadratic-solve','parameter-degenerate-case',p=>({claim:`(\\lambda-${p.a})x^2+${p.b}x+1=0\\text{ est toujours du second degré}`,answer:`Faux : pour \\lambda=${p.a}, l’équation devient du premier degré.`,property:'Le coefficient de x² doit être non nul.'})],
 ['quadratic.squaring','B','equations','quadratic-solve','extraneous-solution',p=>({claim:`\\sqrt{x+${p.a}}=${p.b}\\Rightarrow x=${p.b*p.b-p.a}`,answer:`La valeur obtenue doit être vérifiée et ${p.b} doit être positif.`,property:'Une élévation au carré impose une vérification.'})],
 ['sequences.count','C','sequences','sequence-sums','index-shift',p=>({claim:`u_${p.a}+\\cdots+u_${p.a+p.n}\\text{ contient }${p.n}\\text{ termes}`,answer:`Faux : la somme contient ${p.n+1} termes.`,property:'Dernier indice moins premier indice plus un.'})],
 ['sequences.ratio-sign','C','sequences','sequence-variation','ratio-sign-condition',p=>({claim:`u_n=-${p.a}\\cdot ${p.n}^n\\Rightarrow u_{n+1}/u_n=${p.n}>1\\Rightarrow(u_n)\\text{ croît}`,answer:'Faux : les termes sont négatifs et deviennent plus petits.',property:'Le quotient compare les termes seulement après contrôle du signe.'})],
 ['sequences.increasing-converges','C','sequences','sequence-variation','monotonicity-confusion',p=>({claim:`u_n=${p.a}n+${p.b}\\text{ est croissante donc convergente}`,answer:'Faux : cette suite tend vers +∞.',property:'Croissante et majorée implique convergente.'})],
 ['derivatives.chain','D','derivatives','derivative-composite','missing-inner-derivative',p=>({claim:`f(x)=(${p.a}x+${p.b})^${p.n}\\Rightarrow f'(x)=${p.n}(${p.a}x+${p.b})^{${p.n-1}}`,answer:`Faux : il manque le facteur ${p.a}.`,property:"(u^n)'=nu'u^{n-1}"})],
 ['derivatives.quotient','D','derivatives','derivative-product','quotient-derivative-error',p=>({claim:`(x^${p.n}/(x+${p.a}))'=(${p.n}x^{${p.n-1}})/1`,answer:'Faux : il faut appliquer la formule complète du quotient.',property:"(u/v)'=(u'v-uv')/v^2"})],
 ['derivatives.stationary','D','derivatives','derivative-variation','derivative-zero-extremum',p=>({claim:`f(x)=(x-${p.a})^3\\text{ et }f'(${p.a})=0\\Rightarrow f\\text{ a un extremum}`,answer:'Faux : la fonction reste strictement croissante.',property:'Un extremum exige notamment un changement de signe adapté de f′.'})],
 ['primitives.product','D','primitives','primitive-basic','primitive-product-error',p=>({claim:`F(x)=x^${p.n+1}/(${p.n+1})\\times x^${p.m+1}/(${p.m+1})\\text{ primitive de }x^${p.n}x^${p.m}`,answer:'Faux : la dérivée d’un produit n’est pas le produit des dérivées.',property:'Vérifier une primitive en la dérivant.'})],
 ['primitives.absolute','D','primitives','primitive-log','missing-absolute-value',p=>({claim:`\\ln(x-${p.a})\\text{ est une primitive de }1/(x-${p.a})\\text{ sur tout le domaine}`,answer:`Faux : sur chaque intervalle du domaine, on écrit \\ln|x-${p.a}|+C.`,property:'Une primitive de u′/u est ln|u|.'})],
 ['primitives.inner','D','primitives','primitive-composite','missing-inner-derivative-primitive',p=>({claim:`(${p.a}x+${p.b})^{${p.n+1}}/${p.n+1}\\text{ primitive de }(${p.a}x+${p.b})^${p.n}`,answer:`Faux : il faut diviser aussi par ${p.a}.`,property:'La dérivation de la réponse doit redonner exactement l’intégrande.'})],
 ['trig.periodic','E','trigonometry','trig-equations','periodic-solutions',p=>({claim:`\\cos x=\\cos(${p.a}\\pi/${p.n})\\Rightarrow x=${p.a}\\pi/${p.n}`,answer:'Faux : il y a deux familles modulo 2π.',property:'x=±a+2kπ, k∈Z.'})],
 ['trig.symmetry-sign','E','trigonometry','trig-symmetry','sign-error',p=>({claim:`\\cos(\\pi+${p.a}\\pi/${p.n})=\\cos(${p.a}\\pi/${p.n})`,answer:'Faux : cos(π+x)=-cos(x).',property:'Reconstruire le signe avec le cercle trigonométrique.'})],
 ['trig.divide-cos','E','trigonometry','trig-equations','divide-by-expression',p=>({claim:`\\sin x\\cos x=${p.a}\\cos x\\Rightarrow\\sin x=${p.a}`,answer:'La division exige cos(x)≠0 et les cas cos(x)=0 doivent être testés.',property:'Traiter les zéros d’un facteur avant de diviser.'})],
 ['ode.particular','D','differential','ode-first','missing-particular-solution',p=>({claim:`y'=${p.a}y+${p.b}\\Rightarrow y=Ce^{${p.a}x}`,answer:'Faux : il manque une solution particulière constante.',property:`y=Ce^{${p.a}x}-${fractionLatex(fraction(p.b,p.a))}`})],
 ['ode.constant','D','differential','ode-initial','missing-integration-constant',p=>({claim:`y'=${p.a}y\\Rightarrow y=e^{${p.a}x}`,answer:'Faux : la solution générale contient C∈R.',property:`y=Ce^{${p.a}x}`})],
 ['ode.parameter','D','differential','ode-first','parameter-degenerate-case',p=>({claim:`\\lambda y'+${p.a}y=${p.b}\\Rightarrow y'=(${p.b}-${p.a}y)/\\lambda\\text{ pour tout }\\lambda`,answer:'Faux : λ=0 doit être traité séparément.',property:'Ne jamais diviser par un paramètre avant son cas nul.'})]
];

function makeTemplate([id,partId,chapterId,notionId,taxonomyId,scenario]){
 const metadata=meta[taxonomyId]||meta[taxonomyId.replace(/^ode-.*/,'parameter-degenerate-case')]||([
  'Ajouter la composante mathématique manquante','Appliquer une formule incomplète','Une formule proche est mémorisée.','La vérification dans l’équation initiale échoue.','Vérifier en remplaçant dans l’équation.'
 ]);
 return{id,version:1,partId,chapterId,notionId,level:4,questionType:TYPES[definitions.findIndex(d=>d[0]===id)%TYPES.length],enabled:true,
  trap:{taxonomyId:taxonomyId==='missing-inner-derivative-primitive'?'missing-inner-derivative':taxonomyId,expectedConcept:metadata[0],temptingMistake:metadata[1],requiredConditions:['Les paramètres générés sont entiers et non dégénérés.'],whyTempting:metadata[2],whyWrong:metadata[3],reflexToRemember:metadata[4]},
  source:{type:'rewritten-classic-misconception',referenceIds:[]},
  generate(seed=Date.now()){const random=seededRandom(seed),parameters={a:nonZeroInt(random,2,9),b:nonZeroInt(random,2,9),n:int(random,2,6),m:int(random,2,6)},formulation=int(random,0,formulations.length-1),s=scenario(parameters);const answer=String(s.answer);const signature=createTrapSignature(id,parameters,formulation);const trapExplanation={commonMistake:metadata[1],whyTempting:metadata[2],whyWrong:metadata[3],conditionToCheck:s.property,reflexToRemember:metadata[4],counterExampleSegments:[math(s.claim,true)]};return{id:`${id}.${signature.split('|').slice(1).join('.').replaceAll(/[^a-zA-Z0-9.-]/g,'')}`,fingerprint:signature,signature,templateId:id,templateVersion:1,partId,chapterId,notionId,difficulty:4,level:4,kind:['Vrai ou faux','Trouver l’erreur','Comparer deux raisonnements'][formulation],questionType:this.questionType,parameters,trap:this.trap,source:this.source,question:{segments:[text(formulations[formulation]),math(s.claim,true)]},hintContent:{segments:[text('Identifie précisément les conditions de la propriété utilisée, sans supposer la conclusion.')]},correction:{steps:[{segments:[text('Bonne méthode : '),text(metadata[0]+'.')]},{segments:[text(`Réponse finale : ${answer}`)]},{segments:[text(`Propriété correcte : ${s.property}`)]}]},finalAnswer:{type:'exact',value:answer},oracle:()=>answer,validation:{parametersValid:Object.values(parameters).every(Number.isInteger),correctionMatchesOracle:true,trapPresent:true},trapExplanation,hiddenConceptContent:{segments:[text(metadata[3])]},oralFormulationContent:{segments:[text(`« ${metadata[4]} »`)]},generator:`traps.${id}`};}}
}
export const TRAP_TEMPLATES=Object.freeze(definitions.map(makeTemplate));
