import{COURSE_MAP,allNotions,findNotion}from'./course-map.js';
import{QuizEngine}from'./quiz-engine.js';
import{DrawingBoard}from'./board.js';
import{loadState,saveState,exportState,importState}from'./storage.js';
import{RESULT,updateProgress,dueNotions,weakNotions}from'./scheduler.js';
import{readHandedness,writeHandedness,setDrawerState,setQuestionCollapsed,setToolState}from'./ui-state.js';
import{renderSegments,renderSteps}from'./math/render-math.js';
import{levelLabel}from'./pedagogy/level-policy.js';
import{TestApp}from'./tests/ui/test-app.js';
import{createTestEvents}from'./mastery/mastery-event.js';import{rebuildMastery}from'./mastery/mastery-engine.js';
import{initSyncUI}from'./sync/ui.js';

const $=id=>document.getElementById(id);
let state=loadState(),current=null,hintUsed=false,correctionSeen=false,sessionAnswered=0,questionNumber=0;
const engine=new QuizEngine();
const board=new DrawingBoard({canvas:$('board'),wrap:$('boardWrap'),hint:$('boardHint'),tool:$('toolSelect'),size:$('sizeRange'),grid:$('gridToggle'),straightToggle:$('straightToggle'),scribbleToggle:$('scribbleToggle'),onPlacementChange:updateShapePlacement});
const testApp=new TestApp({root:$('testApp'),board,onFinalized:session=>{const events=createTestEvents(session,{deviceId:state.deviceId}),ids=new Set((state.masteryEvents||[]).map(e=>e.id));state=saveState({...state,masteryEvents:[...(state.masteryEvents||[]),...events.filter(e=>!ids.has(e.id))]});state=saveState({...state,masteryStates:rebuildMastery(state.masteryEvents,allNotions().map(n=>n.id))});updateStats();}});

function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o)}
function initCourseSelectors(){option($('partSelect'),'all','Toutes les parties');for(const p of COURSE_MAP)option($('partSelect'),p.id,p.label);refreshChapters();$('partSelect').addEventListener('change',refreshChapters);$('chapterSelect').addEventListener('change',refreshNotions)}
function refreshChapters(){const part=$('partSelect').value;$('chapterSelect').innerHTML='';option($('chapterSelect'),'all','Tous les chapitres');for(const p of COURSE_MAP.filter(p=>part==='all'||p.id===part))for(const c of p.chapters)option($('chapterSelect'),c.id,c.label);refreshNotions()}
function refreshNotions(){const part=$('partSelect').value,chapter=$('chapterSelect').value;$('notionSelect').innerHTML='';option($('notionSelect'),'all','Toutes les notions');for(const n of allNotions().filter(n=>(part==='all'||n.partId===part)&&(chapter==='all'||n.chapterId===chapter)))option($('notionSelect'),n.id,n.label)}
function filters(){let notionId=$('notionSelect').value,chapterId=$('chapterSelect').value,partId=$('partSelect').value;const mode=$('modeSelect').value;if(mode==='daily'){const due=dueNotions(state);if(due.length){notionId=due[0];const n=findNotion(notionId);chapterId=n.chapterId;partId=n.partId}}else if(mode==='weak'){const weak=weakNotions(state);if(weak.length){notionId=weak[0];const n=findNotion(notionId);chapterId=n.chapterId;partId=n.partId}}return{mode,partId,chapterId,notionId,difficulty:$('difficultySelect').value}}
function newQuestion(){current=engine.generate(filters(),state);hintUsed=false;correctionSeen=false;questionNumber+=1;if(current.status==='missing-coverage'){$('questionChapter').textContent='Couverture manquante';$('questionNotion').textContent='Notion indisponible';$('questionKind').textContent='Aucun piège validé';$('questionDifficulty').textContent='Niveau 4 · Piège';renderSegments($('questionText'),{segments:[{type:'text',value:'Aucun modèle de piège validé ne correspond exactement à cette sélection. Choisis une autre notion ou un niveau 1 à 3.'}]});$('hintButton').disabled=true;$('correctionButton').disabled=true;return}const n=findNotion(current.notionId);$('hintButton').disabled=false;$('correctionButton').disabled=false;$('questionChapter').textContent=n?.chapterLabel||current.chapterId;$('questionNotion').textContent=n?.label||current.notionId;$('questionKind').textContent=current.kind;$('questionDifficulty').textContent=`Niveau ${current.difficulty} · ${levelLabel(current.difficulty)}`;$('questionProgress').textContent=`Question ${questionNumber}`;renderSegments($('questionText'),current.question||current.questionHtml);$('feedback').classList.add('hidden');$('conceptBlock').classList.add('hidden');$('trapBlock').classList.add('hidden');$('evaluationButtons').classList.add('hidden');$('resultBanner').classList.add('hidden');$('nextButton').classList.add('hidden');board.clear(false);updateIndicators()}
function updateIndicators(){const mastery=state.masteryStates?.[current?.notionId];$('mastery').textContent=mastery?`${mastery.masteryScore} % estimés`:'Pas encore évaluée';$('confidence').textContent=mastery?`${mastery.confidenceScore<35?'Limitée':mastery.confidenceScore<65?'Moyenne':'Élevée'} · ${mastery.evidenceCount} preuve${mastery.evidenceCount>1?'s':''}`:'Aucune preuve';$('nextReview').textContent=mastery?.nextReviewAt?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short'}).format(new Date(mastery.nextReviewAt)):'À déterminer';$('sessionProgress').textContent=`Question ${Math.max(questionNumber,1)} · ${sessionAnswered} réponse${sessionAnswered>1?'s':''}`;$('saveStatus').textContent='Sauvegardé localement'}
function showFeedback(type){$('feedback').classList.remove('hidden');$('resultBanner').classList.add('hidden');$('nextButton').classList.add('hidden');if(type==='hint'){hintUsed=true;$('feedbackTitle').textContent='Indice';renderSegments($('feedbackText'),current.hintContent||current.hint);$('conceptBlock').classList.add('hidden');$('trapBlock').classList.add('hidden');$('evaluationButtons').classList.add('hidden')}else{correctionSeen=true;$('feedbackTitle').textContent='Correction raisonnée';renderSteps($('feedbackText'),current.correction||current.correctionHtml);renderSegments($('hiddenConcept'),current.hiddenConceptContent||current.hiddenConcept);renderSegments($('oralFormulation'),current.oralFormulationContent||current.oralFormulation);$('conceptBlock').classList.remove('hidden');const explanation=current.trapExplanation;$('trapBlock').classList.toggle('hidden',!explanation);if(explanation){$('trapMistake').textContent=explanation.commonMistake;$('trapTempting').textContent=explanation.whyTempting;$('trapWrong').textContent=explanation.whyWrong;$('trapReflex').textContent=explanation.reflexToRemember}$('evaluationButtons').classList.remove('hidden')}}
function evaluate(baseResult){if(baseResult!=='skipped'&&!correctionSeen)return;let result=baseResult;if(baseResult==='success')result=hintUsed?RESULT.HARD:RESULT.EASY;current.hintUsed=hintUsed;current.correctionSeen=correctionSeen;if(result!=='skipped'){state=saveState(updateProgress(state,current,result));const event=state.masteryEvents?.at(-1);if(event)document.dispatchEvent(new CustomEvent('quiz-tsi-sync-mutation',{detail:{operationType:'append-event',entityType:'mastery-event',entityId:event.id,payload:event}}));sessionAnswered+=1}const labels={easy:'Réussite déclarée sans indice : révision espacée.',hard:'Réussite déclarée avec difficulté ou indice : révision plus proche.',fragile:'Compréhension partielle déclarée : consolidation proche.',failed:'Échec déclaré : révision rapide sans effacer les acquis antérieurs.',skipped:'Question passée : aucune incidence sur la maîtrise.'};$('evaluationButtons').classList.add('hidden');$('resultBanner').textContent=labels[result];$('resultBanner').classList.remove('hidden');$('nextButton').classList.remove('hidden');updateIndicators();updateStats()}
function updateStats(){const vals=Object.values(state.masteryStates||{}).filter(v=>v.evidenceCount),due=dueNotions(state).length;const stats=[['Révisions dues',due],['En retard',vals.filter(v=>v.status==='overdue').length],['Notions fragiles',vals.filter(v=>['fragile','needs-review'].includes(v.status)).length],['Solides actuellement',vals.filter(v=>v.status==='solid').length],['Nouvelles notions',allNotions().length-vals.length],['Activité récente',`${state.masteryEvents?.slice(-7).length||0} événement(s)`]];$('statsSummary').replaceChildren(...stats.map(([label,value])=>{const box=document.createElement('div'),small=document.createElement('small'),strong=document.createElement('strong');small.textContent=label;strong.textContent=value;box.append(small,strong);return box}))}
function toggleDrawer(open){setDrawerState({drawer:$('settingsDrawer'),backdrop:$('drawerBackdrop'),button:$('drawerButton')},open);if(open)updateStats()}
function applyHandedness(value,persist=false){const handedness=persist?writeHandedness(value):value;$('app').classList.toggle('tool-left',handedness==='left');$('app').classList.toggle('tool-right',handedness==='right');document.querySelector(`input[name="handedness"][value="${handedness}"]`).checked=true}
function setShapeMenu(open){$('shapeMenu').classList.toggle('hidden',!open);$('shapeToggle').setAttribute('aria-expanded',String(open))}
function updateShapePlacement(state){$('shapeToggle').setAttribute('aria-pressed',String(state.active===true));if(state.active){$('shapeStatus').textContent=`Placer : ${state.label}`;setToolState($('toolSelect'),$('toolToggle'),'pen')}else $('shapeStatus').textContent=state.placed?'Forme placée. Outil Stylo actif.':state.cancelled?'Placement annulé. Outil Stylo actif.':''}

$('sizeRange').addEventListener('input',()=>$('sizeValue').textContent=$('sizeRange').value);
$('undoButton').addEventListener('click',()=>board.undo());$('redoButton').addEventListener('click',()=>board.redo());$('clearButton').addEventListener('click',()=>board.clear());
document.querySelectorAll('[data-board-shape]').forEach(button=>button.addEventListener('click',()=>{const selected=document.querySelector('input[name="shapeSize"]:checked').value;board.selectShape(button.dataset.boardShape,selected);setShapeMenu(false)}));
$('shapeToggle').addEventListener('click',()=>{if(board.cancelShapePlacement()){setShapeMenu(false);return}setShapeMenu($('shapeMenu').classList.contains('hidden'))});
$('cancelShape').addEventListener('click',()=>{board.cancelShapePlacement();setShapeMenu(false)});
$('applyFilters').addEventListener('click',()=>{newQuestion();toggleDrawer(false)});$('modeSelect').addEventListener('change',()=>{if($('modeSelect').value==='chapter-test'){testApp.open();toggleDrawer(false)}});$('hintButton').addEventListener('click',()=>showFeedback('hint'));$('correctionButton').addEventListener('click',()=>showFeedback('correction'));$('closeFeedback').addEventListener('click',()=>$('feedback').classList.add('hidden'));
$('successButton').addEventListener('click',()=>evaluate('success'));$('almostButton').addEventListener('click',()=>evaluate(RESULT.ALMOST));$('failedButton').addEventListener('click',()=>evaluate(RESULT.FAILED));$('skipButton').addEventListener('click',()=>evaluate(RESULT.SKIPPED));$('nextButton').addEventListener('click',newQuestion);
$('drawerButton').addEventListener('click',()=>toggleDrawer(true));$('closeDrawer').addEventListener('click',()=>toggleDrawer(false));$('drawerBackdrop').addEventListener('click',()=>toggleDrawer(false));
$('questionToggle').addEventListener('click',()=>setQuestionCollapsed($('questionCard'),$('questionToggle'),!$('questionCard').classList.contains('collapsed')));
$('toolToggle').addEventListener('click',()=>{board.cancelShapePlacement();setShapeMenu(false);setToolState($('toolSelect'),$('toolToggle'),$('toolSelect').value==='pen'?'eraser':'pen')});
document.querySelectorAll('input[name="handedness"]').forEach(input=>input.addEventListener('change',()=>applyHandedness(input.value,true)));
$('exportButton').addEventListener('click',()=>exportState(state));$('importInput').addEventListener('change',async e=>{try{state=await importState(e.target.files[0]);updateIndicators();updateStats();alert('Sauvegarde importée.')}catch(err){alert(err.message)}});

initCourseSelectors();applyHandedness(readHandedness());setToolState($('toolSelect'),$('toolToggle'),'pen');const rememberedShapeSize=board.shapeSize;document.querySelector(`input[name="shapeSize"][value="${rememberedShapeSize}"]`).checked=true;updateStats();newQuestion();initSyncUI({getState:()=>state,setState:next=>{state=saveState(next);updateStats()}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(error=>console.warn('Service worker indisponible',error));
