import{COURSE_MAP,allNotions,findNotion}from'./course-map.js';
import{QuizEngine}from'./quiz-engine.js';import{DrawingBoard}from'./board.js';import{loadState,saveState,exportState,importState}from'./storage.js';import{RESULT,updateProgress,dueNotions,weakNotions}from'./scheduler.js';
const $=id=>document.getElementById(id);let state=loadState(),current=null,hintUsed=false,correctionSeen=false;const engine=new QuizEngine();
const board=new DrawingBoard({canvas:$('board'),wrap:$('boardWrap'),hint:$('boardHint'),tool:$('toolSelect'),size:$('sizeRange'),grid:$('gridToggle')});
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o)}
function initCourseSelectors(){option($('partSelect'),'all','Toutes les parties');for(const p of COURSE_MAP)option($('partSelect'),p.id,p.label);refreshChapters();$('partSelect').addEventListener('change',refreshChapters);$('chapterSelect').addEventListener('change',refreshNotions)}
function refreshChapters(){const part=$('partSelect').value;$('chapterSelect').innerHTML='';option($('chapterSelect'),'all','Tous les chapitres');for(const p of COURSE_MAP.filter(p=>part==='all'||p.id===part))for(const c of p.chapters)option($('chapterSelect'),c.id,c.label);refreshNotions()}
function refreshNotions(){const part=$('partSelect').value,chapter=$('chapterSelect').value;$('notionSelect').innerHTML='';option($('notionSelect'),'all','Toutes les notions');for(const n of allNotions().filter(n=>(part==='all'||n.partId===part)&&(chapter==='all'||n.chapterId===chapter)))option($('notionSelect'),n.id,n.label)}
function filters(){let notionId=$('notionSelect').value,chapterId=$('chapterSelect').value,partId=$('partSelect').value;const mode=$('modeSelect').value;if(mode==='daily'){const due=dueNotions(state);if(due.length){notionId=due[0];const n=findNotion(notionId);chapterId=n.chapterId;partId=n.partId}}else if(mode==='weak'){const weak=weakNotions(state);if(weak.length){notionId=weak[0];const n=findNotion(notionId);chapterId=n.chapterId;partId=n.partId}}return{mode,partId,chapterId,notionId,difficulty:$('difficultySelect').value}}
function newQuestion(){current=engine.generate(filters(),state);hintUsed=false;correctionSeen=false;$('questionKind').textContent=current.kind;$('questionDifficulty').textContent=`Niveau ${current.difficulty}`;$('questionText').innerHTML=current.questionHtml;$('feedback').classList.add('hidden');$('conceptBlock').classList.add('hidden');$('evaluationButtons').classList.add('hidden');$('resultBanner').classList.add('hidden');$('nextButton').classList.add('hidden');board.clear(false);updateHeader()}
function updateHeader(){const n=findNotion(current?.notionId);$('currentNotion').textContent=n?.label||current?.notionId||'—';const m=state.notions[current?.notionId]?.mastery||0;$('mastery').textContent=`${m} %`;$('saveStatus').textContent='Sauvegardé localement'}
function showFeedback(type){$('feedback').classList.remove('hidden');$('resultBanner').classList.add('hidden');$('nextButton').classList.add('hidden');if(type==='hint'){hintUsed=true;$('feedbackTitle').textContent='Indice';$('feedbackText').innerHTML=current.hint;$('conceptBlock').classList.add('hidden');$('evaluationButtons').classList.add('hidden')}else{correctionSeen=true;$('feedbackTitle').textContent='Correction raisonnée';$('feedbackText').innerHTML=current.correctionHtml;$('hiddenConcept').textContent=current.hiddenConcept;$('oralFormulation').textContent=current.oralFormulation;$('conceptBlock').classList.remove('hidden');$('evaluationButtons').classList.remove('hidden')}}
function evaluate(baseResult){let result=baseResult;if(baseResult==='success')result=hintUsed?RESULT.HARD:RESULT.EASY;state=saveState(updateProgress(state,current,result));const labels={easy:'Réussie facilement : elle reviendra plus tard.',hard:'Réussie difficilement : elle reviendra plus tôt.',almost:'Presque réussie : la notion reste fragile.',failed:'Ratée : elle sera reproposée rapidement.',skipped:'Passée : elle reste à revoir.'};$('evaluationButtons').classList.add('hidden');$('resultBanner').textContent=labels[result];$('resultBanner').classList.remove('hidden');$('nextButton').classList.remove('hidden');updateHeader();updateStats()}
function updateStats(){const vals=Object.values(state.notions||{}),avg=vals.length?Math.round(vals.reduce((s,v)=>s+(v.mastery||0),0)/vals.length):0;$('statsSummary').innerHTML=`<div><small>Notions travaillées</small><strong>${vals.length}</strong></div><div><small>Maîtrise moyenne</small><strong>${avg} %</strong></div><div><small>Questions répondues</small><strong>${state.history.length}</strong></div><div><small>À revoir aujourd’hui</small><strong>${dueNotions(state).length}</strong></div>`}
$('sizeRange').addEventListener('input',()=>$('sizeValue').textContent=$('sizeRange').value);$('undoButton').addEventListener('click',()=>board.undo());$('redoButton').addEventListener('click',()=>board.redo());$('clearButton').addEventListener('click',()=>board.clear());$('applyFilters').addEventListener('click',newQuestion);$('hintButton').addEventListener('click',()=>showFeedback('hint'));$('correctionButton').addEventListener('click',()=>showFeedback('correction'));$('closeFeedback').addEventListener('click',()=>$('feedback').classList.add('hidden'));$('successButton').addEventListener('click',()=>evaluate('success'));$('almostButton').addEventListener('click',()=>evaluate(RESULT.ALMOST));$('failedButton').addEventListener('click',()=>evaluate(RESULT.FAILED));$('skipButton').addEventListener('click',()=>{evaluate(RESULT.SKIPPED)});$('nextButton').addEventListener('click',newQuestion);$('settingsButton').addEventListener('click',()=>{$('settingsDialog').showModal();updateStats()});$('exportButton').addEventListener('click',()=>exportState(state));$('importInput').addEventListener('change',async e=>{try{state=await importState(e.target.files[0]);updateHeader();updateStats();alert('Sauvegarde importée.')}catch(err){alert(err.message)}});
initCourseSelectors();updateStats();newQuestion();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
