import{createStroke,deserializeScene,detectScribble,sceneTransform,serializeScene,straightCandidate,strokeTouchesGesture,toStraightStroke,transformPoint,VectorHistory}from'./board-model.js';
const STORAGE_KEY='quiz-tsi-vector-board-v1',PREFS_KEY='quiz-tsi-board-gestures-v1';
export class DrawingBoard{
 constructor({canvas,wrap,hint,tool,size,grid,straightToggle,scribbleToggle,storage=localStorage,onChange=()=>{}}){Object.assign(this,{canvas,wrap,hint,tool,size,grid,straightToggle,scribbleToggle,storage,onChange});this.ctx=canvas.getContext('2d',{alpha:true});this.space=null;this.history=new VectorHistory();this.readOnly=false;this.load();this.bind();this.resize()}
 load(){try{const prefs=JSON.parse(this.storage.getItem(PREFS_KEY)||'{}');this.straightToggle.checked=prefs.straight!==false;this.scribbleToggle.checked=prefs.scribble!==false;const saved=this.storage.getItem(STORAGE_KEY);if(saved){const scene=deserializeScene(saved);this.space=scene.space;this.history=new VectorHistory(scene.strokes)}}catch{this.history=new VectorHistory()}}
 persist(){try{this.storage.setItem(STORAGE_KEY,serializeScene({space:this.space,strokes:this.history.strokes}));this.storage.setItem(PREFS_KEY,JSON.stringify({straight:this.straightToggle.checked,scribble:this.scribbleToggle.checked}));this.onChange(this.capture())}catch(error){console.error('Sauvegarde du tableau impossible',error)}}
 bind(){this.canvas.addEventListener('pointerdown',e=>this.begin(e),{passive:false});this.canvas.addEventListener('pointermove',e=>this.move(e),{passive:false});for(const name of ['pointerup','pointercancel'])this.canvas.addEventListener(name,e=>this.end(e),{passive:false});for(const name of ['touchstart','touchmove'])this.canvas.addEventListener(name,e=>e.preventDefault(),{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});this.grid.addEventListener('change',()=>this.canvas.classList.toggle('no-grid',!this.grid.checked));for(const input of [this.straightToggle,this.scribbleToggle])input.addEventListener('change',()=>this.persist());window.addEventListener('resize',()=>{clearTimeout(this.resizeTimer);this.resizeTimer=setTimeout(()=>this.resize(),100)})}
 resize(){const r=this.wrap.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1);if(!this.space)this.space={width:r.width,height:r.height};this.dpr=dpr;this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.lineCap='round';this.ctx.lineJoin='round';this.transform=sceneTransform(this.space,r.width,r.height);this.redraw()}
 point(e){const r=this.canvas.getBoundingClientRect(),t=this.transform;return{x:(e.clientX-r.left-t.offsetX)/t.scale,y:(e.clientY-r.top-t.offsetY)/t.scale,pressure:e.pressure>0?e.pressure:.5,time:e.timeStamp||performance.now()}}
 drawStroke(stroke,clear=false){if(clear)this.redraw();const points=stroke.points.map(p=>transformPoint(p,this.transform));if(!points.length)return;const erase=stroke.tool==='eraser';this.ctx.globalCompositeOperation=erase?'destination-out':'source-over';this.ctx.strokeStyle='#111';for(let i=1;i<points.length;i++){this.ctx.lineWidth=(erase?stroke.width*3:Math.max(1,stroke.width*(.75+points[i].pressure*.55)))*this.transform.scale;this.ctx.beginPath();this.ctx.moveTo(points[i-1].x,points[i-1].y);this.ctx.lineTo(points[i].x,points[i].y);this.ctx.stroke()}if(points.length===1){this.ctx.lineWidth=stroke.width*this.transform.scale;this.ctx.beginPath();this.ctx.moveTo(points[0].x,points[0].y);this.ctx.lineTo(points[0].x+.01,points[0].y+.01);this.ctx.stroke()}}
 redraw(preview){const r=this.canvas.getBoundingClientRect();this.ctx.globalCompositeOperation='source-over';this.ctx.clearRect(0,0,r.width,r.height);for(const stroke of this.history.strokes)this.drawStroke(stroke);if(preview)this.drawStroke(preview);this.hint.classList.toggle('hidden',this.history.strokes.length>0||!!preview)}
 begin(e){if(this.readOnly||e.pointerType==='touch')return;e.preventDefault();e.stopPropagation();this.drawing=true;this.pointerId=e.pointerId;this.canvas.setPointerCapture(e.pointerId);this.active=createStroke({tool:this.tool.value,points:[this.point(e)],width:Number(this.size.value)});this.lastMotion=performance.now();this.linePreview=false;this.armHold()}
 armHold(){clearTimeout(this.holdTimer);if(this.active.tool!=='pen'||!this.straightToggle.checked)return;this.holdTimer=setTimeout(()=>{if(this.drawing&&performance.now()-this.lastMotion>=450&&straightCandidate(this.active.points)){this.linePreview=true;this.active=toStraightStroke(this.active);this.redraw(this.active);this.canvas.classList.add('line-snapped')}},500)}
 move(e){if(!this.drawing||e.pointerId!==this.pointerId)return;e.preventDefault();const p=this.point(e),last=this.active.points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)<.7)return;this.lastMotion=performance.now();if(this.linePreview){this.active=toStraightStroke(this.active,p);this.redraw(this.active)}else{this.active=createStroke({...this.active,points:[...this.active.points,p]});this.drawStroke(createStroke({...this.active,points:[last,p]}));this.armHold()}}
 end(e){if(!this.drawing||e.pointerId!==this.pointerId)return;e.preventDefault();clearTimeout(this.holdTimer);this.drawing=false;if(this.canvas.hasPointerCapture(this.pointerId))this.canvas.releasePointerCapture(this.pointerId);this.pointerId=null;this.canvas.classList.remove('line-snapped');const active=this.active;this.active=null;if(active.points.length<2){this.redraw();return}if(active.tool==='eraser'){const removed=this.history.strokes.filter(s=>strokeTouchesGesture(s,active,active.width*3));if(removed.length)this.history.perform({added:[],removed});this.redraw()}else{const scribble=this.scribbleToggle.checked&&!this.linePreview?detectScribble(active,this.history.strokes):{isScribble:false};if(scribble.isScribble)this.history.perform({added:[],removed:scribble.touched});else this.history.perform({added:[active],removed:[]});this.redraw()}this.persist()}
 undo(){if(this.history.undo()){this.redraw();this.persist()}}
 redo(){if(this.history.redo()){this.redraw();this.persist()}}
 clear(store=true){const removed=[...this.history.strokes];if(store&&removed.length)this.history.perform({added:[],removed});else if(!store)this.history=new VectorHistory();this.redraw();this.persist()}
 capture(){return JSON.parse(serializeScene({space:this.space,strokes:this.history.strokes}))}
 restore(scene){if(scene){const parsed=deserializeScene(scene);this.space=parsed.space;this.history=new VectorHistory(parsed.strokes)}else this.history=new VectorHistory();this.redraw()}
 setReadOnly(value){this.readOnly=value===true;this.canvas.setAttribute('aria-readonly',String(this.readOnly))}
}
