export class DrawingBoard{
 constructor({canvas,wrap,hint,tool,size,grid,onHistoryChange=()=>{}}){this.canvas=canvas;this.wrap=wrap;this.hint=hint;this.tool=tool;this.size=size;this.grid=grid;this.onHistoryChange=onHistoryChange;this.ctx=canvas.getContext('2d',{alpha:true});this.drawing=false;this.pointerId=null;this.history=[];this.future=[];this.bind();this.resize();this.notifyHistory()}
 bind(){this.canvas.addEventListener('pointerdown',e=>this.begin(e),{passive:false});this.canvas.addEventListener('pointermove',e=>this.move(e),{passive:false});this.canvas.addEventListener('pointerup',e=>this.end(e),{passive:false});this.canvas.addEventListener('pointercancel',e=>this.end(e),{passive:false});this.canvas.addEventListener('touchstart',e=>e.preventDefault(),{passive:false});this.canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});this.grid.addEventListener('change',()=>this.canvas.classList.toggle('no-grid',!this.grid.checked));window.addEventListener('resize',()=>{clearTimeout(this.timer);this.timer=setTimeout(()=>this.resize(),100)})}
 resize(){const old=document.createElement('canvas'),oldDpr=this.dpr||1;old.width=this.canvas.width;old.height=this.canvas.height;if(old.width&&old.height)old.getContext('2d').drawImage(this.canvas,0,0);const r=this.wrap.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1);this.dpr=dpr;this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.canvas.style.width=r.width+'px';this.canvas.style.height=r.height+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.lineCap='round';this.ctx.lineJoin='round';if(old.width&&old.height)this.ctx.drawImage(old,0,0,old.width/oldDpr,old.height/oldDpr)}
 point(e){const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 notifyHistory(){this.onHistoryChange({canUndo:this.history.length>0,canRedo:this.future.length>0})}
 save(){this.history.push(this.canvas.toDataURL());if(this.history.length>40)this.history.shift();this.future=[];this.notifyHistory()}
 begin(e){if(e.pointerType==='touch')return;e.preventDefault();e.stopPropagation();this.save();this.drawing=true;this.pointerId=e.pointerId;this.canvas.setPointerCapture(e.pointerId);const p=this.point(e);this.x=p.x;this.y=p.y;this.hint.classList.add('hidden')}
 move(e){if(!this.drawing||e.pointerId!==this.pointerId)return;e.preventDefault();const p=this.point(e),pressure=e.pressure>0?e.pressure:.5,base=Number(this.size.value),erase=this.tool.value==='eraser';this.ctx.globalCompositeOperation=erase?'destination-out':'source-over';this.ctx.strokeStyle='#111';this.ctx.lineWidth=erase?base*3:Math.max(1,base*(.75+pressure*.55));this.ctx.beginPath();this.ctx.moveTo(this.x,this.y);this.ctx.lineTo(p.x,p.y);this.ctx.stroke();this.x=p.x;this.y=p.y}
 end(e){if(!this.drawing||e.pointerId!==this.pointerId)return;e.preventDefault();this.drawing=false;if(this.canvas.hasPointerCapture(this.pointerId))this.canvas.releasePointerCapture(this.pointerId);this.pointerId=null}
 restore(url){const img=new Image();img.onload=()=>{const r=this.canvas.getBoundingClientRect();this.ctx.clearRect(0,0,r.width,r.height);this.ctx.drawImage(img,0,0,r.width,r.height)};img.src=url}
 undo(){if(!this.history.length)return;this.future.push(this.canvas.toDataURL());this.restore(this.history.pop());this.notifyHistory()}
 redo(){if(!this.future.length)return;this.history.push(this.canvas.toDataURL());this.restore(this.future.pop());this.notifyHistory()}
 clear(store=true){if(store)this.save();const r=this.canvas.getBoundingClientRect();this.ctx.clearRect(0,0,r.width,r.height);this.hint.classList.remove('hidden');this.notifyHistory()}
}
