const finite=Number.isFinite;
export const SHAPE_KINDS=['circle','trig-circle','orthonormal-frame','axes','line','arrow','rectangle','square','triangle'];
export const SHAPE_LABELS={circle:'Cercle','trig-circle':'Cercle trigonométrique','orthonormal-frame':'Repère orthonormé',axes:'Axes seuls',line:'Droite',arrow:'Flèche',rectangle:'Rectangle',square:'Carré',triangle:'Triangle'};
const uid=()=>globalThis.crypto?.randomUUID?.()||`shape-${Date.now()}-${Math.random()}`;
const point=(x,y)=>({x,y});
const line=(x1,y1,x2,y2,arrow='none')=>({type:'line',from:point(x1,y1),to:point(x2,y2),arrow});
const label=(text,x,y,align='center')=>({type:'label',text,x,y,align});
const arrowHead=(path,size=8)=>{const {from:a,to:b}=path,angle=Math.atan2(b.y-a.y,b.x-a.x);return[[b,point(b.x-Math.cos(angle-.55)*size,b.y-Math.sin(angle-.55)*size)],[b,point(b.x-Math.cos(angle+.55)*size,b.y-Math.sin(angle+.55)*size)]]};
export function createBoardShape({id=uid(),kind,x,y,width,height,createdAt=Date.now()}){if(!SHAPE_KINDS.includes(kind))throw new TypeError('Forme mathématique inconnue');const square=['circle','trig-circle','square'].includes(kind),w=Number(width),h=square?w:Number(height);if(![x,y,w,h,createdAt].every(finite)||w<24||h<24||w>10000||h>10000)throw new TypeError('Coordonnées de forme invalides');return{id:String(id),type:'shape',kind,x:Number(x),y:Number(y),width:w,height:h,createdAt:Number(createdAt),bounds:{x:Number(x)-w/2,y:Number(y)-h/2,width:w,height:h}}}
export function defaultShapeSize(kind,visible){const base=Math.max(90,Math.min(220,Math.min(visible.width,visible.height)*.3));if(kind==='line'||kind==='arrow')return{width:Math.min(240,visible.width*.42),height:50};if(kind==='rectangle')return{width:Math.min(220,visible.width*.38),height:Math.min(130,visible.height*.22)};if(kind==='triangle')return{width:Math.min(190,visible.width*.34),height:Math.min(160,visible.height*.27)};if(kind==='axes'||kind==='orthonormal-frame')return{width:Math.min(260,visible.width*.44),height:Math.min(220,visible.height*.37)};return{width:base,height:base}}
export function shapeGeometry(shape){const s=createBoardShape(shape),{x,y,width:w,height:h,kind}=s,l=x-w/2,r=x+w/2,t=y-h/2,b=y+h/2,paths=[],circles=[],labels=[];const add=p=>paths.push(p);if(kind==='circle'||kind==='trig-circle')circles.push({x,y,r:w/2});if(kind==='line'||kind==='arrow')add(line(l,y,r,y,kind==='arrow'?'end':'none'));if(kind==='rectangle'||kind==='square'){add(line(l,t,r,t));add(line(r,t,r,b));add(line(r,b,l,b));add(line(l,b,l,t))}if(kind==='triangle'){add(line(x,t,r,b));add(line(r,b,l,b));add(line(l,b,x,t))}if(['axes','orthonormal-frame','trig-circle'].includes(kind)){const axisW=kind==='trig-circle'?w*1.28:w,axisH=kind==='trig-circle'?h*1.28:h;add(line(x-axisW/2,y,x+axisW/2,y,'end'));add(line(x,y+axisH/2,x,y-axisH/2,'end'));labels.push(label('O',x-7,y+14,'right'))}if(kind==='orthonormal-frame'){const unit=Math.max(20,Math.min(w,h)/6);for(let d=unit;d<w/2-5;d+=unit){add(line(x+d,y-4,x+d,y+4));add(line(x-d,y-4,x-d,y+4))}for(let d=unit;d<h/2-5;d+=unit){add(line(x-4,y+d,x+4,y+d));add(line(x-4,y-d,x+4,y-d))}labels.push(label('x',r-3,y+16,'right'),label('y',x+12,t+7,'left'))}if(kind==='trig-circle'){const rr=w/2,ticks=[[r,y,'0',10,14],[x,t,'π/2',0,-8],[l,y,'π',-10,14],[x,b,'3π/2',0,17]];for(const [px,py,textValue,dx,dy]of ticks){const vx=(px-x)/rr,vy=(py-y)/rr;add(line(px-vx*4,py-vy*4,px+vx*4,py+vy*4));labels.push(label(textValue,px+dx,py+dy))}}for(const p of [...paths])if(p.arrow==='end')for(const [a,bp]of arrowHead(p,Math.min(9,Math.max(6,w/28))))paths.push(line(a.x,a.y,bp.x,bp.y));return{paths,circles,labels,bounds:s.bounds}}
const segmentDistance=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy;if(!n)return Math.hypot(p.x-a.x,p.y-a.y);const q=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/n));return Math.hypot(p.x-a.x-q*dx,p.y-a.y-q*dy)};
export function shapeTouchesGesture(shape,gesture,radius=8){const g=shapeGeometry(shape);for(const p of gesture.points)if(g.paths.some(v=>segmentDistance(p,v.from,v.to)<=radius)||g.circles.some(c=>Math.abs(Math.hypot(p.x-c.x,p.y-c.y)-c.r)<=radius))return true;return false}
