import{createBoardShape}from'./board-shapes.js';
const finite=n=>Number.isFinite(n);
export const distance=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
const segmentDistance=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return distance(p,a);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));return distance(p,{x:a.x+t*dx,y:a.y+t*dy})};
const bounds=points=>{const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)}};
export function simplifyPoints(points,minDistance=0.7){if(points.length<3)return points.map(p=>({...p}));const kept=[{...points[0]}];for(let i=1;i<points.length-1;i++)if(distance(kept.at(-1),points[i])>=minDistance)kept.push({...points[i]});if(distance(kept.at(-1),points.at(-1))||kept.length===1)kept.push({...points.at(-1)});return kept}
export function createStroke({id=globalThis.crypto?.randomUUID?.()||`stroke-${Date.now()}-${Math.random()}`,tool='pen',points,width=3,createdAt=Date.now(),type='free'}){const clean=simplifyPoints(points).map(p=>({x:Number(p.x),y:Number(p.y),pressure:finite(p.pressure)?Math.max(0,Math.min(1,p.pressure)):0.5,time:finite(p.time)?p.time:createdAt}));if(!clean.length||clean.some(p=>!finite(p.x)||!finite(p.y)))throw new TypeError('Coordonnées de trait invalides');return{id,tool,points:clean,width:Number(width),createdAt,type,bounds:bounds(clean)}}
export const createVectorObject=value=>value?.type==='shape'?createBoardShape(value):createStroke(value);
export function serializeScene(scene){return JSON.stringify({version:2,space:{...scene.space},objects:scene.strokes.map(createVectorObject)})}
export function deserializeScene(value){const data=typeof value==='string'?JSON.parse(value):value;if(![1,2].includes(data?.version)||!finite(data.space?.width)||!finite(data.space?.height)||data.space.width<=0||data.space.height<=0)throw new TypeError('Tableau vectoriel invalide');const objects=data.version===1?(data.strokes||[]):data.objects;if(!Array.isArray(objects))throw new TypeError('Objets vectoriels invalides');return{space:{width:data.space.width,height:data.space.height},strokes:objects.map(createVectorObject)}}
export function sceneTransform(space,width,height){const scale=Math.min(width/space.width,height/space.height);return{scale,offsetX:(width-space.width*scale)/2,offsetY:(height-space.height*scale)/2}}
export function transformPoint(point,transform){return{x:point.x*transform.scale+transform.offsetX,y:point.y*transform.scale+transform.offsetY,pressure:point.pressure,time:point.time}}
export function pathLength(points){let n=0;for(let i=1;i<points.length;i++)n+=distance(points[i-1],points[i]);return n}
export function straightCandidate(points,{minLength=80,maxMeanDeviation=3.5,maxRatio=0.075,minSpan=65}={}){if(points.length<2)return false;const a=points[0],b=points.at(-1),span=distance(a,b);if(span<minSpan||pathLength(points)<minLength)return false;const box=bounds(points);if(Math.max(box.width,box.height)<minSpan)return false;const mean=points.reduce((sum,p)=>sum+segmentDistance(p,a,b),0)/points.length;return mean<=maxMeanDeviation&&mean/span<=maxRatio&&pathLength(points)/span<1.18}
export function toStraightStroke(stroke,end=stroke.points.at(-1)){return createStroke({...stroke,type:'line',points:[stroke.points[0],{...end}]})}
export function circleCandidate(points,{minDiameter=44,minPoints=8,maxAspectRatio=1.28,maxClosureRatio=.3,maxRadiusVariation=.16,minCircumferenceRatio=.72,maxCircumferenceRatio=1.35}={}){if(points.length<minPoints)return false;const box=bounds(points),small=Math.min(box.width,box.height),large=Math.max(box.width,box.height);if(small<minDiameter||large/small>maxAspectRatio)return false;const radius=(box.width+box.height)/4,center={x:box.x+box.width/2,y:box.y+box.height/2};if(distance(points[0],points.at(-1))>Math.max(12,small*maxClosureRatio))return false;const radii=points.map(p=>distance(p,center)),variation=radii.reduce((sum,r)=>sum+Math.abs(r-radius),0)/(radii.length*radius);if(variation>maxRadiusVariation)return false;const circumference=2*Math.PI*radius,length=pathLength(points);if(length/circumference<minCircumferenceRatio||length/circumference>maxCircumferenceRatio)return false;const angles=points.map(p=>Math.atan2(p.y-center.y,p.x-center.x));let travel=0,reversals=0,lastDirection=0;for(let i=1;i<angles.length;i++){let delta=angles[i]-angles[i-1];while(delta>Math.PI)delta-=Math.PI*2;while(delta< -Math.PI)delta+=Math.PI*2;travel+=Math.abs(delta);const direction=Math.sign(delta);if(direction&&lastDirection&&direction!==lastDirection)reversals++;if(direction)lastDirection=direction}return travel>=Math.PI*1.65&&travel<=Math.PI*2.7&&reversals<=2}
export function toCircleStroke(stroke){const box=bounds(stroke.points),center={x:box.x+box.width/2,y:box.y+box.height/2},radius=(box.width+box.height)/4,start=Math.atan2(stroke.points[0].y-center.y,stroke.points[0].x-center.x),first=stroke.points[0],last=stroke.points.at(-1),count=48,points=[];for(let i=0;i<=count;i++){const progress=i/count,angle=start+Math.PI*2*progress;points.push({x:center.x+Math.cos(angle)*radius,y:center.y+Math.sin(angle)*radius,pressure:first.pressure+(last.pressure-first.pressure)*progress,time:first.time+(last.time-first.time)*progress})}return createStroke({...stroke,type:'circle',points})}
const directionChanges=points=>{let changes=0,last=0;for(let i=2;i<points.length;i++){const a=points[i-1],cross=(a.x-points[i-2].x)*(points[i].y-a.y)-(a.y-points[i-2].y)*(points[i].x-a.x),sign=Math.sign(cross);if(sign&&last&&sign!==last)changes++;if(sign)last=sign}return changes};
const boxesOverlap=(a,b,pad=0)=>a.x<=b.x+b.width+pad&&a.x+a.width+pad>=b.x&&a.y<=b.y+b.height+pad&&a.y+a.height+pad>=b.y;
export function strokeTouchesGesture(stroke,gesture,radius=Math.max(5,gesture.width*1.5)){if(!boxesOverlap(stroke.bounds,gesture.bounds,radius))return false;let hits=0;for(const p of stroke.points){if(gesture.points.some((g,i)=>i&&segmentDistance(p,gesture.points[i-1],g)<=radius))hits++}return hits>=Math.max(1,Math.ceil(stroke.points.length*.12))}
export function detectScribble(gesture,existing){const box=gesture.bounds,area=Math.max(1,box.width*box.height),length=pathLength(gesture.points),duration=Math.max(1,gesture.points.at(-1).time-gesture.points[0].time),changes=directionChanges(gesture.points),touched=existing.filter(s=>strokeTouchesGesture(s,gesture));const density=length/Math.sqrt(area),speed=length/duration;const closed=distance(gesture.points[0],gesture.points.at(-1))<Math.min(box.width,box.height)*.35;const confidence=(length>120?1:0)+(density>4.2?1:0)+(changes>=5?1:0)+(speed>.18?1:0)+(touched.length?2:0);return{isScribble:!closed&&box.width>12&&box.height>8&&touched.length>0&&confidence>=6,touched,confidence}}
export class VectorHistory{
 constructor(strokes=[]){this.strokes=strokes;this.undoStack=[];this.redoStack=[]}
 perform(operation){this.#apply(operation,false);this.undoStack.push(operation);this.redoStack=[]}
 #apply(op,inverse){const remove=inverse?op.added:op.removed,add=inverse?op.removed:op.added;const ids=new Set(remove.map(s=>s.id));this.strokes=this.strokes.filter(s=>!ids.has(s.id));this.strokes.push(...add.map(createVectorObject))}
 undo(){const op=this.undoStack.pop();if(!op)return false;this.#apply(op,true);this.redoStack.push(op);return true}
 redo(){const op=this.redoStack.pop();if(!op)return false;this.#apply(op,false);this.undoStack.push(op);return true}
}
