import{activeWorkspace}from'./workspace/user-workspace.js';import{allNotions}from'./course-map.js';import{migrateLegacyState}from'./mastery/mastery-migration.js';import{validateMasteryEvent,activeEvents}from'./mastery/mastery-event-validator.js';import{rebuildMastery}from'./mastery/mastery-engine.js';
const KEY='state',BACKUP_KEY='state-backup',MAX_IMPORT_BYTES=5_000_000;
const store=()=>activeWorkspace();
const deviceId=()=>localStorage.getItem('quiz-tsi-device-id')||(()=>{const id=globalThis.crypto?.randomUUID?.()||`device-${Date.now().toString(36)}`;localStorage.setItem('quiz-tsi-device-id',id);return id})();
export const emptyState=()=>({version:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),deviceId:deviceId(),notions:{},history:[],masteryEvents:[],masteryStates:{},reviewQueue:[],preferences:{}});
export function loadState(){const raw=store().storage.getItem(store().key(KEY));if(!raw)return emptyState();try{const parsed=JSON.parse(raw),migration=migrateLegacyState(parsed,{deviceId:deviceId()});if(migration.migrated){store().write(BACKUP_KEY,migration.backup);store().write(KEY,migration.state)}return{...emptyState(),...migration.state}}catch(error){console.error('Chargement de la progression impossible',error);throw new Error('La progression locale est illisible. Une sauvegarde n’a pas été écrasée.')}}
export function saveState(state){const next={...state,updatedAt:new Date().toISOString()};store().write(KEY,next);return next}
export function exportState(state){const blob=new Blob([serializeState(state)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`quiz-tsi-sauvegarde-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
export function serializeState(state){return JSON.stringify({schema:'quiz-tsi-mastery',version:2,exportedAt:new Date().toISOString(),deviceId:state.deviceId,events:state.masteryEvents||[],masteryStates:state.masteryStates||{},reviewQueue:state.reviewQueue||[],preferences:state.preferences||{}},null,2)}
export async function importState(file){const raw=await file.text();if(new TextEncoder().encode(raw).length>MAX_IMPORT_BYTES)throw new Error('Import trop volumineux');const data=JSON.parse(raw);if(data?.schema!=='quiz-tsi-mastery'||data.version!==2)throw new Error('Version de sauvegarde incompatible');const notionIds=new Set(allNotions().map(n=>n.id)),existing=loadState(),ids=new Set((existing.masteryEvents||[]).map(e=>e.id)),report={added:0,duplicates:0,rejected:0,unknownNotions:[],recalculated:false};const added=[];for(const event of data.events||[]){const validation=validateMasteryEvent(event,{notionIds});if(!validation.valid){report.rejected++;if(validation.errors.includes('notion inconnue'))report.unknownNotions.push(event.notionId);continue}if(ids.has(event.id)){report.duplicates++;continue}ids.add(event.id);added.push(event);report.added++}const events=activeEvents([...(existing.masteryEvents||[]),...added]),masteryStates=rebuildMastery(events,[...notionIds]);report.recalculated=true;const state=saveState({...existing,masteryEvents:events,masteryStates,reviewQueue:Array.isArray(data.reviewQueue)?data.reviewQueue:[],preferences:data.preferences&&typeof data.preferences==='object'?data.preferences:{},lastImportReport:report});return Object.assign(state,{importReport:report})}
