import{loadState}from'../storage.js';
import{allNotions,COURSE_MAP}from'../course-map.js';
import{accountOverview,buildAdaptivePlan,chapterOptions,normalizeEvents}from'../planner/study-plan.js';
import{toast}from'../shell/toast.js';

const DAY_LABEL=new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short'});
const FULL_DATE=new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'});
const TYPE_LABEL={exam:'Examen',revision:'Révision',chapter:'Fin de chapitre'};
let workspace,state,events=[],plan;
const notionMap=()=>new Map(allNotions().map(n=>[n.id,n]));
const chapterMap=()=>new Map(COURSE_MAP.flatMap(part=>part.chapters.map(chapter=>[chapter.id,{...chapter,partId:part.id,partLabel:part.label}])));

export function init(context){
 workspace=context.workspace;state=loadState();events=normalizeEvents(workspace.read('study-plan',{events:[]})?.events||[]);
 wireForm();wireFilters();render();
 document.addEventListener('quiz-tsi-progress-merged',event=>{state=event.detail.state;render()});
}

function wireForm(){
 const form=document.querySelector('[data-event-form]'),chapter=form.elements.chapterId,date=form.elements.date;
 chapter.replaceChildren(...chapterOptions().map(item=>option(item.id,item.label)));date.min=localDate(new Date());
 form.onsubmit=event=>{event.preventDefault();const data=new FormData(form),entry={id:crypto.randomUUID(),title:data.get('title'),date:data.get('date'),type:data.get('type'),chapterId:data.get('chapterId'),createdAt:new Date().toISOString()};events=normalizeEvents([...events,entry]);persist();form.reset();date.min=localDate(new Date());render();toast('Échéance ajoutée au plan de travail.')};
 document.querySelector('[data-refresh]').onclick=()=>{state=loadState();render();toast('Plan actualisé avec tes derniers résultats.')};
}
function wireFilters(){document.querySelector('[data-skill-search]').oninput=renderSkills;document.querySelector('[data-skill-filter]').onchange=renderSkills}
function persist(){workspace.write('study-plan',{version:1,events,updatedAt:new Date().toISOString()})}
function render(){plan=buildAdaptivePlan({state,events,now:new Date(),days:14,maxPerDay:4});renderSummary();renderToday();renderNextEvent();renderAgenda();renderEvents();renderSkills()}

function renderSummary(){
 const o=plan.overview,level=o.average<35?'Fondations':o.average<60?'En progression':o.average<80?'Solide':'Très solide';
 const cards=[['Niveau estimé',`${o.average} %`,level],['Programme exploré',`${o.coverage} %`,`${o.notions.length-o.unseen.length} notions travaillées`],['À revoir',String(o.due.length),o.due.length?'Priorité du jour':'Aucune échéance urgente'],['À explorer',String(o.unseen.length),o.unseen.length?'Nouvelles notions disponibles':'Tout le programme a été abordé']];
 const root=document.querySelector('[data-plan-summary]');root.replaceChildren(...cards.map(([title,value,copy])=>{const article=document.createElement('article');article.className='summary-card';const p=document.createElement('p'),strong=document.createElement('strong'),span=document.createElement('span');p.className='eyebrow';p.textContent=title;strong.textContent=value;span.textContent=copy;article.append(p,strong,span);return article}))
}
function renderToday(){const today=plan.days[0]?.tasks||[],root=document.querySelector('[data-today-tasks]');root.replaceChildren();document.querySelector('[data-today-duration]').textContent=today.length?`${today.reduce((sum,t)=>sum+t.minutes,0)} min`:'Journée légère';if(!today.length){root.append(empty('Rien d’urgent aujourd’hui. Une courte séance de formules reste disponible.'));return}root.append(...today.map(taskCard))}
function taskCard(item){const article=document.createElement('article');article.className='task-card';const icon=document.createElement('span');icon.className='task-icon';icon.textContent=({exam:'E',review:'R',weak:'!',explore:'+'})[item.type]||'R';const body=document.createElement('div'),title=document.createElement('h3'),copy=document.createElement('p'),button=document.createElement('button');title.textContent=item.title;copy.textContent=`${item.reason} · ${item.minutes} min`;body.append(title,copy);button.type='button';button.className='primary';button.textContent='Réviser';button.onclick=()=>startTask(item);article.append(icon,body,button);return article}
function startTask(item){const notion=notionMap().get(item.notionId);if(!notion)return;workspace.write('active-session',{mode:'free',partId:notion.partId,chapterId:notion.chapterId,notionId:notion.id,difficulty:item.type==='explore'?'1':'adaptive',source:'adaptive-plan',createdAt:new Date().toISOString()});location.href='./quiz.html'}
function renderNextEvent(){const today=new Date(),next=events.find(event=>new Date(`${event.date}T12:00:00`)>=new Date(today.getFullYear(),today.getMonth(),today.getDate())),title=document.querySelector('[data-next-event-title]'),copy=document.querySelector('[data-next-event-copy]');if(!next){title.textContent='Aucun examen enregistré';copy.textContent='Ajoute une date pour que le plan prépare automatiquement les chapitres concernés.';return}const chapter=chapterMap().get(next.chapterId),days=Math.max(0,Math.ceil((new Date(`${next.date}T12:00:00`)-today)/86_400_000));title.textContent=next.title;copy.textContent=`${FULL_DATE.format(new Date(`${next.date}T12:00:00`))} · ${chapter?.label||'Chapitre'} · ${days===0?'aujourd’hui':days===1?'demain':`dans ${days} jours`}`}
function renderAgenda(){const root=document.querySelector('[data-agenda]'),today=localDate(new Date());root.replaceChildren(...plan.days.map(day=>{const article=document.createElement('article');article.className=`agenda-day${day.date===today?' today':''}`;const header=document.createElement('header'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=DAY_LABEL.format(new Date(`${day.date}T12:00:00`));span.textContent=`${day.tasks.reduce((sum,t)=>sum+t.minutes,0)} min`;header.append(strong,span);article.append(header);if(!day.tasks.length){const p=document.createElement('p');p.className='agenda-empty';p.textContent='Repos ou rattrapage';article.append(p)}else for(const task of day.tasks){const button=document.createElement('button'),small=document.createElement('small');button.type='button';button.className='agenda-task';button.textContent=task.title;small.textContent=task.reason;button.append(small);button.onclick=()=>startTask(task);article.append(button)}return article}))}
function renderEvents(){const root=document.querySelector('[data-event-list]');root.replaceChildren();if(!events.length){root.append(empty('Aucune échéance enregistrée.'));return}for(const event of events){const date=new Date(`${event.date}T12:00:00`),article=document.createElement('article');article.className='event-item';const dateBox=document.createElement('div');dateBox.className='event-date';const day=document.createElement('strong'),month=document.createElement('small');day.textContent=String(date.getDate());month.textContent=new Intl.DateTimeFormat('fr-FR',{month:'short'}).format(date);dateBox.append(day,month);const body=document.createElement('div'),title=document.createElement('strong'),copy=document.createElement('p');title.textContent=event.title;copy.textContent=`${TYPE_LABEL[event.type]} · ${chapterMap().get(event.chapterId)?.label||'Chapitre'}`;body.append(title,copy);const remove=document.createElement('button');remove.type='button';remove.className='secondary';remove.textContent='Retirer';remove.setAttribute('aria-label',`Retirer ${event.title} du calendrier`);remove.onclick=()=>{events=events.filter(x=>x.id!==event.id);persist();render();toast('Échéance retirée.')};article.append(dateBox,body,remove);root.append(article)}}
function renderSkills(){if(!plan)return;const query=document.querySelector('[data-skill-search]').value.trim().toLowerCase(),filter=document.querySelector('[data-skill-filter]').value,root=document.querySelector('[data-skills]'),chapters=chapterMap();root.replaceChildren();let count=0;for(const chapter of chapters.values()){const notions=plan.overview.notions.filter(n=>n.chapterId===chapter.id).filter(n=>!query||`${n.label} ${chapter.label}`.toLowerCase().includes(query)).filter(n=>filter==='all'||filter==='weak'&&['weak','learning'].includes(n.status.key)||n.status.key===filter);if(!notions.length)continue;count+=notions.length;const details=document.createElement('details');details.className='chapter-skills';details.open=filter!=='all'||Boolean(query);const summary=document.createElement('summary');summary.textContent=`${chapter.partLabel} · ${chapter.label} (${notions.length})`;const list=document.createElement('div');list.className='chapter-skill-list';list.append(...notions.map(skillRow));details.append(summary,list);root.append(details)}if(!count)root.append(empty('Aucune notion ne correspond à ce filtre.'))}
function skillRow(notion){const row=document.createElement('article');row.className='skill-row';const body=document.createElement('div'),title=document.createElement('p'),copy=document.createElement('small');title.textContent=notion.label;copy.textContent=`${notion.status.evidence} preuve${notion.status.evidence>1?'s':''}`;body.append(title,copy);const meter=document.createElement('div'),bar=document.createElement('span');meter.className='skill-meter';meter.setAttribute('role','progressbar');meter.setAttribute('aria-label',`Maîtrise de ${notion.label}`);meter.setAttribute('aria-valuemin','0');meter.setAttribute('aria-valuemax','100');meter.setAttribute('aria-valuenow',String(notion.status.score));bar.style.width=`${notion.status.score}%`;meter.append(bar);const status=document.createElement('strong');status.className=`status-${notion.status.key}`;status.textContent=notion.status.label;row.append(body,meter,status);return row}
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o}
function empty(message){const p=document.createElement('p');p.className='empty-state';p.textContent=message;return p}
function localDate(date){const d=new Date(date);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
