import{COURSE_MAP,allNotions}from'../course-map.js';
import{QuestionCache}from'../question-bank/question-cache.js';
import{QuestionRepository}from'../question-bank/question-repository.js';
import{QuestionSync}from'../question-bank/question-sync.js';
import{operation,enqueue}from'../question-bank/question-outbox.js';
import{validateQuestion}from'../question-bank/question-validator.js';
import{generateVariants}from'../question-bank/parameterized-generator.js';
import{insertAtSelection,mathSnippet,parameterizedExample,pedagogicalError,variableDraft,variableSpec}from'../question-bank/editor-helpers.js';
import{renderSegments,renderSteps}from'../math/render-math.js';
import{toast}from'../shell/toast.js';

const TYPES={course:'Question de cours',formula:'Formule',parameterized:'Exercice avec valeurs variables'};
const LEVELS={1:'Fondamental',2:'Standard',3:'Réflexe prépa',4:'Piège'};
let cache,sync,account,currentTab='common',editing=null,archiveTarget=null;

export async function init(context){
 account=context.account;
 cache=new QuestionCache();cache.open(account.userId);
 sync=context.client?new QuestionSync(cache,new QuestionRepository(context.client)):null;
 tabs();wire();render();
 if(sync)sync.sync().then(()=>{status('Synchronisé');render()}).catch(()=>status('Hors connexion : la banque locale reste disponible.'));
 document.addEventListener('quiz-tsi-account-leaving',()=>{sync?.stop();cache.close()},{once:true});
}
function tabs(){const rows=[['common','Banque commune'],['mine','Mes questions'],['draft','Brouillons'],...(['admin','owner'].includes(account.role)?[['publish','À publier'],['archives','Archives']]:[])],root=document.querySelector('[data-tabs]');for(const[id,label]of rows){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=label;b.onclick=()=>{currentTab=id;render()};root.append(b)}}
function wire(){document.querySelector('[data-create]').onclick=()=>openEditor();document.querySelector('[data-search]').oninput=render;document.querySelector('[data-difficulty]').onchange=render;const d=document.querySelector('[data-confirm]');document.querySelector('[data-confirm-cancel]').onclick=()=>d.close();document.querySelector('[data-confirm-ok]').onclick=()=>{archive(archiveTarget);d.close()}}
function rows(){const all=[...cache.data.common,...cache.data.private,...cache.data.management],mine=q=>q.author_id===account.userId;let out=currentTab==='common'?all.filter(q=>q.scope==='common'&&q.status==='published'):currentTab==='mine'?all.filter(q=>mine(q)&&q.status==='published'):currentTab==='draft'?all.filter(q=>mine(q)&&q.status==='draft'):currentTab==='publish'?all.filter(q=>q.status==='draft'&&q.scope==='common'):all.filter(q=>q.status==='archived');const query=document.querySelector('[data-search]').value.toLowerCase(),difficulty=document.querySelector('[data-difficulty]').value;return out.filter(q=>(!query||[q.title,q.chapter_id,q.notion_id].join(' ').toLowerCase().includes(query))&&(!difficulty||String(q.difficulty)===difficulty)).filter(q=>q.scope==='common'||mine(q))}
function render(){const root=document.querySelector('[data-question-list]'),list=rows();root.replaceChildren();if(!list.length){const e=document.createElement('div');e.className='empty';e.textContent='Aucune question dans cette section.';root.append(e);return}for(const q of list)root.append(card(q))}
function card(q){const a=document.createElement('article');a.className='card question-card-item';const h=document.createElement('header'),title=document.createElement('strong'),type=document.createElement('span');title.textContent=q.title;type.className='badge';type.textContent=TYPES[q.question_type]||'Question';h.append(title,type);const meta=document.createElement('p');const notion=allNotions().find(n=>n.id===q.notion_id);meta.textContent=`${notion?.chapterLabel||q.chapter_id} · ${notion?.label||q.notion_id} · ${LEVELS[q.difficulty]} · ${q.status==='published'?'Publiée':q.status==='archived'?'Archivée':'Brouillon'} · ${q.scope==='common'?'Commune':'Privée'} · Modifiée ${date(q.updated_at)}`;const actions=document.createElement('div');actions.className='actions-row';actions.append(action('Aperçu',()=>preview(q)));const own=q.author_id===account.userId,manager=['admin','owner'].includes(account.role);if(own||manager)actions.append(action('Modifier',()=>openEditor(q)));actions.append(action('Dupliquer',()=>duplicate(q,'private')));if(manager)actions.append(action('Dupliquer comme brouillon commun',()=>duplicate(q,'common')));if((own||manager)&&q.status==='draft')actions.append(action('Publier',()=>publish(q)));if((own||manager)&&q.status==='published')actions.append(action('Remettre en brouillon',()=>mutate(q,{status:'draft'})));if((own||manager)&&q.status!=='archived')actions.append(action('Archiver',()=>{archiveTarget=q;document.querySelector('[data-confirm]').showModal()}));a.append(h,meta,actions);return a}
function action(label,fn){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=label;b.onclick=fn;return b}
function date(v){return v?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short'}).format(new Date(v)):'date inconnue'}
function status(v){document.querySelector('[data-bank-status]').textContent=v}

function openEditor(question=null){
 editing=question;
 document.querySelector('[data-question-list]').hidden=true;
 const root=document.querySelector('[data-editor]');root.hidden=false;root.replaceChildren();
 let step=1,type=question?.question_type||'',variables=(question?.variable_spec?.variables||[]).map(variableDraft),activeTextarea=null,previewValid=false;
 root.innerHTML=`
 <p class="wizard-progress" data-progress>Étape 1 sur 4</p>
 <section class="wizard-step" data-step="1"><h2>Quel type de question ?</h2><div class="cards" data-types></div></section>
 <section class="wizard-step" data-step="2" hidden><h2>Classer la question</h2><div class="field-grid"><label>Partie<select name="part"></select></label><label>Chapitre<select name="chapter"></select></label><label>Notion<select name="notion"></select></label><label>Difficulté<select name="difficulty"><option value="1">1 — Fondamental</option><option value="2">2 — Standard</option><option value="3">3 — Réflexe prépa</option><option value="4">4 — Piège</option></select></label><label>Titre interne<input name="title" maxlength="160"></label><label>Catégorie facultative<input name="category"></label></div><p>Fondamental mémorise l’essentiel. Standard applique le cours. Réflexe prépa exige un calcul ou une formule. Piège entraîne une erreur classique.</p><p class="form-error" data-level-warning role="alert"></p></section>
 <section class="wizard-step" data-step="3" hidden><h2>Écrire le contenu</h2><p class="editor-help">Clique d’abord dans le champ à modifier. Utilise « Formule en ligne » dans une phrase et « Formule centrée » pour une égalité importante.</p><div data-content></div><div class="editor-toolbar" aria-label="Outils de rédaction"><button type="button" data-add-text>Nouvelle ligne</button><button type="button" data-add-inline>Formule en ligne</button><button type="button" data-add-display>Formule centrée</button><button type="button" data-add-step>Nouvelle étape de correction</button></div><section data-variables hidden><header class="editor-section-head"><div><h3>Valeurs variables</h3><p>Écris <code>{{a}}</code> dans l’énoncé ou la correction pour utiliser la variable <strong>a</strong>.</p></div><button type="button" class="secondary" data-example>Charger un exemple de dérivation</button></header><div data-variable-list class="variable-list"></div><button type="button" data-add-variable>Ajouter une variable</button><label>Contraintes facultatives<textarea name="constraints" placeholder="a != 0\na < b\ngcd(a,b) = 1"></textarea></label><button type="button" class="secondary" data-advanced-toggle>Mode avancé</button><div class="advanced" data-advanced hidden><p>Réservé aux utilisateurs expérimentés. Le JSON saisi remplace la configuration visuelle après validation.</p><label>Configuration JSON<textarea name="advancedJson"></textarea></label></div></section><p class="form-error" data-editor-error role="alert"></p></section>
 <section class="wizard-step" data-step="4" hidden><h2>Aperçu et publication</h2><article class="card question-preview" data-preview></article><div data-variants></div><p class="form-error" data-preview-error role="alert"></p></section>
 <div class="actions-row editor-actions"><button type="button" data-back>Retour</button><button type="button" class="primary" data-next>Continuer</button><button type="button" data-draft hidden>Enregistrer comme brouillon</button><button type="button" class="primary" data-private hidden>Publier dans mes questions</button><button type="button" class="primary" data-common hidden>Publier pour tous</button><button type="button" data-cancel>Annuler</button></div>`;
 const content=root.querySelector('[data-content]');
 content.innerHTML=`<label data-prompt-label>Énoncé visible par l’élève<textarea name="prompt" placeholder="Exemple : Calculer \\(f'(x)\\)." required></textarea></label><label data-hint-label>Indice facultatif<textarea name="hint" placeholder="Donner une piste sans révéler toute la réponse."></textarea></label><label data-correction-label>Correction détaillée<textarea name="correction" placeholder="Une étape claire par ligne." required></textarea></label><label>Concept ou erreur à retenir<textarea name="concept"></textarea></label><label>Formulation propre à retenir<textarea name="oral"></textarea></label>`;
 for(const[k,v]of Object.entries({title:question?.title||'',category:question?.category||'',difficulty:question?.difficulty||1,prompt:text(question?.prompt_content),hint:text(question?.hint_content),correction:question?.correction_content?.steps?.map(text).join('\n')||'',concept:text(question?.hidden_concept_content),oral:text(question?.oral_formulation_content),constraints:question?.variable_spec?.constraints?.join('\n')||'',advancedJson:''}))if(root.querySelector(`[name=${k}]`))root.querySelector(`[name=${k}]`).value=v;
 activeTextarea=root.querySelector('[name=prompt]');
 root.addEventListener('focusin',event=>{if(event.target instanceof HTMLTextAreaElement&&content.contains(event.target))activeTextarea=event.target});
 const part=root.querySelector('[name=part]'),chapter=root.querySelector('[name=chapter]'),notion=root.querySelector('[name=notion]'),difficulty=root.querySelector('[name=difficulty]');
 fill(part,COURSE_MAP);part.onchange=()=>{fill(chapter,COURSE_MAP.find(p=>p.id===part.value)?.chapters||[]);chapter.dispatchEvent(new Event('change'))};chapter.onchange=()=>fill(notion,COURSE_MAP.flatMap(p=>p.chapters).find(c=>c.id===chapter.value)?.notions||[]);part.value=question?.part_id||COURSE_MAP[0].id;part.dispatchEvent(new Event('change'));chapter.value=question?.chapter_id||chapter.value;chapter.dispatchEvent(new Event('change'));notion.value=question?.notion_id||notion.value;
 const updateLevelWarning=()=>root.querySelector('[data-level-warning]').textContent=pedagogicalError(type,difficulty.value);difficulty.onchange=updateLevelWarning;
 const labels={course:['Énoncé visible par l’élève','Indice facultatif','Correction détaillée'],formula:['Question sur la formule','Hypothèses et domaine','Formule attendue et explication'],parameterized:['Énoncé avec variables','Indice facultatif','Correction avec variables']};
 const applyLabels=()=>{const values=labels[type]||labels.course;root.querySelector('[data-prompt-label]').firstChild.textContent=values[0];root.querySelector('[data-hint-label]').firstChild.textContent=values[1];root.querySelector('[data-correction-label]').firstChild.textContent=values[2];updateLevelWarning()};
 for(const[v,label,desc]of[['course','Question de cours','Faire réciter une définition, une propriété ou un théorème.'],['formula','Formule','Faire retrouver ou appliquer une formule avec une présentation mathématique propre.'],['parameterized','Exercice avec valeurs variables','Créer automatiquement plusieurs variantes d’un même exercice.']]){const b=action(label,()=>{type=v;applyLabels();go(2)});b.classList.add('card','action-card');const p=document.createElement('span');p.textContent=desc;b.append(p);root.querySelector('[data-types]').append(b)}
 function go(n){step=n;root.querySelectorAll('[data-step]').forEach(x=>x.hidden=Number(x.dataset.step)!==step);root.querySelector('[data-progress]').textContent=`Étape ${step} sur 4`;root.querySelector('[data-back]').hidden=step===1;root.querySelector('[data-next]').hidden=step===4;for(const x of['draft','private','common'])root.querySelector(`[data-${x}]`).hidden=step!==4||(x==='common'&&!['admin','owner'].includes(account.role));root.querySelector('[data-variables]').hidden=type!=='parameterized';if(step===4)previewValid=showPreview(root,type,variables);updatePublishButtons()}
 function updatePublishButtons(){for(const name of['private','common']){const button=root.querySelector(`[data-${name}]`);button.disabled=step===4&&!previewValid}}
 const insert=(target,value)=>{const result=insertAtSelection(target.value,target.selectionStart,target.selectionEnd,value);target.value=result.value;target.focus();target.setSelectionRange(result.start,result.end)};
 root.querySelector('[data-next]').onclick=()=>{const warning=pedagogicalError(type,difficulty.value);if(step===2&&warning){root.querySelector('[data-level-warning]').textContent=warning;return}go(Math.min(4,step+1))};
 root.querySelector('[data-back]').onclick=()=>go(Math.max(1,step-1));root.querySelector('[data-cancel]').onclick=closeEditor;
 root.querySelector('[data-add-text]').onclick=()=>insert(activeTextarea||root.querySelector('[name=prompt]'),'\n');
 root.querySelector('[data-add-inline]').onclick=()=>insert(activeTextarea||root.querySelector('[name=prompt]'),mathSnippet({display:false,variable:variables[0]?.name||'a'}));
 root.querySelector('[data-add-display]').onclick=()=>insert(activeTextarea||root.querySelector('[name=prompt]'),mathSnippet({display:true,variable:variables[0]?.name||'a'}));
 root.querySelector('[data-add-step]').onclick=()=>{const target=root.querySelector('[name=correction]');insert(target,target.value?'\n':'');activeTextarea=target};
 function variable(){variables.push(variableDraft({},variables.length));renderVariables(root,variables)}
 root.querySelector('[data-add-variable]').onclick=variable;
 root.querySelector('[data-example]').onclick=()=>{if(!variables.length)variable();const example=parameterizedExample(variables[0].name);for(const[name,value]of Object.entries(example))root.querySelector(`[name=${name}]`).value=value;toast('Exemple chargé. Modifie les valeurs puis vérifie l’aperçu.',{type:'success'})};
 root.querySelector('[data-advanced-toggle]').onclick=()=>{const advanced=root.querySelector('[data-advanced]');advanced.hidden=!advanced.hidden};
 if(!variables.length&&type==='parameterized')variable();else renderVariables(root,variables);
 root.querySelector('[data-draft]').onclick=()=>save(root,type,variables,'draft','private');root.querySelector('[data-private]').onclick=()=>save(root,type,variables,'published','private');root.querySelector('[data-common]').onclick=()=>save(root,type,variables,'published','common');
 if(type){applyLabels();go(2)}
}

function renderVariables(root,variables){
 const list=root.querySelector('[data-variable-list]');list.replaceChildren(...variables.map((v,i)=>{const box=document.createElement('fieldset');box.className='variable-card';box.innerHTML=`<legend>Variable ${v.name}</legend><div class="field-grid"><label>Nom<input data-v="name" value="${v.name}"></label><label>Type<select data-v="type"><option value="integer">Entier</option><option value="natural">Entier naturel</option><option value="nonzero">Entier non nul</option><option value="decimal">Décimal</option><option value="list">Valeur dans une liste</option></select></label><label data-range>Minimum<input data-v="minimum" type="number" value="${v.minimum}"></label><label data-range>Maximum<input data-v="maximum" type="number" value="${v.maximum}"></label><label data-precision>Décimales<input data-v="precision" type="number" min="0" max="6" value="${v.precision}"></label><label data-excluded>Valeurs interdites<input data-v="excluded" value="${v.excluded}" placeholder="0 ; 1"></label><label data-values>Valeurs possibles<input data-v="values" value="${v.values}" placeholder="1 ; 2 ; 5"></label></div><div class="actions-row"><button type="button" data-insert>Insérer {{${v.name}}}</button><button type="button" class="secondary" data-remove>Supprimer</button></div>`;const type=box.querySelector('[data-v=type]');type.value=v.type;const refresh=()=>{const listMode=v.type==='list',decimal=v.type==='decimal';box.querySelectorAll('[data-range]').forEach(node=>node.hidden=listMode);box.querySelector('[data-values]').hidden=!listMode;box.querySelector('[data-precision]').hidden=!decimal;box.querySelector('[data-excluded]').hidden=listMode};refresh();box.querySelectorAll('[data-v]').forEach(input=>input.oninput=()=>{const key=input.dataset.v;v[key]=['minimum','maximum','precision'].includes(key)?Number(input.value):input.value;if(key==='type')refresh();box.querySelector('legend').textContent=`Variable ${v.name}`;box.querySelector('[data-insert]').textContent=`Insérer {{${v.name}}}`});box.querySelector('[data-insert]').onclick=()=>{const target=root.querySelector('[name=prompt]');const result=insertAtSelection(target.value,target.selectionStart,target.selectionEnd,`{{${v.name}}}`);target.value=result.value;target.focus();target.setSelectionRange(result.start,result.end)};box.querySelector('[data-remove]').onclick=()=>{variables.splice(i,1);renderVariables(root,variables)};return box}))
}
function payload(root,type,variables,statusValue,scope){
 const n=allNotions().find(x=>x.id===root.querySelector('[name=notion]').value),seg=value=>({segments:[{type:'text',value:String(value||'')}]});let spec=null;
 if(type==='parameterized'){
  const advanced=root.querySelector('[name=advancedJson]').value.trim();
  if(advanced){try{spec=JSON.parse(advanced)}catch{throw new TypeError('La configuration JSON avancée n’est pas valide.')}}else{const constraints=root.querySelector('[name=constraints]').value.split('\n').map(x=>x.trim()).filter(Boolean);spec={variables:variables.map(variableSpec),constraints,promptTemplate:root.querySelector('[name=prompt]').value,hintTemplate:root.querySelector('[name=hint]').value,correctionTemplates:root.querySelector('[name=correction]').value.split('\n').filter(Boolean)}}
 }
 const now=new Date().toISOString();
 return{id:editing?.id||crypto.randomUUID(),author_id:editing?.author_id||account.userId,scope,status:statusValue,question_type:type,title:root.querySelector('[name=title]').value.trim(),part_id:n?.partId,chapter_id:n?.chapterId,notion_id:n?.id,difficulty:Number(root.querySelector('[name=difficulty]').value),category:root.querySelector('[name=category]').value.trim()||null,prompt_content:seg(root.querySelector('[name=prompt]').value),hint_content:seg(root.querySelector('[name=hint]').value),correction_content:{steps:root.querySelector('[name=correction]').value.split('\n').filter(Boolean).map(seg)},hidden_concept_content:seg(root.querySelector('[name=concept]').value),oral_formulation_content:seg(root.querySelector('[name=oral]').value),variable_spec:spec,tags:editing?.tags||[],version:editing?.version||1,created_at:editing?.created_at||now,updated_at:now};
}
function previewSection(title,content,steps=false){const section=document.createElement('section'),heading=document.createElement('h3'),body=document.createElement('div');heading.textContent=title;steps?renderSteps(body,content):renderSegments(body,content);section.append(heading,body);return section}
function displayValue(value){return value&&Number.isInteger(value.numerator)?value.denominator===1?String(value.numerator):`${value.numerator}/${value.denominator}`:String(value)}
function showPreview(root,type,variables){
 const preview=root.querySelector('[data-preview]'),variantsRoot=root.querySelector('[data-variants]'),error=root.querySelector('[data-preview-error]');preview.replaceChildren();variantsRoot.replaceChildren();error.textContent='';
 try{const q=payload(root,type,variables,'draft','private'),check=validateQuestion(q,{publishing:true});const notion=allNotions().find(item=>item.id===q.notion_id),meta=document.createElement('p');meta.className='question-preview-meta';meta.textContent=`${notion?.chapterLabel||q.chapter_id} · ${notion?.label||q.notion_id} · ${LEVELS[q.difficulty]}`;preview.append(meta,previewSection('Énoncé',q.prompt_content));if(text(q.hint_content).trim())preview.append(previewSection('Indice',q.hint_content));preview.append(previewSection('Correction',q.correction_content,true));if(!check.valid){error.textContent=check.errors.join(' · ');return false}if(type==='parameterized'){const variants=generateVariants(q.variable_spec,10),heading=document.createElement('h3');heading.textContent='10 variantes contrôlées';variantsRoot.append(heading,...variants.map((variant,index)=>{const article=document.createElement('article');article.className='card variant-preview';const title=document.createElement('strong');title.textContent=`Variante ${index+1} · ${Object.entries(variant.values).map(([key,value])=>`${key}=${displayValue(value)}`).join(' · ')}`;const statement=document.createElement('div'),correction=document.createElement('div');renderSegments(statement,{segments:[{type:'text',value:variant.prompt}]});renderSteps(correction,{steps:variant.correction.map(value=>({segments:[{type:'text',value}]}))});article.append(title,statement,correction);return article}))}return true}catch(cause){error.textContent=cause.message||'L’aperçu ne peut pas être généré.';return false}
}
function save(root,type,variables,statusValue,scope){
 let q;try{q=payload(root,type,variables,statusValue,scope)}catch(cause){root.querySelector('[data-editor-error]').textContent=cause.message;toast(cause.message,{type:'error'});return}
 const check=validateQuestion(q,{publishing:statusValue==='published'});if(!check.valid){const message=check.errors[0]||'Certains champs sont incomplets.';root.querySelector('[data-editor-error]').textContent=check.errors.join(' · ');toast(message,{type:'error'});return}
 const target=q.scope==='common'?(q.status==='published'?cache.data.common:cache.data.management):cache.data.private,old=[...cache.data.common,...cache.data.management,...cache.data.private].find(x=>x.id===q.id);for(const list of[cache.data.common,cache.data.management,cache.data.private]){const i=list.findIndex(x=>x.id===q.id);if(i>=0)list.splice(i,1)}target.push(q);enqueue(cache,operation(q.id,old?'update':'create',q,old?.version??null));cache.save();toast('Enregistré sur cet appareil. En attente de synchronisation.',{type:'success'});sync?.sync().then(()=>toast('Synchronisé.',{type:'success'})).catch(()=>toast('La synchronisation reprendra dès que possible.'));closeEditor()
}
function closeEditor(){document.querySelector('[data-editor]').hidden=true;document.querySelector('[data-question-list]').hidden=false;editing=null;render()}
function preview(q){openEditor(q);const root=document.querySelector('[data-editor]');root.querySelector('[data-progress]').textContent='Aperçu de la question';root.querySelectorAll('[data-step]').forEach(x=>x.hidden=x.dataset.step!=='4')}
function duplicate(q,scope){editing=null;const copy={...structuredClone(q),id:crypto.randomUUID(),author_id:account.userId,scope,status:'draft',version:1,title:`Copie de ${q.title}`,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};cache.data[scope==='common'?'management':'private'].push(copy);enqueue(cache,operation(copy.id,'create',copy));cache.save();toast('La copie a été créée comme brouillon.',{type:'success'});render()}
function mutate(q,patch,type='update'){const next={...q,...patch,updated_at:new Date().toISOString()};for(const list of[cache.data.common,cache.data.private,cache.data.management]){const i=list.findIndex(x=>x.id===q.id);if(i>=0)list[i]=next}enqueue(cache,operation(q.id,type,next,q.version));cache.save();render();sync?.sync()}
function publish(q){if(q.scope==='common'&&!['admin','owner'].includes(account.role)){toast('Ton compte n’a pas l’autorisation de publier dans la banque commune.',{type:'error'});return}const check=validateQuestion({...q,status:'published'},{publishing:true});if(!check.valid){toast(check.errors[0]||'La question doit être complétée avant publication.',{type:'error'});return}mutate(q,{status:'published'})}
function archive(q){mutate(q,{status:'archived'},'archive');toast('Question archivée.',{type:'success'})}
function fill(select,rows){select.replaceChildren(...rows.map(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.label;return o}))}
function text(content){return content?.segments?.map(segment=>segment.value).join('\n')||''}
