const SYNC_PROTOCOL_VERSION=1, SYNC_SCHEMA_VERSION=3, SYNC_FORMAT_VERSION=1;
const SYNC_FOLDER_NAME='Quiz TSI Sync', SYNC_FOLDER_PROPERTY='SYNC_FOLDER_ID', SYNC_KEY_HASH_PROPERTY='SYNC_KEY_SHA256';
const SYNC_ACTIONS=Object.freeze(['health','initialize','sync','pull','push','getManifest']);
const SYNC_OPERATION_TYPES=Object.freeze(['append-event','upsert-entity','delete-entity','supersede-event','upload-test-draft','finalize-test-result','update-preference']);
const SYNC_MAX_OPERATION_BYTES=256000;

function doGet(){return jsonResponse_({ok:true,status:'healthy',protocolVersion:SYNC_PROTOCOL_VERSION,serverTime:new Date().toISOString()});}
function doPost(e){try{const request=parseRequest_(e);authenticate_(request.key);validateVersions_(request);return jsonResponse_(routeAction_(request.action,request.data||{}));}catch(error){return jsonResponse_({ok:false,error:structuredError_(error),protocolVersion:SYNC_PROTOCOL_VERSION,serverTime:new Date().toISOString()});}}
function parseRequest_(e){if(!e||!e.postData||typeof e.postData.contents!=='string')throw syncError_('REMOTE_DATA_CORRUPTED','Corps JSON absent');let request;try{request=JSON.parse(e.postData.contents);}catch(error){throw syncError_('REMOTE_DATA_CORRUPTED','Corps JSON invalide');}if(!request||typeof request!=='object'||!SYNC_ACTIONS.includes(request.action))throw syncError_('APPS_SCRIPT_ERROR','Action non autorisée');return request;}
function routeAction_(action,data){if(action==='health')return baseResponse_({status:'healthy'});if(action==='initialize')return initializeSync_();if(action==='getManifest')return baseResponse_({manifest:readManifest_()});if(action==='pull')return pull_(data);if(action==='push'||action==='sync')return synchronize_(data);throw syncError_('APPS_SCRIPT_ERROR','Action non autorisée');}
function validateVersions_(request){if(request.protocolVersion!==SYNC_PROTOCOL_VERSION)throw syncError_('PROTOCOL_MISMATCH','Version de protocole incompatible');if(request.schemaVersion!==SYNC_SCHEMA_VERSION)throw syncError_('SCHEMA_MISMATCH','Version de schéma incompatible');}
function baseResponse_(value){return Object.assign({ok:true,protocolVersion:SYNC_PROTOCOL_VERSION,serverTime:new Date().toISOString()},value);}
function jsonResponse_(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
function syncError_(code,message){const error=new Error(message);error.code=code;return error;}
function structuredError_(error){return{code:error&&error.code||mapGoogleError_(error),message:String(error&&error.message||'Erreur Apps Script').slice(0,300)};}
function mapGoogleError_(error){const text=String(error&&error.message||error);if(/quota|limit exceeded/i.test(text))return'QUOTA_EXCEEDED';if(/drive|file|folder/i.test(text))return'DRIVE_UNAVAILABLE';return'APPS_SCRIPT_ERROR';}

function generateSyncKey(){const bytes=[];for(let i=0;i<4;i++)bytes.push(Utilities.getUuid().replace(/-/g,''));const key=bytes.join('');PropertiesService.getScriptProperties().setProperty(SYNC_KEY_HASH_PROPERTY,sha256Text_(key));return key;}
function revokeSyncKey(){PropertiesService.getScriptProperties().deleteProperty(SYNC_KEY_HASH_PROPERTY);return{ok:true};}
function rotateSyncKey(){revokeSyncKey();return generateSyncKey();}
function authenticate_(key){const expected=PropertiesService.getScriptProperties().getProperty(SYNC_KEY_HASH_PROPERTY);if(!expected||typeof key!=='string'||!constantTimeEqual_(sha256Text_(key),expected))throw syncError_('AUTH_INVALID','Clé de synchronisation invalide');}
function constantTimeEqual_(a,b){if(a.length!==b.length)return false;let value=0;for(let i=0;i<a.length;i++)value|=a.charCodeAt(i)^b.charCodeAt(i);return value===0;}

function initializeSync_(){const lock=LockService.getScriptLock();lock.waitLock(30000);try{return baseResponse_({manifest:ensureStorage_().manifest});}finally{lock.releaseLock();}}
function getOrCreateRoot_(){const props=PropertiesService.getScriptProperties(),known=props.getProperty(SYNC_FOLDER_PROPERTY);if(known){try{return DriveApp.getFolderById(known);}catch(error){props.deleteProperty(SYNC_FOLDER_PROPERTY);}}const folders=DriveApp.getFoldersByName(SYNC_FOLDER_NAME),folder=folders.hasNext()?folders.next():DriveApp.createFolder(SYNC_FOLDER_NAME);props.setProperty(SYNC_FOLDER_PROPERTY,folder.getId());return folder;}
function childFolder_(parent,name){const folders=parent.getFoldersByName(name);return folders.hasNext()?folders.next():parent.createFolder(name);}
function writeFile_(folder,name,value,fileId){const content=JSON.stringify(value,null,2);let file=null;if(fileId){try{file=DriveApp.getFileById(fileId);}catch(error){file=null;}}if(!file){const files=folder.getFilesByName(name);file=files.hasNext()?files.next():null;}if(file)file.setContent(content);else file=folder.createFile(name,content,MimeType.PLAIN_TEXT);return{id:file.getId(),checksum:sha256Text_(canonical_(value))};}
function ensureStorage_(){const root=getOrCreateRoot_(),state=childFolder_(root,'state'),snapshots=childFolder_(root,'snapshots');const existing=findJson_(root,'manifest.json');if(existing)return{root:root,state:state,snapshots:snapshots,manifest:existing.value};const installationId=Utilities.getUuid(),emptyEvents={events:[],processedOperations:{}},emptyEntities={entities:{}},emptyPreferences={preferences:{}};const files={events:writeFile_(state,'events.json',emptyEvents),entities:writeFile_(state,'entities.json',emptyEntities),preferences:writeFile_(state,'preferences.json',emptyPreferences)};const snapshot={formatVersion:1,serverRevision:0,events:[],entities:{},preferences:{}};const snap=writeFile_(snapshots,'latest.json',snapshot);const manifest=buildManifest_(0,installationId,{events:files.events.id,entities:files.entities.id,preferences:files.preferences.id,snapshot:snap.id},{events:files.events.checksum,entities:files.entities.checksum,preferences:files.preferences.checksum,snapshot:snap.checksum});writeFile_(root,'manifest.json',manifest);return{root:root,state:state,snapshots:snapshots,manifest:manifest};}
function buildManifest_(revision,installationId,fileIds,checksums){const base={formatVersion:SYNC_FORMAT_VERSION,protocolVersion:SYNC_PROTOCOL_VERSION,schemaVersion:SYNC_SCHEMA_VERSION,serverRevision:revision,updatedAt:new Date().toISOString(),installationId:installationId,fileIds:fileIds,checksums:checksums};base.checksum=sha256Text_(canonical_(base));return base;}
function findJson_(folder,name){const files=folder.getFilesByName(name);if(!files.hasNext())return null;const file=files.next();try{return{file:file,value:JSON.parse(file.getBlob().getDataAsString('UTF-8'))};}catch(error){throw syncError_('REMOTE_DATA_CORRUPTED',name+' est invalide');}}
function readManifest_(){const storage=ensureStorage_(),manifest=storage.manifest,content=Object.assign({},manifest);delete content.checksum;if(manifest.checksum!==sha256Text_(canonical_(content)))throw syncError_('CHECKSUM_INVALID','Checksum du manifest invalide');return manifest;}
function readState_(manifest){return{events:readChecked_(manifest.fileIds.events,manifest.checksums.events).events||[],entities:readChecked_(manifest.fileIds.entities,manifest.checksums.entities).entities||{},preferences:readChecked_(manifest.fileIds.preferences,manifest.checksums.preferences).preferences||{},processedOperations:readChecked_(manifest.fileIds.events,manifest.checksums.events).processedOperations||{}};}
function readChecked_(fileId,expected){let value;try{value=JSON.parse(DriveApp.getFileById(fileId).getBlob().getDataAsString('UTF-8'));}catch(error){throw syncError_('REMOTE_DATA_CORRUPTED','Fichier Drive invalide');}if(sha256Text_(canonical_(value))!==expected)throw syncError_('CHECKSUM_INVALID','Checksum Drive invalide');return value;}
function pull_(data){const manifest=readManifest_();if(!Number.isInteger(data.sinceRevision)||data.sinceRevision<0)throw syncError_('SERVER_CONFLICT','Révision client invalide');const state=readState_(manifest);return baseResponse_({acceptedOperationIds:[],rejectedOperations:[],newServerRevision:manifest.serverRevision,remoteChanges:data.sinceRevision<manifest.serverRevision?state:{events:[],entities:{},preferences:{}},conflicts:[]});}
function synchronize_(data){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const storage=ensureStorage_(),manifest=readManifest_();if(!Number.isInteger(data.baseServerRevision)||data.baseServerRevision!==manifest.serverRevision)throw syncError_('SERVER_CONFLICT','Révision serveur obsolète');const operations=Array.isArray(data.operations)?data.operations:[],state=readState_(manifest),accepted=[],rejected=[],conflicts=[];for(const operation of operations){const validation=validateOperation_(operation);if(!validation.valid){rejected.push({operationId:operation&&operation.operationId||null,error:validation.error});continue;}const prior=state.processedOperations[operation.operationId];if(prior){if(prior!==operation.checksum)conflicts.push({type:'operation-content-mismatch',operationId:operation.operationId});else accepted.push(operation.operationId);continue;}const result=applyOperation_(state,operation);if(result.conflict){conflicts.push(result.conflict);continue;}state.processedOperations[operation.operationId]=operation.checksum;accepted.push(operation.operationId);}const revision=accepted.length||conflicts.length||rejected.length?manifest.serverRevision+1:manifest.serverRevision;const eventsFile=writeFile_(storage.state,'events.json',{events:state.events,processedOperations:state.processedOperations},manifest.fileIds.events),entitiesFile=writeFile_(storage.state,'entities.json',{entities:state.entities},manifest.fileIds.entities),preferencesFile=writeFile_(storage.state,'preferences.json',{preferences:state.preferences},manifest.fileIds.preferences);const snapshotValue={formatVersion:1,serverRevision:revision,events:state.events,entities:state.entities,preferences:state.preferences},snapshotFile=writeFile_(storage.snapshots,'latest.json',snapshotValue,manifest.fileIds.snapshot);const next=buildManifest_(revision,manifest.installationId,{events:eventsFile.id,entities:entitiesFile.id,preferences:preferencesFile.id,snapshot:snapshotFile.id},{events:eventsFile.checksum,entities:entitiesFile.checksum,preferences:preferencesFile.checksum,snapshot:snapshotFile.checksum});writeFile_(storage.root,'manifest.json',next);return baseResponse_({acceptedOperationIds:accepted,rejectedOperations:rejected,newServerRevision:revision,remoteChanges:{events:state.events,entities:state.entities,preferences:state.preferences},conflicts:conflicts});}finally{lock.releaseLock();}}
function validateOperation_(operation){try{if(!operation||!uuidValid_(operation.operationId)||!SYNC_OPERATION_TYPES.includes(operation.operationType))throw syncError_('REMOTE_DATA_CORRUPTED','Opération invalide');if(operation.protocolVersion!==SYNC_PROTOCOL_VERSION)throw syncError_('PROTOCOL_MISMATCH','Protocole invalide');if(operation.schemaVersion!==SYNC_SCHEMA_VERSION)throw syncError_('SCHEMA_MISMATCH','Schéma invalide');if(!Number.isInteger(operation.baseServerRevision)||!finiteTree_(operation)||!Date.parse(operation.createdAt))throw syncError_('REMOTE_DATA_CORRUPTED','Valeur invalide');if(Utilities.newBlob(JSON.stringify(operation)).getBytes().length>SYNC_MAX_OPERATION_BYTES)throw syncError_('PAYLOAD_TOO_LARGE','Opération trop volumineuse');const content=Object.assign({},operation);delete content.checksum;if(operation.checksum!==sha256Text_(canonical_(content)))throw syncError_('CHECKSUM_INVALID','Checksum invalide');return{valid:true};}catch(error){return{valid:false,error:structuredError_(error)};}}
function applyOperation_(state,op){if(op.operationType==='append-event'||op.operationType==='supersede-event'){const prior=state.events.find(e=>e.id===op.entityId);if(prior&&canonical_(prior)!==canonical_(op.payload))return{conflict:{type:'event-content-mismatch',entityId:op.entityId}};if(!prior)state.events.push(op.payload);return{};}if(op.operationType==='upload-test-draft'){const prior=state.entities[op.entityId];if(prior&&canonical_(prior)!==canonical_(op.payload))return{conflict:{type:'draft-diverged',entityId:op.entityId,versions:[prior,op.payload]}};state.entities[op.entityId]=op.payload;return{};}if(op.operationType==='update-preference'){const prior=state.preferences[op.entityId],next=op.payload;if(!prior||next.updatedAt>prior.updatedAt||next.updatedAt===prior.updatedAt&&String(next.deviceId)>String(prior.deviceId))state.preferences[op.entityId]=next;return{};}if(op.operationType==='delete-entity')delete state.entities[op.entityId];else state.entities[op.entityId]=op.payload;return{};}
function uuidValid_(value){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value||'');}
function finiteTree_(value){if(typeof value==='number')return Number.isFinite(value);if(value&&typeof value==='object')return Object.keys(value).every(k=>finiteTree_(value[k]));return typeof value!=='function'&&typeof value!=='undefined';}
function canonical_(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return'['+value.map(canonical_).join(',')+']';return'{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical_(value[k])).join(',')+'}';}
function sha256Text_(text){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,text,Utilities.Charset.UTF_8).map(byte=>(byte<0?byte+256:byte).toString(16).padStart(2,'0')).join('');}
