import{readFile,readdir,stat}from'node:fs/promises';
import path from'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname);const errors=[];const checked=new Set();
const fail=(kind,file,value)=>errors.push(`${kind}: ${file}${value?` -> ${value}`:''}`);
async function exactFile(relative,from='.'){
 const clean=relative.replace(/^\.\//,'').split(/[?#]/)[0];if(!clean||clean==='.')return true;
 let current=root;for(const part of clean.split('/')){if(part==='..'){current=path.dirname(current);continue}let names;try{names=await readdir(current)}catch{return false}if(!names.includes(part))return false;current=path.join(current,part)}try{return(await stat(current)).isFile()}catch{return false}
}
async function walk(dir){const out=[];for(const entry of await readdir(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())out.push(...await walk(full));else out.push(path.relative(root,full))}return out}
const files=await walk(root);
async function checkModule(relative){if(checked.has(relative))return;checked.add(relative);const source=await readFile(path.join(root,relative),'utf8');const pattern=/(?:\bfrom\s*|\bimport\s*\(?)['"]([^'"]+)['"]/g;for(const match of source.matchAll(pattern)){if(!match[1].startsWith('.'))continue;const target=path.normalize(path.join(path.dirname(relative),match[1]));if(!await exactFile(target))fail('Import absent ou mauvaise casse',relative,match[1]);else if(target.endsWith('.js'))await checkModule(target)}}
await checkModule('scripts/app.js');
const html=await readFile(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/<(?:script|link)\b[^>]*(?:src|href)=["']([^"']+)["']/g)){const ref=match[1];if(/^https?:/.test(ref))fail('Ressource distante', 'index.html',ref);else if(ref.startsWith('/'))fail('Chemin racine incompatible avec /quizz-prepa/','index.html',ref);else if(!await exactFile(ref))fail('Ressource HTML absente ou mauvaise casse','index.html',ref)}
const manifest=JSON.parse(await readFile(path.join(root,'manifest.webmanifest'),'utf8'));for(const ref of [manifest.start_url,...(manifest.icons||[]).map(x=>x.src)]){if(ref.startsWith('/'))fail('Chemin manifest incompatible avec /quizz-prepa/','manifest.webmanifest',ref);else if(!await exactFile(ref))fail('Ressource manifest absente','manifest.webmanifest',ref)}
const sw=await readFile(path.join(root,'service-worker.js'),'utf8'),coreMatch=sw.match(/const CORE_RESOURCES=(\[[^;]+\]);/);if(!coreMatch)fail('Liste de précache illisible','service-worker.js');const core=coreMatch?JSON.parse(coreMatch[1].replaceAll("'",'"')):[];for(const ref of core)if(ref!=='./'&&!await exactFile(ref))fail('Ressource de précache absente ou mauvaise casse','service-worker.js',ref);
for(const module of checked)if(!core.includes(`./${module}`))fail('Module de démarrage absent du précache','service-worker.js',module);
for(const required of ['./index.html','./vendor/katex/katex.min.js','./vendor/katex/katex.min.css'])if(!core.includes(required))fail('Ressource PWA obligatoire absente','service-worker.js',required);
for(const cssFile of ['styles/app.css','styles/katex-overrides.css','vendor/katex/katex.min.css']){const css=await readFile(path.join(root,cssFile),'utf8');for(const match of css.matchAll(/url\((?:["'])?([^"')]+)(?:["'])?\)/g)){if(match[1].startsWith('data:'))continue;const target=path.normalize(path.join(path.dirname(cssFile),match[1]));if(!await exactFile(target))fail('Ressource CSS absente ou mauvaise casse',cssFile,match[1])}}
for(const file of files.filter(x=>x.endsWith('.json')||x.endsWith('.webmanifest'))){try{JSON.parse(await readFile(path.join(root,file),'utf8'))}catch(error){fail(`JSON invalide (${error.message})`,file)}}
const textFiles=files.filter(x=>!x.startsWith('vendor/')&&!/\.(?:woff2?|ttf|png|ico)$/.test(x));for(const file of textFiles){const source=await readFile(path.join(root,file),'utf8');if(/^(<<<<<<<|=======|>>>>>>>)/m.test(source))fail('Marqueur de conflit Git',file);if(/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]{20,}\/exec/.test(source))fail('URL Apps Script réelle probable',file);if(/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(source)||/(?:AIza[0-9A-Za-z_-]{30,}|gh[oprs]_[0-9A-Za-z]{30,}|sb_secret_[0-9A-Za-z_-]{12,}|service_role\s*[:=]|JWT[_ -]?secret\s*[:=])/i.test(source))fail('Secret évident probable',file)}
const appManifest=JSON.parse(await readFile(path.join(root,'apps-script/appsscript.json'),'utf8'));const scopes=new Set(appManifest.oauthScopes||[]);if(!scopes.has('https://www.googleapis.com/auth/drive')&&!scopes.has('https://www.googleapis.com/auth/drive.file'))fail('Autorisation Drive absente','apps-script/appsscript.json');
if(!/event\.request\.method!==['"]GET['"]/.test(sw)||!/url\.origin!==self\.location\.origin/.test(sw))fail('Les requêtes de synchronisation ne sont pas explicitement exclues du cache','service-worker.js');


// Les ressources livrées par GitHub Pages ne doivent contenir aucune capacité
// d'administration serveur. supabase/functions est volontairement hors périmètre.
const publicFiles=files.filter(file=>file==='service-worker.js'||file==='manifest.webmanifest'||file.endsWith('.html')||file.endsWith('.css')||file.startsWith('scripts/'));
const forbiddenPublic=[[/sb_secret_/i,'préfixe de clé secrète'],[/service_role/i,'service role'],[/SUPABASE_SECRET_KEY/,'variable secrète'],[/auth\s*\.\s*admin/,'Auth Admin'],[/admin\s*\.\s*(?:listUsers|inviteUserByEmail|updateUserById)/,'méthode Auth Admin'],[/console\.(?:log|info|debug)\s*\([^)]*(?:token|authorization)/i,'journalisation de token'],[/localStorage[^\n;]*(?:team.?users|list-users)/i,"liste d’équipe en stockage local"],[/caches?\.(?:put|add)[^\n;]*team-admin/i,"réponse d’administration en cache"]];
for(const file of publicFiles){const source=await readFile(path.join(root,file),'utf8');for(const[pattern,label]of forbiddenPublic){const sanitizerDefinition=file==='scripts/progress-sync/progress-sync-errors.js'&&source.includes("replace(SECRET,'[confidentiel]')")&&['préfixe de clé secrète','service role'].includes(label);if(!sanitizerDefinition&&pattern.test(source))fail(`Ressource publique interdite (${label})`,file)}}
if(errors.length){console.error(`Audit statique échoué (${errors.length} anomalie(s)):\n- ${errors.join('\n- ')}`);process.exitCode=1}else console.log(`Audit statique réussi : ${checked.size} modules, ${core.length} ressources PWA, sécurité publique et JSON validés.`)
