import{randInt,nonZero,choice,createQuestion}from'../generator-utils.js';
export function generateArithmeticSequence(difficulty=1){
 const u0=randInt(-12,12),r=nonZero(-6,6),n=randInt(5,difficulty>2?20:12);const un=u0+n*r;const count=n+1;const sum=count*(u0+un)/2;
 return createQuestion({id:`seq-arith-${u0}-${r}-${n}`,partId:'C',chapterId:'sequences',notionId:'sequence-arithmetic',difficulty,questionHtml:`On définit <span class="math">u₀ = ${u0}</span> et <span class="math">uₙ₊₁ = uₙ ${r>=0?'+':'−'} ${Math.abs(r)}</span>. Donner <span class="math">u${n}</span>, le sens de variation, puis <span class="math">u₀ + … + u${n}</span>.`,hint:'Suite arithmétique : uₙ = u₀ + nr. Pour la somme, compter n+1 termes.',correctionHtml:`<span class="math">u${n} = ${u0} + ${n}×(${r}) = ${un}</span>. La suite est ${r>0?'strictement croissante':'strictement décroissante'}. La somme vaut <span class="math">${count}×(${u0}+${un})/2 = ${sum}</span>.`,hiddenConcept:'De u₀ à uₙ inclus, il y a n+1 termes.',oralFormulation:'« Je vérifie toujours le nombre de termes : dernier indice moins premier indice plus un. »',generator:'sequences.arithmetic'});
}
export function generateGeometricSequence(difficulty=2){
 const u0=choice([1,2,3,4,5,-1,-2]),q=choice(difficulty>2?[-3,-2,2,3]:[2,3]),n=randInt(3,7);const un=u0*q**n;const sum=q===1?(n+1)*u0:u0*(1-q**(n+1))/(1-q);
 return createQuestion({id:`seq-geo-${u0}-${q}-${n}`,partId:'C',chapterId:'sequences',notionId:'sequence-geometric',difficulty,questionHtml:`On définit <span class="math">u₀ = ${u0}</span> et <span class="math">uₙ₊₁ = ${q}uₙ</span>. Calculer <span class="math">u${n}</span> et la somme <span class="math">u₀ + … + u${n}</span>.`,hint:'Suite géométrique : uₙ = u₀qⁿ et somme = u₀(1−qⁿ⁺¹)/(1−q) si q ≠ 1.',correctionHtml:`<span class="math">u${n} = ${u0}×${q}${'ⁿ'.replace('ⁿ',String(n))} = ${un}</span>. La somme vaut <span class="math">${sum}</span>.`,hiddenConcept:'La formule de somme utilise le nombre de termes, ici n+1.',oralFormulation:'« J’identifie le premier terme, la raison et le nombre exact de termes. »',generator:'sequences.geometric'});
}
export const sequenceGenerators=[generateArithmeticSequence,generateGeometricSequence];
